### PR TITLE
fix(nuxt): allow changing dirs within modules

### LINKED ISSUE #15686: changing the nuxt "dir" option through a module doesn't work
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `()`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-m8hu6q?file=nuxt.config.ts

### Describe the bug

Customizing the dir options using a module doesn't work anymore.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/15686

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This allows changing the `dir` options by respecting `nuxt.options.dir` when used in the root/base layer.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/nuxt.ts [hunk 1]
```diff
@@ -190,9 +190,10 @@ async function initNuxt (nuxt: Nuxt) {
 
   // Automatically register user modules
   for (const config of nuxt.options._layers.map(layer => layer.config).reverse()) {
+    const modulesDir = (config.rootDir === nuxt.options.rootDir ? nuxt.options : config).dir?.modules || 'modules'
```
Comment (pi0) [inline packages/nuxt/src/core/nuxt.ts:193]: Note: We shall find a better way to mark top level layer (in resolver maybe) to avoid rootDir === rootDir checks

**Review by pi0 — APPROVED** [review]
Nice fixes! I think as later improvement refactors we might:

- Mark top level layer explicitly when loading config
- Have kit util like `getDir` and possibly an ENUM for the defaults to avoid possible issues in different places.

File: packages/nuxt/src/core/nuxt.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/nuxt.ts:193]: that would be great 👍
