### PR TITLE
fix(nuxt): use `undefined` rather than `null` for data fetching defaults

### LINKED ISSUE #26295: Settle on either `undefined` or `null` for async data's data and error
### Describe the feature

Currently, there is a discrepancy in default values of async data's data and error:
- data is assigned an `undefined` value (unless a different default value is specified)
- error is assigned a `null` value

It would be good to consider settling on one of them for consistency, unless there's a justifiable reason for why they have to differ.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/26295

### 📚 Description

This updates the default value for error + data in `useFetch` and `useAsyncData`, as well as in `useError()`. It updates both the types and the runtime value in a backwards compatible way, so `future.compatibilityVersion: 4` is respected.

One note: previously the default value of `useAsyncData` was inconsistent. It was initialised to `null` but cleared in `clearNuxtData` to `undefined`. This PR preserves the inconsistency for v3 compatibility mode.

### CODE REVIEW

**Comment by pi0** [comment]
`undefined` forever 🚀

File: packages/nuxt/index.d.ts [hunk 1]
```diff
@@ -19,4 +19,10 @@ declare global {
   }
 }
 
+declare module '#app/defaults' {
+  type DefaultAsyncDataErrorValue = undefined
+  type DefaultAsyncDataValue = undefined
```
Comment (pi0) [inline packages/nuxt/index.d.ts:24]: Nice idea for dynamic default types!

**Review by atinux — APPROVED** [review]
