### PR TITLE
fix(vite): prevent CSS flickering after config changes in dev mode

### LINKED ISSUE #33823: Nuxt 4.2 is flickering when changing CSS
### Environment

````
------------------------------
- Operating System: Ubuntu Linux 24.04
- Node Version:     v24.11.0
- Nuxt Version:     4.2.1
- CLI Version:      3.30.0
- Nitro Version:    2.12.9
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      devtools, modules, css, vite, compatibilityDate
- Runtime Modules:  @nuxt/fonts@0.12.1, @vueuse/nuxt@14.1.0
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/nuxt-4-2-flickering

### Describe the bug

I just installed a brand new Nuxt 4.2 project with TailwindCSS module. But when I change the `nuxt.config.ts` css section and reload the page, it starts flickering on every refresh. I noticed it started flickering also on other changes, just don't remember what else I did. But it definitely does this when `nuxt.config.ts` is changed.

Steps to reproduce:
1. Run `pnpm dev`
2. Open the app at http://localhost:3000 - refresh a few times - no flickering (good)
3. Now edit the `nuxt.config.ts` file css section, change `app.css` to `app2.css`
4. Refresh the page - you will see an error (good because app2 does not exist)
5. Go back and fix it. Change `app2.css` back to `app.css`
6. Refresh the page - now it flickers on every refresh (this is the bug)  ❌

**Screencast:**
https://www.youtube.com/watch?v=dDwbLQ7w958

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Flo0806**
### 🔗 Linked issue

resolves: #33823

## Summary

  - Fixes CSS flickering (FOUC) that occurs after `nuxt.config` changes trigger a dev server restart
  - Adds global CSS from `nuxt.options.css` to the manifest as a fallback when the Vite moduleGraph is empty

## Problem
When the dev server restarts after config changes, the moduleGraph is empty on the first request. This causes global CSS defined in `nuxt.config.ts` to be missing from the manifest, resulting in a flash of unstyled content until the CSS modules are loaded.

## Solution

Always include CSS paths from `nuxt.options.css` in the manifest, regardless of moduleGraph state. The `Set` ensures no duplicates when CSS is also present in moduleGraph.

### CODE REVIEW

File: packages/vite/src/plugins/vite-node.ts [hunk 1]
```diff
@@ -81,6 +83,15 @@ function getManifest (nuxt: Nuxt, viteServer: ViteDevServer, clientEntry: string
     }
   }
 
+  // Add global CSS from config as fallback to prevent FOUC
+  // This ensures CSS is in manifest even if moduleGraph isn't populated yet
+  for (const globalCss of nuxt.options.css) {
+    if (typeof globalCss === 'string') {
+      // Resolve ~/ alias to root-relative path for Vite
+      css.add(globalCss.startsWith('~/') ? '/' + globalCss.slice(2) : globalCss)
```
Comment (danielroe) [inline packages/vite/src/plugins/vite-node.ts]: we have a resolveAlias kit util that may be useful here

**Comment by Flo0806** [comment]
@danielroe conflicts are fixed if you want add that to the next fix release

**Review by danielroe — APPROVED** [review]

**Comment by wokalek** [comment]
Not working for me at version 4.4.2, Windows, pnpm, node 24.14.1.
