### PR TITLE
fix: fix issues with route normalization

### LINKED ISSUE #8458: "export 'normalizeURL' was not found in '@nuxt/ufo' [IE]
<!-- 💚 Thanks for your time to make Nuxt better with your feedbacks 💚

**IMPORTANT** Before reporting a bug:

- Please make sure that you have read through Nuxt documentation: https://nuxtjs.org
- If issue is related to a module please create the issue in corresponding repository
- Ensure using latest version of nuxt dependencies using `yarn upgrade nuxt` or `npm upgrade nuxt`

👍 A properly detailed bug report can save a LOT of time and help fixing issues as soon as possible.
-->

### Versions

- nuxt: v2.14.10
- node: v14.15.0 

<!--### Reproduction-->

<!--
Link to a minimal test case based on one of:
- A fork of https://template.nuxtjs.org
- A GitHub repository that can reproduce the bug
Without a reproduction, it is so hard to address problem :(
-->

<!--<details open>
<summary>Additional Details</summary>
<br> -->
<!-- Attaching `nuxt.config`, dependencies, logs or code snippets would help to find the issue -->
</details>

### What is actually happening?

When running `nuxt` with the latest release 2.14.10, the following warning occurs:

`"export 'normalizeURL' was not found in '@nuxt/ufo'`

#### Command Line Output
```
$ nuxt
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                                                                      nuxt:tailwindcss 10:30:21
ℹ Merging Tailwind config from ~/tailwind.config.js                                                                                                                                                                      nuxt:tailwindcss 10:30:21
ℹ [HPM] Proxy created: /  -> https://staging.example.com                                                                                                                                                                                 10:30:22
ℹ [HPM] Proxy rewrite rule created: "^/api/" ~> "/spa/"                                                                                                                                                                                   10:30:22

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.14.10                     │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      server               │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                                                                                       10:30:23
ℹ Initial build may take a while                                                                                                                                                                                                          10:30:23
ℹ Tailwind Colors available on http://localhost:3000/_tailwind                                                                                                                                                           nuxt:tailwindcss 10:30:23
✔ Builder initialized                                                                                                                                                                                                                     10:30:23
✔ Nuxt files generated                                                                                                                                                                                                                    10:30:23

✔ Client
  Compiled successfully in 22.97s

✔ Server
  Compiled successfully in 21.86s


 WARN  Compiled with 1 warnings                                                                                                                                                                                           friendly-errors 10:30:46


 WARN  in ./.nuxt/utils.js                                                                                                                                                                                                friendly-errors 10:30:46

"export 'normalizeURL' was not found in '@nuxt/ufo'                                                                                                                                                                       friendly-errors 10:30:46
                                                                                                                                                                                                                          friendly-errors 10:30:46
ℹ Waiting for file changes                                                                                                                                                                                                                10:30:46
ℹ Memory usage: 319 MB (RSS: 704 MB)                                                                                                                                                                                                      10:30:46
ℹ Listening on: http://localhost:3000/                                                                                                                                                                                                    10:30:46
```

#### Browser Console Output

```
TypeError: Object(...) is not a function
    NuxtJS 2
        getLocation
        _callee2$
    Babel 10
        tryCatch
        invoke
        defineIteratorMethods
        asyncGeneratorStep
        _next
        promise callback*asyncGeneratorStep
        _next
        _asyncToGenerator
        _asyncToGenerator
        _createApp
    NuxtJS 11
        createApp
        <anonymous>
        <anonymous>
        js
        __webpack_require__
        fn
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
[HMR] bundle 'client' has 2 warnings client.js:195
./.nuxt/utils.js 455:9-21
"export 'normalizeURL' was not found in '@nuxt/ufo'
./.nuxt/router.js 255:11-23
"export 'normalizeURL' was not found in '@nuxt/ufo'

```

Although it is defined as warning, it causes parts of the app not being rendered (correctly).


### What is Expected?

Export should be found, and app should be rendered correctly.

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

History: vuejs/vue-router#3350 > #8325 > #8421 > #8430

- Add `url-polyfill` (2.1 kB min/gzip) to fix IE11 issue (URL is not a constructor) (resolves #8458)
- Update to [@nuxt/ufo@0.1.0](https://github.com/nuxt-contrib/ufo/blob/main/CHANGELOG.md#010-2020-12-09) preserving relative links (resovles #8457, #8459)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — APPROVED** [review]

**Review by danielroe — APPROVED** [review]

File: packages/vue-app/template/utils.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import Vue from 'vue'
+import 'url-polyfill'
```
[the remark this answers is not in the document]
Comment (pi0) [reply packages/vue-app/template/utils.js]: ba4dbdd2844eb6e052136038f2b69189187030f1 :D

File: test/dev/async-config.size-limit.test.js [hunk 2]
```diff
@@ -20,20 +20,20 @@ describe('nuxt basic resources size limit', () => {
...
-    const LEGACY_JS_RESOURCES_BROTLI_KB_SIZE = 60
+    const LEGACY_JS_RESOURCES_BROTLI_KB_SIZE = 64
     expect(legacyResourcesSize.brotli).toBeWithinSize(LEGACY_JS_RESOURCES_BROTLI_KB_SIZE)
   })
 
   it('should stay within the size limit range in modern mode', async () => {
     const modernResourcesSize = await getResourcesSize(distDir, 'modern', { gzip: true, brotli: true })
 
-    const MODERN_JS_RESOURCES_KB_SIZE = 172
+    const MODERN_JS_RESOURCES_KB_SIZE = 180
```
Comment (pi0) [inline test/dev/async-config.size-limit.test.js:36]: No ideas why this increased maybe something shared? /cc @clarkdo

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: polyfill？

Comment (pi0) [reply test/dev/async-config.size-limit.test.js:36]: Indeed but it is added conditionally: https://github.com/nuxt/nuxt.js/pull/8462/files#diff-2159334eca1dc836bb579a16572dc7d1a52e7777661a52424e9efdcddb84e546R209

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: I think babel detected ufo is using URL and added a polyfill

Comment (pi0) [reply test/dev/async-config.size-limit.test.js:36]: In that case it would be worst :D Since URL constructor polyfill is only for IE (so babel preset for modern shouldn't do) and also if it was doing polyfill we didn't need it. I think only corejs@3 has this polyfill... 

Anyway nothing important since gzip is fine. Something might be wrong with tests

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: corejs seems supporting URL but not URLSearchParams.

Comment (pi0) [reply test/dev/async-config.size-limit.test.js:36]: Actually it is in [web-standards 3](https://github.com/zloirock/core-js/tree/v3#web-standards) but not [web-standards 2](https://github.com/zloirock/core-js/tree/v2#web-standards) :))

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: Have you checked analyzer report?

Comment (pi0) [reply test/dev/async-config.size-limit.test.js:36]: image

nothing there...

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: I’ll check with my laptop

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: Checked bundle size, there is no difference before and after, I think you're right there is sth wrong in test, I'll run through the code an try to fix.

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: Just checked the test, I think the test is fine, actually we have a min 0.95 and max 1.05 value for the size. The max value was 172*1.05 = 180.6, the modern bundle size was around 180 which is just OK for the assertion, but the bundle size is 1-2 kb larger than before now and just exceed the max value.

Comment (pi0) [reply test/dev/async-config.size-limit.test.js:36]: oh this makes sense now. Do you have any idea of windows failing test? (added possix due to vendor chunk creation)

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: Looks this branch is not latest dev, is that expected ?

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: I just merged dev and let's see the test result

Comment (clarkdo) [reply test/dev/async-config.size-limit.test.js:36]: Fixed
