### PR TITLE
fix(nuxt): prevent cache reset on excluded pages and solve transition warning

### LINKED ISSUE #27401: keep alive caches are destroyed when visit keep alive excluded page
### Environment

"nuxt": "^3.11.2"

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fzarr5

1. Visit A Page and type something. go back,
2. Visit B Page and type something. go back.
3. Visit A, B Page. cache works nice.
4. But after visit C Page, Page A, B caches are gone.

### Describe the bug

keep alive caches are destroyed when visit keep alive excluded page

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #27777: nuxtpage modifies name of component names which interferes with keepalive
### Environment

node: 18.12.0
nuxt: 3.12.2
vue: 3.4.29
vue-router: 4.3.3

### Reproduction

Easy to reproduce

### Describe the bug

企业微信截图_319fd01e-03c3-487f-8341-aa7c046efa47
调试发现NuxtPage这种方式修改组件名，好像导致了所有缓存的组件的名称变成了当前组件的名称

企业微信截图_86252c5a-c1f0-491f-8b77-7c933d890df3
因为所有的组件名称变成了一个，导致通过改变include的值去控制删除已缓存的组件的时候出现问题

企业微信截图_78938f11-bda0-45a9-a4a2-16ff71e6624f

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #28609: Dynamically changing the keepalive include attribute will invalidate all cached pages
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-v6enyd?file=composables%2Fcache.ts,app.vue,pages%2Findex.vue,pages%2Fpage2.vue

### Describe the bug

page1 and page2 are cached
1. click 'go to page1'
2. click 'a++'
3. click 'back to home'
4. click 'go to page1', a is still 2, which is correct
5. click 'back to home' and click 'only cache page1'
6. click 'go to page1', a is 1, which is incorrect

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #30806: `<NuxtPage>` slots not working with transition
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.15.3
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pjcxjvhm?file=app.vue,pages/index.vue

### Describe the bug

1. Open the **minimal reproduction**.  
2. Open the browser **devtools**, and you will see a Vue warning:  

   ```text
   [Vue warn]: Component inside <Transition> renders non-element root node that cannot be animated.
   ```

However, in the provided **minimal reproduction**, the `<NuxtPage>` slot contains only a single root node:  

```vue
<template>
  <div>
    <NuxtPage
      :transition="{ name: 'fade', mode: 'out-in', appear: true }"
      #="{ Component }"
    >
      <component :is="Component" />
    </NuxtPage>
  </div>
</template>
```

If the `<NuxtPage>` slot is not used, the warning does not appear, and everything works as expected.  

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Mini-ghost**
### 🔗 Linked issue

- Resolve #27401
- Resolve #27777
- Resolve #28609
- Resolve #30806 

### **KeepAlive**  

When `<KeepAlive>` is enabled inside `<NuxtPage>`, it captures `<RouteProvider>`, which may cause `<KeepAlive>` to malfunction in certain situations. To address this, PR #24024 attempted to modify `providerVNode.type.name` so that `<NuxtPage>` can correctly cache the vnode.  

However, this approach still fails in some edge cases.  

```vue
<template>
  <NuxtLayout>
    <NuxtPage :keepalive="{ exclude: ['cpage', 'dpage'] }" />
  </NuxtLayout>
</template>
```  

This implementation creates a new `exclude` array each time the page is re-rendered, causing `<KeepAlive>`'s internal `watch` to repeatedly prune the cache.  

Additionally, since `providerVNode.type` is an object, all cache keys inside `<KeepAlive>` effectively point to the same `RouteProvider` object, which gets modified every time the page changes.  

When `<KeepAlive>` prunes its cache, it checks all cached vnodes and determines whether to remove them based on `vnode.type.name`. Due to this behavior, when switching to an excluded page, the new page's `name` is assigned to `providerVNode.type`, leading to **all cached pages being removed**.  

As a temporary solution, we can move the `exclude` array into `<script setup>` to prevent it from being recreated on each page change, thus avoiding excessive cache pruning inside `<KeepAlive>`.  

```vue
<script setup lang="ts">
const exclude = ['cpage', 'dpage']
</script>

<template>
  <NuxtLayout>
    <NuxtPage :keepalive="{ exclude }" />
  </NuxtLayout>
</template>
```  

To address this issue, this PR refactors `RouteProvider` into `defineRouteProvider` and follows a similar approach to PR #24024 by assigning each **Page Component’s `name`** to `RouteProvider` and caching it using an object.  

This ensures that each **Page Component** is associated with its own `RouteProvider` object, preventing errors caused by cache pruning inside `<KeepAlive>`. 

---

### **NuxtPage Slot**  

Previously, the implementation of the `<NuxtPage>` slot caused `<Transition>` to detect multiple child nodes when enabled.  

```vue
<template>
  <div>
    <NuxtPage
      :transition="{ name: 'fade', mode: 'out-in', appear: true }"
      #="{ Component }"
    >
      <component :is="Component" />
    </NuxtPage>
  </div>
</template>
```  

To resolve this, I referred to [Vue Router's solution](https://github.com/vuejs/router/commit/d18e500da2ed017be30871628a5cc59324bec15c) to ensure that only a **single child node** is passed whenever possible.  

If there's anything I might have overlooked, please let me know. I truly appreciate your feedback. Thank you!

### CODE REVIEW

File: packages/nuxt/src/pages/runtime/page.ts [hunk 1]
```diff
@@ -104,14 +107,16 @@ export default defineComponent({
 
           previousPageKey = key
 
+          const pageVnode = slots.default ? normalizeSlot(slots.default, routeProps) : routeProps.Component
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/page.ts:110]: is there a reason this isn't located within the render function?

File: packages/nuxt/src/pages/runtime/page.ts [hunk 2]
```diff
@@ -148,18 +152,30 @@ export default defineComponent({
...
+
+                const routerComponentType = routeProps.Component.type as any
+                const routerComponentName = routerComponentType.name || routerComponentType.__name
+
+                let PageRouteProvider = routerProviderLookup[routerComponentName]
+
+                if (!PageRouteProvider) {
+                  PageRouteProvider = defineRouteProvider(routerComponentName)
+                  routerProviderLookup[routerComponentName] = PageRouteProvider
+                }
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/page.ts:176]:
```suggestion
                const PageRouteProvider = routerProviderLookup[routerComponentName] ||= defineRouteProvider(routerComponentName)
```

File: packages/nuxt/src/pages/runtime/page.ts [hunk 3]
```diff
@@ -66,6 +66,9 @@ export default defineComponent({
       nuxtApp._isNuxtPageUsed = true
     }
     let pageLoadingEndHookAlreadyCalled = false
+
+    const routerProviderLookup: Record<string, ReturnType<typeof defineRouteProvider> | undefined> = {}
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/page.ts:70]: it might be worth investigating whether a WeakMap would also resolve the issues linked above

(it might also be that the overhead for multiple RouteProviders is small enough not to matter, but it's worth verifying that pages/routes can still be garbage collected)

**Review by danielroe — APPROVED** [review]

File: packages/nuxt/src/pages/runtime/page.ts (hunk 3 above)
Comment (Mini-ghost) [reply packages/nuxt/src/pages/runtime/page.ts]: @danielroe I've updated it to a version using `WeakMap`. If `routeProps.Component.type` can be garbage collected, then this approach should be more memory-efficient compared to using an object.
