### PR TITLE
fix(nuxt): warn when scanning layout/middleware without name

### LINKED ISSUE #24988: invalid code is generated if there is a layout named "index"
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vjwzyc-btki5e

1. initialize nuxt3 project
2. add layout named "index"
3. modify app.vue to use `<NuxtLayout>` component

### Describe the bug

if a project have layout file named `index.vue`, following error occurs on running dev/build (probably because  'index' is omitted in an unintended way):

### dev mode
`[vite-node] [PARSE_ERROR] virtual:nuxt:./.nuxt/layouts.mjs` on browser

### on build
```
 ERROR  Unexpected token :. Expected identifier, string literal, numeric literal or [ for the computed key (Note that you need plugins to import files that are not JavaScript)         23:56:39
file: virtual:nuxt:/home/projects/github-vjwzyc-btki5e/.nuxt/layouts.mjs:2:2
1: export default {
2:   : () => import("/home/projects/github-vjwzyc-btki5e/layouts/index.vue").then(m => m.default || m)
     ^
3: }


[23:56:39]  ERROR  Nuxt Build Error: Unexpected token :. Expected identifier, string literal, numeric literal or [ for the computed key (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/rollup/dist/es/shared/parseAst.js:468:30)
  at nodeConverters (node_modules/rollup/dist/es/shared/parseAst.js:2215:9)
  at convertNode (node_modules/rollup/dist/es/shared/parseAst.js:1100:12)
  at convertProgram (node_modules/rollup/dist/es/shared/parseAst.js:1091:48)
  at Module.parseAstAsync (node_modules/rollup/dist/es/shared/parseAst.js:2281:20)
  at async Module.tryParseAsync (node_modules/rollup/dist/es/shared/node-entry.js:13539:21)
  at async Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:13120:35)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:17785:13)
```

### Additional context

There were no problem at v3.7.3

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/24988

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a warning a layout that does not resolve to a name is detected, like `~/layouts/index.vue`

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/app.ts [hunk 1]
```diff
@@ -117,6 +117,11 @@ export async function resolveApp (nuxt: Nuxt, app: NuxtApp) {
     const layoutFiles = await resolveFiles(config.srcDir, `${layoutDir}/**/*{${nuxt.options.extensions.join(',')}}`)
     for (const file of layoutFiles) {
       const name = getNameFromPath(file, resolve(config.srcDir, layoutDir))
+      if (!name) {
```
Comment (manniL) [inline packages/nuxt/src/core/app.ts:120]: Should we do the same for `middleware` ([here](https://github.com/nuxt/nuxt/blob/4dd87f6e281bacacafa9566a21388d5a7a53f911/packages/nuxt/src/core/app.ts#L130-L131))?

**Review by TheAlexLichter — APPROVED** [review]

File: packages/nuxt/src/core/app.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/app.ts:120]: good catch 👌

Comment (danielroe) [reply packages/nuxt/src/core/app.ts:120]: (Note for anyone else looking that plugins + middleware are not resolved in a nested fashion.)
