### PR TITLE
fix(nuxt): watch server/ for builder:watch hook

### LINKED ISSUE #33827: `builder:watch` hook is not triggered for changes in server/
### Environment

Node.js version       v20.19.5                              │
│ │  nuxt/cli version      3.31.1                                │
│ │  Package manager       bun 1.3.4                             │
│ │  Nuxt version          4.2.1                                 │
│ │  Nitro version         2.12.9                                │
│ │  Builder               vite 7.2.6 

### Reproduction

https://stackblitz.com/edit/github-9gs5ku35?file=server%2Froutes%2Ftest.ts

1. Run nuxt dev.
2. Create or modify a file in server/ or server/tests/test.ts.

### Describe the bug

When developing a module that scans the `server/` directory and generates virtual files via `addServerTemplate`, there is no reliable way to trigger a template regeneration when those server files change.

The `builder:watch` hook fires correctly for files in `app/`, `pages/`, or `components/`, but it completely ignores the `server/` directory.

Even if I explicitly add the path to the watch list:
```typescript
nuxt.options.watch.push(resolve(nuxt.options.srcDir, 'server/tests'))
```
The `builder:watch` hook still does not trigger.

**The result:**
1. I modify/create a server file.
2. Nitro detects the change and restarts the server (if configured via `nitro.devServer.watch`).
3. However, Nuxt **does not** trigger `builder:watch` to re-run an `addServerTemplate.getContents`/`updateTemplates` for the virtual templates.
4. Nitro restarts, reads the **old** virtual file from `.nuxt/`, and the server runs with stale data.

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by onmax**
Closes #33827

## Summary

`builder:watch` hook not triggered for server/ changes. Regression from #33098 refactor.

## Context

- PR #33098 refactored to use `dirs.app` instead of `srcDir`
- In v4, server/ is outside app/, so it stopped being watched
- Fix: add `dirs.server` to watched paths

## StackBlitz

| | Link | Expected |
|---|---|---|
| Bug | [nuxt-33827](https://stackblitz.com/github/onmax/repros/tree/repro/nuxt-33827/nuxt-33827?startScript=dev) | No log on server/ change |
| Fix | [nuxt-33827-fix](https://stackblitz.com/github/onmax/repros/tree/repro/nuxt-33827/nuxt-33827-fix?startScript=dev) | Log appears |

### CODE REVIEW

**Comment by onmax** [comment]
@coderabbitai I considered implementing the deduplication, but it adds complexity that may cause issues:

1. **In v4** (the primary use case): `app/` and `server/` are siblings at root level, so no nesting/duplication occurs
2. **In v3**: `server/` is inside `srcDir`, but the `startsWith` check would incorrectly skip legitimate cases in test environments where both paths are at root level
3. **Duplicate events are harmless**: Module developers typically debounce their `builder:watch` handlers anyway

The simpler implementation works for the intended use case (v4). If v3 edge cases cause problems, we can address them in a follow-up.

**Comment by onmax** [comment]
@danielroe Added a second commit (e9c79e81) with deduplication to avoid double-watching when `serverDir` is configured inside `app/`.

**Commits:**
1. `adb6221` - Core fix: watch server/ for builder:watch
2. `e9c79e8` - Deduplication: skip server if inside app (uses `relative()` check)

**Your call:** If you prefer the simpler version without deduplication, you can reset `adb6221` before merge. The first commit alone fixes the issue for standard v4 layouts.

The deduplication prevents duplicate events when someone sets `serverDir: 'app/server'` or similar nested configs.

**Comment by onmax** [comment]
@danielroe, there is a small edge case with the `includes()` check, it can match when paths share prefixes but aren't nested:

```
app = /workspace/app/
server = /workspace/app-admin/server/
```

`/workspace/app-admin/server/`.includes(`/workspace/app/`) -> true, but server isn't inside app.

Would `server.startstWith(app)` work better? Since paths have trailing slashes it should handle the nesting check correctly.

File: packages/nuxt/src/core/builder.ts [hunk 1]
```diff
@@ -102,7 +102,17 @@ function createWatcher () {
   const nuxt = useNuxt()
   const isIgnored = createIsIgnored(nuxt)
 
-  const watcher = chokidarWatch(getLayerDirectories(nuxt).map(dirs => dirs.app), {
+  const layerDirs = getLayerDirectories(nuxt)
+  const paths: string[] = []
+  for (const layer of layerDirs) {
+    paths.push(layer.app)
+    // Only add server if it's not inside app (avoid double-watching)
+    if (!layer.server.includes(layer.app.replace(/\/?$/, '/'))) {
```
Comment (danielroe) [inline packages/nuxt/src/core/builder.ts]:
```suggestion
    if (!layer.server.startsWith(layer.app.replace(/\/?$/, '/'))) {
```

File: packages/nuxt/src/core/builder.ts [hunk 2]
```diff
@@ -248,9 +258,13 @@ async function loadBuilder (nuxt: Nuxt, builder: string): Promise<NuxtBuilder> {
...
   const pathsToWatch = new Set<string>()
   for (const dirs of getLayerDirectories(nuxt)) {
-    if (!dirs.app || isIgnored(dirs.app)) { continue }
-
-    pathsToWatch.add(dirs.app)
+    if (!isIgnored(dirs.app)) {
+      pathsToWatch.add(dirs.app)
+    }
+    // Only add server if it's not inside app (avoid double-watching)
+    if (!isIgnored(dirs.server) && !dirs.server.includes(dirs.app.replace(/\/?$/, '/'))) {
```
Comment (danielroe) [inline packages/nuxt/src/core/builder.ts]:
```suggestion
    if (!isIgnored(dirs.server) && !dirs.server.startsWith(dirs.app.replace(/\/?$/, '/'))) {
```

**Comment by danielroe** [comment]
oops, that's quite right

**Review by danielroe — APPROVED** [review]
