### PR TITLE
fix(cjs): fix HMR issue with mongoose

### LINKED ISSUE #7917: App crashes on ServerMiddleware hot reload if Mongoose models are used, gives an error like "ServerMiddleware Error: Cannot overwrite User model once compiled"
### Versions

- nuxt: v2.14.1
- node: v12.18.3

### Reproduction
Use [this project](https://github.com/nuxt/nuxt.js/files/5074173/reproduction.zip) to reproduce, you may need to add a working MongoDB database credentials in .env file.

### Steps to reproduce
npm install
npm run dev
(No error at this point yet)
Make a change in login.js file
Save

### What is Expected?
Normal hot reload of servermiddleware as always (like when Mongoose is not used).

### What is actually happening?
App crashes with this error:

`ERROR ServerMiddleware Error: Cannot overwrite User model once compiled.`

### PR DESCRIPTION
**Pull request by farnabaz**
## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Introduce `isHMRCompatible` function to detect clear incompatible modules cache.  
As we know `mongoose` is incompatible and clearing `mongoose/index.js` and `mongoose/lib/index.js` makes it work.

close #7917

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/utils/src/cjs.js [hunk 1]
```diff
@@ -1,11 +1,15 @@
 import { join } from 'path'
 
+export function isHMRCompatible (id) {
+  return !/[/\\]mongoose[/\\/](lib[/\\/])?index.js/.test(id)
```
Comment (pi0) [inline packages/utils/src/cjs.js:4]: Why not marking entire mongoose dep as incompatible? A regex matching `node_modules/mongoose` as a part of id

Comment (farnabaz) [reply packages/utils/src/cjs.js:4]: mongoose has lots of files and it does not bundle them. clearing entire deps causes Maximum call stack size exceeded. (Honestly, I don't understand why)

Comment (pi0) [reply packages/utils/src/cjs.js:4]: Do you have a repo to quickly check? Maybe it is a nuxt HMR bug

Comment (farnabaz) [reply packages/utils/src/cjs.js:4]: I'll have one, let me push it to github

Comment (farnabaz) [reply packages/utils/src/cjs.js:4]: @pi0 https://github.com/farnabaz/nuxt-mongoose

Comment (clarkdo) [reply packages/utils/src/cjs.js:4]: Can we create a nuxt module for mongoouse and clear cache via `watchers` or `modules:before` hook ?

Comment (pi0) [reply packages/utils/src/cjs.js:4]: @farnabaz Typescript recursion should be fixed by (#7966)

Comment (pi0) [reply packages/utils/src/cjs.js:4]: @clarkdo Seems nice idea. Also there is an alternative way i used once to use [unload](#7358) method. 

Since it is really minor case (serverMiddleware + HMR + mongoose) but not uncommon setup, it may worth excluding mongoose by default. Nuxt 3 will isolate functions anyway so we won't have such issues for HMR.

Comment (farnabaz) [reply packages/utils/src/cjs.js]: @pi0 I have updated the regex based on based on fix #7966

**Review by pi0 — APPROVED** [review]
