### PR TITLE
fix(nuxt): init `$fetch` at entry start

### LINKED ISSUE #23848: $fetch is not defined
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devServer, telemetry, imports, srcDir, app, runtimeConfig, css, vite, modules, vant, hooks, nitro, build
- Runtime Modules:  @qzd-h5-ui/nuxt@1.0.3, @vueuse/nuxt@10.5.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, nuxt-windicss@2.6.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zr9tkf-upvvdt?file=utils%2Ffetch.ts

### Describe the bug

The browser throws an error "$fetch is not defined". 

I need to call an API when initializing on the client side. I wrapped $fetch and exported a fetch function, calling the API request method in plugins/1.init.client.ts.

### Additional context

image

### Logs

```shell-script
fetch.ts:1 Uncaught ReferenceError: $fetch is not defined
    at fetch.ts:1:14
```

### PR DESCRIPTION
**Pull request by antfu**
fix #23848

### CODE REVIEW

File: packages/nuxt/src/core/templates.ts [hunk 1]
```diff
@@ -334,6 +334,21 @@ export const publicPathTemplate: NuxtTemplate = {
...
+  getContents () {
+    return [
+      "import { $fetch } from 'ofetch'",
+      "import { baseURL } from '#build/paths.mjs'",
+      'if (!globalThis.$fetch) {',
+      '  globalThis.$fetch = $fetch.create({',
+      '    baseURL: baseURL()',
+      '  })',
+      '}'
+    ].filter(Boolean).join('\n')
```
Comment (DamianGlowala) [inline packages/nuxt/src/core/templates.ts:348]: Filtering plain strings might be redundant here
```suggestion
    ].join('\n')
```

File: packages/nuxt/src/app/entry.ts [hunk 2]
```diff
@@ -1,11 +1,9 @@
 // We set __webpack_public_path via this import with webpack builder
 import { createApp, createSSRApp, nextTick } from 'vue'
-import { $fetch } from 'ofetch'
-import type { $Fetch, NitroFetchRequest } from 'nitropack'
 
-// This file must be imported first for webpack as we set __webpack_public_path__ there
-// @ts-expect-error virtual file
-import { baseURL } from '#build/paths.mjs'
+// These files must be imported first for webpack as we set __webpack_public_path__ there
```
Comment (danielroe) [inline packages/nuxt/src/app/entry.ts:4]:
```suggestion
// These files must be imported first as they have side effects
```

File: packages/nuxt/src/core/templates.ts [hunk 3]
```diff
@@ -334,6 +334,21 @@ export const publicPathTemplate: NuxtTemplate = {
   }
 }
 
+export const dollarFetchTemplate: NuxtTemplate = {
+  filename: 'fetch.mjs',
+  getContents () {
+    return [
+      "import { $fetch } from 'ofetch'",
+      "import { baseURL } from '#build/paths.mjs'",
```
Comment (DamianGlowala) [inline packages/nuxt/src/core/templates.ts:342]: Would it make sense/be possible to move these inside the if statement and import dynamically?

**Review by danielroe — APPROVED** [review]
