### PR TITLE
fix(nuxt): overwrite island payload instead of assigning

### LINKED ISSUE #25289: Failed to locate Teleport target when using Server Components with nuxt-client
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.8.1`
- Nuxt Version:     `3.9.3`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `bun@1.0.22`
- Builder:          `-`
- User Config:      `app`, `runtimeConfig`, `modules`, `devtools`, `css`, `experimental`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.10.4`, `@nuxtjs/i18n@8.0.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-m9jf8b?file=components%2FServerComponent.server.vue

### Describe the bug

Since Nuxt version v3.9.2 this error occurs. It occurs when using nuxt-client conditionally. It probably has to do with the refactor. Try changing `"nuxt": "^3.9.3",` to `"nuxt": "3.9.1",` in the reproduction, and it will work.

image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #25289 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Hi :wave: this PR fix an issue when having a dynamic nuxt-client. The old data about client components were not removed due to `Object.assign` so we're now replacing completly the object

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: playground/app.vue [hunk 1]
```diff
@@ -10,4 +10,4 @@
 
 <style scoped>
 
-</style>
+</style>
```
Comment (danielroe) [inline playground/app.vue:13]:
```suggestion
</style>

```

File: packages/nuxt/src/app/components/nuxt-island.ts [hunk 2]
```diff
@@ -104,12 +104,18 @@ export default defineComponent({
       }
     }
 
-    const payloadSlots: NonNullable<NuxtIslandResponse['slots']> = {}
-    const payloadComponents: NonNullable<NuxtIslandResponse['components']> = {}
+    const payloads: {
+     slots: NonNullable<NuxtIslandResponse['slots']>
+     components:  NonNullable<NuxtIslandResponse['components']>
+    } = {
```
Comment (danielroe) [inline packages/nuxt/src/app/components/nuxt-island.ts:110]: we could probably extract this into a type alias above, or simplify to:

```suggestion
    const payloads: Required<Pick<NuxtIslandResponse, 'slots' | 'components'>> = {
```

Comment (huang-julien) [reply packages/nuxt/src/app/components/nuxt-island.ts:110]: oops indeed 😅

**Review by danielroe — APPROVED** [review]
