### PR TITLE
fix(schema): update `vue-loader` options type

### LINKED ISSUE #21332: Extend vue-loader option types
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     ^3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          webpack
- User Config:      builder, webpack
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6ue8jc?file=nuxt.config.ts

### Describe the bug

Nuxt has [a schema](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/config/webpack.ts#L154-L163) of `vue-loader` options that [partially matches](https://github.com/vuejs/vue-loader/blob/main/src/index.ts#L32-L62) `vue-loader`. 

For example, you can enable experimental features like Vue 3.3 `defineModel` in `webpack.loaders.vue`, but TypeScript won't recognize it as a valid property. However, if you ignore the error squiggles, it does work.
image

### Additional context

Mentioned in https://github.com/nuxt/nuxt/pull/21303#issuecomment-1574295022

### Logs

```shell-script
'{ defineModel: true; }' is not assignable to type '{ productionMode?: boolean | undefined; transformAssetUrls?: { video?: string | undefined; source?: string | undefined; object?: string | undefined; embed?: string | undefined; } | undefined; compilerOptions?: { ...; } | undefined; }'.
  Object literal may only specify known properties, and 'defineModel' does not exist in type '{ productionMode?: boolean | undefined; transformAssetUrls?: { video?: string | undefined; source?: string | undefined; object?: string | undefined; embed?: string | undefined; } | undefined; compilerOptions?: { ...; } | undefined; }'.(2322)
```

### PR DESCRIPTION
**Pull request by Lehoczky**
### 🔗 Linked issue

#21332

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The [schema for the vue-loader options](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/config/webpack.ts#L154-L163) did not extend the [VueLoaderOptions ](https://github.com/vuejs/vue-loader/blob/main/src/index.ts#L32-L62) interface and therefore the generated type, which the `defineNuxtConfig` function used was incorrect. 

There are probably issues with other properties of the [webpack.loaders](https://github.com/nuxt/nuxt/blob/main/packages/schema/src/config/webpack.ts#LL136C7-L136C7) object as well. They most likely should extend the option interface of their webpack plugin too. I can try to address this in another PR if you want, Daniel.

Before:
image

After:
image

Resolves #21332

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/webpack.ts [hunk 1]
```diff
@@ -151,8 +151,12 @@ export default defineUntypedSchema({
       fontUrl: { esModule: false, limit: 1000 },
       imgUrl: { esModule: false, limit: 1000 },
       pugPlain: {},
+
+      /**
+       * See [vue-loader](https://github.com/vuejs/vue-loader) for available options.
+       * @type {Partial<typeof import('vue-loader')['VueLoaderOptions']>}
+       */
       vue: {
-        productionMode: { $resolve: async (val, get) => val ?? !(await get('dev')) },
```
Comment (Lehoczky) [inline packages/schema/src/config/webpack.ts:155]: This seemed like an [old option](https://github.com/vuejs/vue-loader/pull/1208) that is no longer in the `vue-loader` plugin's codebase.

**Review by danielroe — APPROVED** [review]
