### PR TITLE
fix(vite): optimise layer dependencies with vite

### LINKED ISSUE #19426: Can't use dependencies in nuxt layers
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.19.0`
- Nuxt Version:     `^3.2.3`
- Nitro Version:    `-`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `ssr`, `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[dayjs-in-nuxt-layer-reporoduction.zip](https://github.com/nuxt/nuxt/files/10882990/dayjs-in-nuxt-layer-reporoduction.zip)
In `./nuxt-project`:
```bash
yarn && yarn dev
```
image

### Describe the bug

Can't use dependencies in package layer. So far I've noticed that the problem occurs with packages like: `axios`, `humps`, `qs`, `dayjs`, but I suspect there are many more.

### Additional context

Workaround (in `nuxt.config.ts`):
```ts
export default defineNuxtConfig({
	// ...
	extends: [
		'<layer-name>'
	],
	alias: {
		axios: 'axios',
		humps: 'humps',
		qs: 'qs',
		dayjs: 'dayjs',
	},
});
```

### Logs

```shell-script
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/dayjs/dayjs.min.js?v=17986f0a' does not provide an export named 'default' (at useDayjs.ts?v=17986f0a:1:8)
```

### LINKED ISSUE #21714: Ambiguous Indirect Export error when using elastic-builder in nuxt layer
### Environment

- Operating System: Linux
- Node Version:     v16.14.2                                                                                                                             12:48:46
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.5
- Builder:          vite
- User Config:      extends, vite
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/thibaultrey/nuxt-extends-import-bug

### Describe the bug

If you import [elastic-builder](https://www.npmjs.com/package/elastic-builder) package in a layer extended as a NPM package, you get the following error when load the page :
`
Uncaught SyntaxError: ambiguous indirect export: default
`

This error doesn't appear when you using the same layer locally via a relative path.

The error seems similar to [#19267](https://github.com/nuxt/nuxt/issues/19267) but added elastic-builder package in the build.transpile settings doesn't works.

In the relative path extend way vite seems to _optimize_ the elastic-builder; this action never happens when you extends throught a NPM Package.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/19426
resolves https://github.com/nuxt/nuxt/issues/21714

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR triggers a resolve call when importing dependencies into layers, to trigger vite to optimise any dependencies that are imported within a layer, just as if they were imported by a user...

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/vite/src/vite.ts [hunk 1]
```diff
@@ -138,13 +138,23 @@ export const bundle: NuxtBuilder['bundle'] = async (nuxt) => {
     ctx.config.build!.watch = undefined
   }
 
-  // Trigger vite to optimize any dependencies that are imported within a layer, just as if they were imported by a user
-  if (nuxt.options.dev) {
```
Comment (manniL) [inline packages/vite/src/vite.ts]: Not only in dev anymore?

Comment (danielroe) [reply packages/vite/src/vite.ts]: ah. yes. probably best to keep in dev for now until tested better. we might later expand out of dev to try and resolve dependencies from final layer (would resolve https://github.com/nuxt/nuxt/issues/25747, for example)...

**Comment by darvids0n** [comment]
Hi @danielroe, I believe this change is the direct cause of some serious build performance issues e.g. #26211, #27106

Experiment for any users who have a slow dev server startup: Comment out this code chunk from
`@nuxt/vite-builder/dist/shared/vite-builder.CHUNK_ID.mjs`

```ts
if (nuxt.options.dev) {
    const layerDirs = [];
    const delimitedRootDir = nuxt.options.rootDir + "/";
    for (const layer of nuxt.options._layers) {
      if (layer.config.srcDir !== nuxt.options.srcDir && !layer.config.srcDir.startsWith(delimitedRootDir)) {
        layerDirs.push(layer.config.srcDir + "/");
      }
    }
    if (layerDirs.length > 0) {
      ctx.config.plugins.push({
        name: "nuxt:optimize-layer-deps",
        enforce: "pre",
        async resolveId(source, _importer) {
          if (!_importer) {
            return;
          }
          const importer = normalize(_importer);
          if (layerDirs.some((dir) => importer.startsWith(dir))) {
            await this.resolve(source, join(nuxt.options.srcDir, "index.html"), { skipSelf: true }).catch(() => null);
          }
        }
      });
    }
  }
```

Result for me: Build performance significantly improves from ~40-80s, down to ~2-3s

Something about these resolves is very inefficient it seems.

**Comment by danielroe** [comment]
@darvids0n Thanks for digging into this. There is definitely space to optimise this. 

Do you have a reproduction I can use to test?

**Comment by darvids0n** [comment]
> @darvids0n Thanks for digging into this. There is definitely space to optimise this.
> 
> Do you have a reproduction I can use to test?

I just made one on Stackblitz for you. Link here: https://stackblitz.com/edit/nuxt-starter-ujzgtq

All I've done is take the nuxt starter, and pull in 3 layers which provide some ready-to-go components - `oxecore`, `nuxt-lego` and `supauth`. I added them to `extends`. The `npm run dev` performance is roughly 13 seconds in before Nitro completed build, and 20 seconds for Nuxt ssr+client.

I added the exact instructions for commenting out the layer deps chunk in README.
