### PR TITLE
fix(vue-app): check for Page.options before looking within

### LINKED ISSUE #8234: scrollToTop throws `Page.options is undefined`
### Versions

- nuxt: v2.14.6
- node: v12.18.3

### Reproduction

Not sure how to reproduce.

### Issue

This line: `Pages.some(Page => Page.options.scrollToTop)` in router.scrollBehaviour sometimes throws an error: `Page.options is undefined`. This prevents the page from loading properly. Not sure how this can happen. Consol error is shown both in dev mode and prod mode, but only breaks the page in dev mode.

### PR DESCRIPTION
**Pull request by danielroe**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
Difficult to reproduce the issue but the fix is lightweight.

closes #8234

## Checklist:
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/router.scrollBehavior.js [hunk 1]
```diff
@@ -31,9 +31,9 @@ export default function (to, from, savedPosition) {
   // Scroll to the top of the page if...
   if (
       // One of the children set `scrollToTop`
-      (Pages.some(Page => Page.options.scrollToTop) ||
+      (Pages.some(Page => Page.options && Page.options.scrollToTop) ||
```
Comment (Atinux) [inline packages/vue-app/template/router.scrollBehavior.js:34]: Could we use this?
```suggestion
      (Pages.some(Page => Page.options?.scrollToTop) ||
```

Comment (clarkdo) [reply packages/vue-app/template/router.scrollBehavior.js:34]: This may add extra polyfill if user is not using optional chaining.

**Review by clarkdo — APPROVED** [review]

File: packages/vue-app/template/router.scrollBehavior.js (hunk 1 above)
Comment (clarkdo) [reply packages/vue-app/template/router.scrollBehavior.js:34]: Let's merge this and I may make some refactoring to this file,
