### PR TITLE
fix(nuxt): use fresh route when `<NuxtLayout>` first renders

### LINKED ISSUE #24642: useRoute not correctly populated with async layout
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-bvoawn?file=pages%2Findex.vue,app.vue,layouts%2FTestLayout.vue,pages%2F[profileId].vue

I left a comment in "TestLayout.vue" that you should uncomment to see a fix

### Describe the bug

Upon navigating to a layout that uses top-level await, `useRoute().params`  is not populated correctly on the client side. Upon hard refresh, it is populated correctly

### Additional context

I left a comment in "TestLayout.vue" that you should uncomment to see a fix

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue
resolve https://github.com/nuxt/nuxt/issues/24642

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

~~Hi :wave: this PR sync `nuxtApp._route` for `NuxtLayout`~~

**edited**:

this PR updated `useRoute()` within layouts to use the vue-router route if the layout is rendering for the first time in a page transition

I've marked two TODOs in the test - these aren't regressions from this PR but issues I spotted and which we could ultimately fix.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/pages/runtime/plugins/router.ts [hunk 1]
```diff
@@ -104,6 +104,9 @@ const plugin: Plugin<{ router: Router }> = defineNuxtPlugin({
       // so we need to update the route manually
       if (to.matched[0]?.components?.default === from.matched[0]?.components?.default) {
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/plugins/router.ts:105]: Should we instead use the isSameRoute utility you created in another PR?

File: packages/nuxt/src/pages/runtime/plugins/router.ts [hunk 2]
```diff
@@ -104,6 +104,9 @@ const plugin: Plugin<{ router: Router }> = defineNuxtPlugin({
...
         syncCurrentRoute()
+      } else {
+        // assign toValue to avoid reactivity
+        Object.assign(toValue(_route), router.currentRoute.value)
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/plugins/router.ts:109]: I'm not sure this is the correct fix (but do tell me what you're thinking as I could be wrong here). This is omitted initially as the suspense resolution _should_ update the route (and I think we always want it to be reactive).

Comment (huang-julien) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:109]: In that case, should we always sync the route ?

Comment (danielroe) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:109]: We should sync the route, but if we do it here when suspense is involved, it will be too early and update the view before the setup function of the new route has finished

Comment (huang-julien) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:109]: I think assigning this way shouldn't update the view since vue won't trigger reactivity. Is there another way of fixing it ?

File: packages/nuxt/src/app/components/nuxt-layout.ts [hunk 3]
```diff
@@ -51,10 +51,12 @@ export default defineComponent({
...
     // Need to ensure (if we are not a child of `<NuxtPage>`) that we use synchronous route (not deferred)
     const injectedRoute = inject(PageRouteSymbol)
-    const route = injectedRoute === useRoute() ? useVueRouterRoute() : injectedRoute
+    const shouldUseEagerRoute = !injectedRoute /* this should never be true */
+      || injectedRoute === useRoute() /* this is only true if we are not within `<NuxtPage>` */
+    const route = shouldUseEagerRoute ? useVueRouterRoute() as ReturnType<typeof useRoute> : injectedRoute
 
     const layout = computed(() => {
-      let layout = unref(props.name) ?? route.meta.layout as string ?? 'default'
+      let layout = unref(props.name) ?? route!.meta.layout as string ?? 'default'
```
Comment (huang-julien) [inline packages/nuxt/src/app/components/nuxt-layout.ts:59]:
```suggestion
      let layout = unref(props.name) ?? route?.meta.layout as string ?? 'default'
```

File: packages/nuxt/src/app/components/nuxt-layout.ts [hunk 4]
```diff
@@ -79,9 +81,14 @@ export default defineComponent({
       nuxtApp._isNuxtLayoutUsed = true
     }
 
+    let lastLayout: string | boolean | undefined
+
     return () => {
       const hasLayout = layout.value && layout.value in layouts
-      const transitionProps = route.meta.layoutTransition ?? defaultLayoutTransition
+      const transitionProps = route!.meta.layoutTransition ?? defaultLayoutTransition
```
Comment (huang-julien) [inline packages/nuxt/src/app/components/nuxt-layout.ts:88]:
```suggestion
      const transitionProps = route?.meta.layoutTransition ?? defaultLayoutTransition
```
