### PR TITLE
fix(utils): error when router.trailingSlash is false

### LINKED ISSUE #6501: router.trailingSlash: false "This page could not be found"
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://github.com/CurtisBelt/nuxtjs-template](https://github.com/CurtisBelt/nuxtjs-template)

### Steps to reproduce

```
yarn dev
```

or 

```
yarn build
yarn start
```

### Additional comments?

Removing `router.trailingSlash` or setting it to true prevents the error, but my preference is for no trailing slash.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9851">#c9851</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by y-temp4**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix https://github.com/nuxt/nuxt.js/issues/6501

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/utils/src/route.js [hunk 1]
```diff
@@ -177,6 +177,9 @@ export const createRoutes = function createRoutes ({
     if (trailingSlash !== undefined) {
       route.pathToRegexpOptions = { ...route.pathToRegexpOptions, strict: true }
       route.path = route.path.replace(/\/+$/, '') + (trailingSlash ? '/' : '')
+      if (route.path === '') {
```
Comment (vladyslavprosolupov) [inline packages/utils/src/route.js]: how about?
`route.path = route.path.replace(/\/+$/, '') + (trailingSlash ? '/' : '') || '/'`

Comment (y-temp4) [reply packages/utils/src/route.js]: looks good.
I'll adopt this way, thx!

**Review by TheAlexLichter — APPROVED** [review]
