### PR TITLE
fix(kit): correctly exclude local modules in `tsconfig.json`

### LINKED ISSUE #25116: Problem with TypeScript module imports from pages within a multi-module Nuxt.js application (maybe ts alias problem 🤷‍♂️)
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      css, app, ssr, runtimeConfig, modules, imports, vite, nitro
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxt/devtools@1.0.6, @nuxtjs/i18n@8.0.0-beta.13
- Build Modules:    -

### Reproduction

[codesandbox.io/p/devbox/eloquent-chatelet-gdvcy3](https://codesandbox.io/p/devbox/eloquent-chatelet-gdvcy3)

---

Unfortunately, due to confidential elements of the project, providing a public repository is not possible.
However, I'll guide you on creating a simplified reproduction locally to demonstrate the import issue:

### Project Structure:
Group 3615
Confirm that your project structure includes a module named "processus" with TypeScript files (e.g., store, components, etc.).

### Module Setup:
Group 3616
On each module's root, the set of pages/components used for that module is defined using the example above.

### TS Config:
image
After reviewing several issues more or less related to this topic, the following configuration was added to the tsconfig.json file.

### Page index.vue

1. Navigate to the modules/processus/index.vue file.
2. Attempt to import the module with the statement import processus from '~/modules/processus/store/processus'; or import from "#imports" resource.
3. Observe the aforementioned errors in the IDE.

### Describe the bug

I am currently facing issues with importing TypeScript modules from specific pages within a local module in an extended Nuxt.js application composed of multiple modules.

When attempting to import specific modules from pages located in the "processus" module, I receive the following errors in my IntelliJ IDE and also in VSCode:

Vue: Cannot find module ~/modules/processus/store/processus or its corresponding type declarations.
Vue: Cannot find module #imports or its corresponding type declarations.

Capture d'écran 2024-01-09 115917
Group 3617
image

### Additional context

Group 3618

If I try to import with the same path and alias from a Vue file in the "components" folder of my process module, everything works perfectly.

I also want to add that the code runs completely without any issues, and the builds are functional as well. It's just that my IDE consistently highlights these imports in red.

### Logs

_No response_

### LINKED ISSUE #25134: Generated tsconfig.json for modules is messing with VS Code's TypeScript support
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.18.1
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-6h2ghs?file=.nuxt%2Ftsconfig.json

### Describe the bug

When using modules in your nuxt project the generated `tsconfig.json` in `.nuxt` seems to be conflicting with VS Code's TypeScript server.

In the `include` section everything in the module's `runtime` folder is allowed but then in the `exclude` section the whole module gets removed again.

```
"include": [
    "../modules/1.first/runtime",
    ".."
  ],
  "exclude": [
    "../modules/1.first",
    "../modules/1.first/runtime/server",
  ]
```

As you can see when opening a file from within the `runtime` folder, VS Code shows on the bottom right that no tsconfig file is associated with that file and the auto imports are not working as intended:

image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by DamianGlowala**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/25134
resolves https://github.com/nuxt/nuxt/issues/25116

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

It addresses two things:

1. In `installModule` util, instead of adding e.g. `modules/my-module` as a modules directory to the `nuxt.options.modulesDir`, now `modules` gets added instead.
2. When constructing paths to be excluded in the `tsconfig.json`, now only the `node-modules`-related directories in `nuxt.options.modulesDir` are taken into account.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/kit/src/template.ts [hunk 1]
```diff
@@ -154,7 +154,9 @@ export async function writeTypes (nuxt: Nuxt) {
       ...modulePaths.map(m => join(relativeWithDot(nuxt.options.buildDir, m), 'runtime'))
     ],
     exclude: [
-      ...nuxt.options.modulesDir.map(m => relativeWithDot(nuxt.options.buildDir, m)),
+      ...nuxt.options.modulesDir
+        .filter((modulesDir) => modulesDir.endsWith("node_modules"))
```
Comment (danielroe) [inline packages/kit/src/template.ts:158]:
```suggestion
        .filter(modulesDir => modulesDir.endsWith('node_modules'))
```

Comment (danielroe) [inline packages/kit/src/template.ts:158]:
```suggestion
      ...nuxt.options.modulesDir
        .filter(modulesDir => modulesDir.endsWith('node_modules'))
```

File: packages/kit/src/module/install.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export async function installModule (moduleToInstall: string | NuxtModule, inlin
     nuxt.options.build.transpile.push(normalizeModuleTranspilePath(moduleToInstall))
     const directory = getDirectory(moduleToInstall)
     if (directory !== moduleToInstall && !localLayerModuleDirs.has(directory)) {
-      nuxt.options.modulesDir.push(directory)
+      nuxt.options.modulesDir.push(resolve(directory, '..'))
```
Comment (danielroe) [inline packages/kit/src/module/install.ts:41]: 'modulesDir' in this context is a place where we resolve node_modules from. The parent directory may not work, particularly in a hoisted context. I think this should likely stay unchanged here but perhaps we add a bit of additional logic in `template.ts`?

**Review by danielroe — APPROVED** [review]
