### PR TITLE
fix(nuxt): convert kebab to pascal name when loading server component

### LINKED ISSUE #27920: Server component cannot be used with kebab-case
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, ssr, experimental
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dwbpsr

### Describe the bug

1. Add a server component `MyComponent.server.vue` in `components`
2. Use it with kebab-case `<my-component>` in app
3.  `WARN  [Vue warn]: Component <Anonymous> is missing template or render function.`

### Additional context

When using server component from a nuxt module, it will log "Island component not found" in browser console.

When using server component from local `components` dir, it will log "hydration mismatch" in browser console.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #27920 
### 📚 Description
Hey :wave: this PR convert kebab to pascal case swhen creating the `createServerComponent()` variable

### CODE REVIEW

File: packages/nuxt/src/components/loader.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const loaderPlugin = createUnplugin((options: LoaderOptions) => {
             !components.some(c => c.pascalName === component.pascalName && c.mode === 'client')
           if (isServerOnly) {
             imports.add(genImport(serverComponentRuntime, [{ name: 'createServerComponent' }]))
-            imports.add(`const ${identifier} = createServerComponent(${JSON.stringify(name)})`)
+            imports.add(`const ${identifier} = createServerComponent(${JSON.stringify(pascalCase(name))})`)
```
Comment (danielroe) [inline packages/nuxt/src/components/loader.ts:61]: Does this also work?

```suggestion
            imports.add(`const ${identifier} = createServerComponent(${JSON.stringify(component.pascalName)})`)
```

Comment (huang-julien) [reply packages/nuxt/src/components/loader.ts:61]: yes !

**Review by danielroe — APPROVED** [review]
