### PR TITLE
fix(nuxt): provide types for modules as array

### LINKED ISSUE #18415: Modules as arrays don't take advantage of ModuleOptions
### Describe the feature

Nuxt configuration allows modules to either be passed as a `NuxtModule` function, a string (usual case), and an array (tuple technically) with the first element as either of the two mentioned and the second as options - quite similar to many other configuration systems like ESLint, etc. However, the schema would only give the type definition if the module option is added as a property instead.

```ts
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/tailwindcss', // OK
    ['@nuxtjs/web-vitals', { } ], // no types 🙁
  ],
  tailwindcss: { exposeConfig: true },
});
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by ineshbose**
### 🔗 Linked issue

resolves #18415 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [X] 👌 Enhancement (improving an existing functionality like performance)
- [X] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Extends `modules` definition in `.nuxt/types/schema.d.ts`.

### 📝 Checklist

- [X] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/templates.ts [hunk 1]
```diff
@@ -121,14 +121,20 @@ export const schemaTemplate: NuxtTemplate<TemplateContext> = {
...
-        `    [${genString(meta.configKey)}]?: typeof ${genDynamicImport(meta.importName.startsWith('.') ? './' + join(relativeRoot, meta.importName) : meta.importName, { wrapper: false })}.default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>`
-      ),
+      ...moduleInfo.filter(Boolean).map((meta) => {
+        const configKey = genString(meta.configKey)
+        const importName = meta.importName.startsWith('.') ? './' + join(relativeRoot, meta.importName) : meta.importName
+        moduleMap[importName] = configKey
+
+        return `    [${configKey}]?: typeof ${genDynamicImport(importName, { wrapper: false })}.default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>`
+      }),
+      Object.keys(moduleMap).length > 0 ? `    modules: (NuxtModule | string | ${Object.keys(moduleMap).join(' | ')} | [NuxtModule | string, Record<string, any>] | ${Object.entries(moduleMap).map(([importName, configKey]) => `[${genString(importName)}, NuxtConfig[${genString(configKey)}]]`).join(' | ')})[]` : '',
```
Comment (danielroe) [inline packages/nuxt/src/core/templates.ts]: could we move the shared code (getting import name and config key) into the section above (L124)? that way we can consume it a bit more cleanly in both places below

Comment (danielroe) [reply packages/nuxt/src/core/templates.ts]: You will likely need to stringify the keys as well, something like:

```js
Object.keys(moduleMap).map(r => JSON.stringify(r)).join(' | ')
```

**Review by danielroe — CHANGES_REQUESTED** [review]
Thank you! This is a nice improvement. Just a couple of suggestions, I think.

File: packages/nuxt/src/core/templates.ts (hunk 1 above)
Comment (ineshbose) [reply packages/nuxt/src/core/templates.ts]: I've made changes based on these suggestions.

> Actually, is there any reason we need these explicitly typed?
My answer to that would be 1) DX and 2) ensuring configurations match the desired module inputs to avoid errors.
Based on how developers intend to configure the `modules` property, all that Nuxt would do is provide IntelliSense for it - but I'm mostly making use of `NuxtConfig` interface itself!

In my opinion, it won't make a difference if someone configures to use absolute paths, because 1) they can continue passing options as a property than an array element or 2) if they are to use an array, at least options would be typed and it won't make difference between these two:

```ts
export default defineNuxtConfig({
  modules: [
   '/node_modules/.pnpm/@nuxtjs+color-mode@3.2.0/node_modules/@nuxtjs/color-mode/dist/module.mjs',
   // ['/node_modules/.pnpm/@nuxtjs+color-mode@3.2.0/node_modules/@nuxtjs/color-mode/dist/module.mjs', {}]
  ],
  colorMode: {},
})
```

The resulting schema would still include this as:

```ts
import { NuxtModule } from '@nuxt/schema'
declare module '@nuxt/schema' {
  interface NuxtConfig {
    ["colorMode"]?: typeof import("/node_modules/.pnpm/@nuxtjs+color-mode@3.2.0/node_modules/@nuxtjs/color-mode/dist/module.mjs").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>,
    // modules: (NuxtModule | string | "/node_modules/.pnpm/@nuxtjs+color-mode@3.2.0/node_modules/@nuxtjs/color-mode/dist/module.mjs" | [NuxtModule | string, Record<string, any>] | ["/node_modules/.pnpm/@nuxtjs+color-mode@3.2.0/node_modules/@nuxtjs/color-mode/dist/module.mjs", NuxtConfig['colorMode']])[]
  }
}
```

Comment (danielroe) [reply packages/nuxt/src/core/templates.ts]: Because `string` is a valid type of `modules` I don't think we'll get any benefit here by using a literal type, added to which you have to have added the string first, then saved the file, before you'll get auto-completion for the string you've just typed.

**Comment by danielroe** [comment]
Would you mind reopening this PR (or updating it) and giving me permission to push some changes? I think we can simplify this a bit further, and I've also spotted a pre-existing bug in the schema generation we can fix at the same time.

**Comment by ineshbose** [comment]
Sorry! Please let me know if you have permission to push on here.

File: packages/nuxt/src/core/templates.ts (hunk 1 above)
Comment (ineshbose) [reply packages/nuxt/src/core/templates.ts]: That is a very fair point, and there is the point to realise that the schema validation occurs after the initial load.
I went for literal types because configurations would have to correspond to the modules - like we can't have the tailwind module options for color-mode.

**Comment by danielroe** [comment]
nope, but never mind - I've opened a PR to this PR 😆 

https://github.com/inesh-forks/nuxt/pull/1

File: packages/nuxt/src/core/templates.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/templates.ts]: ah, but if we look at the below type:

```ts
modules: (
  NuxtModule |
  string |
  // here we do not need the literal type (and in fact it has no effect on type hinting because we also
  // allow string as a valid type)
  "@nuxtjs/color-mode" |
  [NuxtModule | string, Record<string, any>] |
  // here we _do_ need the literal type
  ["@nuxtjs/color-mode", NuxtConfig['colorMode']]
)[]
```

Comment (ineshbose) [reply packages/nuxt/src/core/templates.ts]: Yes, I agree with you - that one is redundant. 🙂

File: test/fixtures/basic/nuxt.config.ts [hunk 2]
```diff
@@ -55,7 +55,16 @@ export default defineNuxtConfig({
     }
   },
   modules: [
-    '~/modules/example',
+    [
+      '~/modules/example',
+      {
+        typeTest(val) {
```
Comment (danielroe) [inline test/fixtures/basic/nuxt.config.ts:61]:
```suggestion
        typeTest (val) {
```

File: packages/nuxt/src/core/templates.ts [hunk 3]
```diff
@@ -121,14 +121,17 @@ export const schemaTemplate: NuxtTemplate<TemplateContext> = {
     })).filter(m => m.configKey && m.name && !adHocModules.includes(m.name))
 
     const relativeRoot = relative(resolve(nuxt.options.buildDir, 'types'), nuxt.options.rootDir)
+    const getImportName = (name: string) => (name.startsWith('.') ? './' + join(relativeRoot, name) : name).replace(/\.\w+$/, '')
+    const modules = moduleInfo.map((meta) => [genString(meta.configKey), getImportName(meta.importName)])
```
Comment (danielroe) [inline packages/nuxt/src/core/templates.ts:125]:
```suggestion
    const modules = moduleInfo.map(meta => [genString(meta.configKey), getImportName(meta.importName)])
```

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Lovely work - thank you! ❤️
