### PR TITLE
fix(nuxt): avoid recursive ssr errors

### LINKED ISSUE #24393: Infinite loop when plugin/middleware throw error
### Environment

Nitro 2.8.0

### Reproduction

https://stackblitz.com/edit/github-syrpot?file=server%2Fapi%2Ftest.ts,plugins%2Ftest.server.ts

### Describe the bug

If we create a plugin using `useRequestFetch()`, the http headers from the browser are forwarded (`accept: 'text/html'`), and since [this commit](https://github.com/unjs/nitro/commit/0a5911e342a24d5099b6045605913d5d52d30d46) in Nitro, it won't look at it as JSON request.

What is weird is that when calling the API route and rendering the error page, it calls again the Nuxt plugin with the API route as path (I suspected to never do this).

### Additional context

Workaround is to explicit set the text/json header.

```ts
await useRequestFetch()('/api/test', {
  headers: {
    Accept: 'text/json',
  },
}).catch(() => {});
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

resolves #24393

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Nitro's default error handler is set to a custom Nuxt handler that unless the incoming request is from a json client, always prefers SSR rendering. If an error happens during SSR rendering of error page by making another fetch call, we will end up with an infinity loop.

This PR fixes issue by setting a custom header to the first error rendering phase and if we see the same header in a subsequent one, we simply fallback to the static HTML one that wouldn't cause recursion.

As a much much better improvement we could (and i believe we should) skip all plugins and nuxt middleware by default when rendering error page and allow opting-in using meta as current behavior can potentially plugins to misbehave in rendering errro pages but i guess is something of a bigger discussion as this would be a breaking change.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/runtime/nitro/error.ts [hunk 1]
```diff
@@ -45,14 +45,20 @@ export default <NitroErrorHandler> async function errorhandler (error: H3Error,
     return send(event, JSON.stringify(errorObject))
   }
 
+  // Access request headers
+  const reqHeaders = getRequestHeaders(event)
+
+  // Detect to avoid recusrion in SSR rendering of errors
+  const isRenderingError = event.path.startsWith('/__nuxt_error') || !!reqHeaders['x-nuxt-error']
```
Comment (danielroe) [inline packages/nuxt/src/core/runtime/nitro/error.ts:52]: Do you think there is a way we can set a property that can't be 'forged'? That is, disallow a user from manually adding this header to a request?

Comment (pi0) [reply packages/nuxt/src/core/runtime/nitro/error.ts:52]: I'm afraid and tried also not because the attached properties will be lost only the ones  that can be carried over HTTP are always safe to assume will be preserved in recursion.

We might use a random global number btw but it can make troubles for multi threading if source of recusrion is different.

Also i think it should be safe because 1) It is already possible by user agents to switch between json and HTML 2) Static fallback is almost the safest rendering path so adding header for benefit of exploiting an issue should not be reasonable

File: packages/nuxt/src/core/runtime/nitro/error.ts [hunk 2]
```diff
@@ -45,14 +45,20 @@ export default <NitroErrorHandler> async function errorhandler (error: H3Error,
     return send(event, JSON.stringify(errorObject))
   }
 
+  // Access request headers
+  const reqHeaders = getRequestHeaders(event)
+
+  // Detect to avoid recusrion in SSR rendering of errors
```
Comment (danielroe) [inline packages/nuxt/src/core/runtime/nitro/error.ts:51]:
```suggestion
  // Detect to avoid recursion in SSR rendering of errors
```

File: packages/nuxt/src/core/runtime/nitro/error.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/runtime/nitro/error.ts:52]: Okay. I wonder if it's worth making available (in future) an explicit way via unenv to pass data/payload to bypass this? I'd guess the issue will be caching but if we effectively opt it out of caching or specify a custom cache key(?)

**Review by danielroe — APPROVED** [review]

File: packages/nuxt/src/core/runtime/nitro/error.ts (hunk 1 above)
Comment (pi0) [reply packages/nuxt/src/core/runtime/nitro/error.ts:52]: It is possible as of today to also use `context/`__unenv__` init option but let's see in the future if we really need to do this and depend on unenv internals (i am mainly worried about future with multi-threading fetch that makes it harder to assume depending on unenv context)

File: test/fixtures/basic/plugins/error.server.ts [hunk 3]
```diff
@@ -0,0 +1,5 @@
+export default defineNuxtPlugin(async () => {
+  if (useRequestHeaders(['x-recurse'])['x-recurse']) {
```
Comment (pi0) [inline test/fixtures/basic/plugins/error.server.ts:2]: Small code style: I would use `x-test-` to make it more readable it is a test suite specific thing

```suggestion
  if (useRequestHeaders(['x-test-recurse-error'])['x-test-recurse-error']) {
```

File: test/basic.test.ts [hunk 4]
```diff
@@ -814,6 +814,17 @@ describe('errors', () => {
         "url": "/__nuxt_error",
       }
     `)
+
+    it('should not recursively throw an error when there is an error rendering the error page', async () => {
+      const res = await $fetch('/', {
+        headers: {
+          'x-recurse': 'true',
```
Comment (pi0) [inline test/basic.test.ts:821]:
```suggestion
          'x-test-recurse-error': 'true',
```

File: test/fixtures/basic/plugins/error.server.ts (hunk 3 above)
Comment (pi0) [reply test/fixtures/basic/plugins/error.server.ts:2]: Don't we also have `useRequestHeader` btw?

Comment (danielroe) [reply test/fixtures/basic/plugins/error.server.ts:2]: we do, yes.
