### PR TITLE
fix(nuxt): delete existing properties on app config template's HMR

### LINKED ISSUE #30916: appConfig doesn't remove unused entries
### Environment

(Stackblitz Sandbox)

Working directory: /home/projects/llqiwvwkzb.github
Nuxt project info:
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.15.4
- CLI Version:      3.21.1
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-appconfig-update?file=app.config.ts

### Describe the bug

When removing unused entries in appConfig, Nuxt only updates existing entries and ignores the entries to be deleted.

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by DamianGlowala**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/30916

### 📚 Description

Adds `replaceAppConfig` util, which allows for deep assign/delete of app config.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
I wonder if there is a way to avoid changing the public signature of updateAppConfig.

**Comment by DamianGlowala** [comment]
@danielroe fully agree; is it any better now?

File: packages/nuxt/src/app/index.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ export type { AddRouteMiddlewareOptions, AsyncData, AsyncDataOptions, AsyncDataR
 
 export { defineNuxtLink } from './components/index'
 export type { NuxtLinkOptions, NuxtLinkProps } from './components/index'
-export { _getAppConfig, updateAppConfig, useAppConfig } from './config'
+export { _getAppConfig, updateAppConfig, useAppConfig, replaceAppConfig } from './config'
```
Comment (danielroe) [inline packages/nuxt/src/app/index.ts:9]:
```suggestion
export { _getAppConfig, updateAppConfig, useAppConfig } from './config'
```

File: packages/nuxt/src/app/config.ts [hunk 2]
```diff
@@ -54,6 +54,13 @@ export function useAppConfig (): AppConfig {
   return nuxtApp._appConfig
 }
 
+export function replaceAppConfig (newConfig: AppConfig) {
```
Comment (danielroe) [inline packages/nuxt/src/app/config.ts:57]:
```suggestion
export function _replaceAppConfig (newConfig: AppConfig) {
```

File: packages/nuxt/src/core/templates.ts [hunk 3]
```diff
@@ -428,12 +428,12 @@ import { defuFn } from 'defu'
 const inlineConfig = ${JSON.stringify(nuxt.options.appConfig, null, 2)}
 
 /** client **/
-import { updateAppConfig } from '#app/config'
+import { replaceAppConfig } from '#app/config'
```
Comment (danielroe) [inline packages/nuxt/src/core/templates.ts:431]:
```suggestion
import { _replaceAppConfig } from '#app/config'
```

File: packages/nuxt/src/core/templates.ts [hunk 4]
```diff
@@ -428,12 +428,12 @@ import { defuFn } from 'defu'
...
 
 // Vite - webpack is handled directly in #app/config
 if (import.meta.dev && !import.meta.nitro && import.meta.hot) {
   import.meta.hot.accept((newModule) => {
-    updateAppConfig(newModule.default)
+    replaceAppConfig(newModule.default)
```
Comment (danielroe) [inline packages/nuxt/src/core/templates.ts:436]:
```suggestion
   _replaceAppConfig(newModule.default)
```

**Review by danielroe — COMMENTED** [review]
perfect!

File: packages/nuxt/src/core/templates.ts [hunk 5]
```diff
@@ -428,12 +428,12 @@ import { defuFn } from 'defu'
...
 
 /** client **/
-import { updateAppConfig } from '#app/config'
+import { _replaceAppConfig } from '#app/config'
 
 // Vite - webpack is handled directly in #app/config
 if (import.meta.dev && !import.meta.nitro && import.meta.hot) {
   import.meta.hot.accept((newModule) => {
-    updateAppConfig(newModule.default)
+   _replaceAppConfig(newModule.default)
```
Comment (danielroe) [inline packages/nuxt/src/core/templates.ts:436]:
```suggestion
    _replaceAppConfig(newModule.default)
```

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
I think it should ideally be gone from the array entirely

**Review by danielroe — APPROVED** [review]
let's follow up in a separate PR with the fix for `deepDelete`
