### PR TITLE
fix(nuxt): pass nuxt + workspace paths when importing builder

### LINKED ISSUE #14441: Cannot start nuxt:  Cannot find module '@nuxt/vite-builder'
### Environment

Nuxt CLI v3.0.0-rc.6                                                                                                                                                                               
RootDir: C:\Users\Ilya\Desktop\nuxt-app                                                                                                                                                            
Nuxt project info:                                                                                                                                                                                 

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `ssr`, `bridge`, `buildModules`, `css`, `windicss`, `build`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.4.3`
------------------------------

### Reproduction

https://github.com/loremru/nuxt-bug

### Describe the bug

 ERROR  Cannot start nuxt:  Cannot find module '@nuxt/vite-builder'                                                                                                                                
Require stack:                                                                                                                                                                                             
- C:\Users\Ilya\Desktop\nuxt-app\index.js  

image

### Additional context

on majestic-ui version 0.0.83-13 its ok. But on latest versions there are nothing changed, only yarn version. Also latest versions works on clear vite.js

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/14441

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This passes the path of `nuxt` and the workspace dir as a basis from which to resolve the builder, which can help if the builder dependency is not hoisted (probably only in the case of `@nuxt/vite-builder`).

We are probably due to refactor away from this `importModule` util but this can be considered a hotfix until then.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/builder.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ function watch (nuxt: Nuxt) {
 async function bundle (nuxt: Nuxt) {
   try {
     const { bundle } = typeof nuxt.options.builder === 'string'
-      ? await importModule(nuxt.options.builder, { paths: nuxt.options.rootDir })
+      ? await importModule(nuxt.options.builder, { paths: [import.meta.url, nuxt.options.rootDir, nuxt.options.workspaceDir] })
```
Comment (pi0) [inline packages/nuxt/src/core/builder.ts:64]: I would put rootDir before so that we pick user version but has same effect i guess with webpack

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/core/builder.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/builder.ts:64]:
```suggestion
      ? await importModule(nuxt.options.builder, { paths: [nuxt.options.rootDir, nuxt.options.workspaceDir, import.meta.url] })
```
