### PR TITLE
fix(nuxt): ensure `provide` / `inject` work in `setup` of `defineNuxtComponent`

### LINKED ISSUE #28573: Inject/Provide no longer works with defineNuxtComponent
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.6.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      devtools, multiCache, components, $production, $development, vue, algolia, imports, i18n, unocss, typescript, image, robots, runtimeConfig, css, vite, build, app, routeRules, compatibilityDate
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-o69gxl?file=app.vue,components%2FChildNuxtComponent.vue

### Describe the bug

I recently update from nuxt 3.11.2 to 3.12.4 and inject has stopped working in my components using defineNuxtComponent. Minimal reproduction attached.

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #30977: useRoute() is containing data from previous page when performing client-side navigation
### Environment

- Operating System: `Darwin`
- Node Version:     `v23.6.0`
- Nuxt Version:     `3.15.4`
- CLI Version:      `3.21.1`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@11.1.0`
- Builder:          `-`
- User Config:      `devtools`, `app`, `routeRules`, `modules`, `runtimeConfig`, `css`, `build`, `ssr`, `spaLoadingTemplate`, `experimental`, `primevue`, `i18n`, `compatibilityDate`, `turnstile`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.12.1`, `@pinia/nuxt@0.5.1`, `@primevue/nuxt-module@4.1.1`, `@nuxtjs/i18n@8.3.1`, `@nuxt/eslint@0.3.13`, `@nuxtjs/turnstile@0.9.10`, `@sentry/nuxt/module@8.55.0`
- Build Modules:    `-`

### Reproduction

[https://stackblitz.com/edit/github-iy4axfop?file=pages%2Fpage2.vue](https://stackblitz.com/edit/github-iy4axfop?file=pages%2Fpage2.vue)

### Describe the bug

When doing client-side navigation from one page to another and the second page (the page we are navigating to) is using the useRoute() hook in its setup method. The hook will still contain data from the previous page (path, params, ...). So for example when fetching data in the setup method with useAsyncData will cause issues as the path is not correct and will not contain desired data.

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Mini-ghost**
### 🔗 Linked issue

Resolve #30977
Resolve #28573

### 📚 Description

The `setup` function in `defineNuxtComponent` needs to run within the Nuxt context. However, if it is executed inside Vue’s `runWithContext`, it can cause issues with `provide` and `inject`.  

```ts
vueApp.runWithContext(() => {
  // This retrieves `provide` data directly from vueApp, which may lead to unexpected results.
  inject()
})
```

This PR introduces `callWithNuxtContext`, an internal function that executes a callback with the current Nuxt as the injection context, without the Vue app context. It ensures the correct context is provided when executing `setup` inside `defineNuxtComponent`.  

If there’s anything I haven’t considered thoroughly, please let me know. I really appreciate your time. Thank you!

### CODE REVIEW

File: packages/nuxt/src/app/nuxt.ts [hunk 1]
```diff
@@ -492,14 +492,18 @@ export function isNuxtPlugin (plugin: unknown) {
  * @since 3.0.0
  */
 export function callWithNuxt<T extends (...args: any[]) => any> (nuxt: NuxtApp | _NuxtApp, setup: T, args?: Parameters<T>) {
+  return nuxt.vueApp.runWithContext(() => callWithNuxtContext(nuxt, setup, args))
+}
+
+export function callWithNuxtContext<T extends (...args: any[]) => any> (nuxt: NuxtApp | _NuxtApp, setup: T, args?: Parameters<T>) {
```
Comment (huang-julien) [inline packages/nuxt/src/app/nuxt.ts:498]: we probably need to add `callWithNuxtContext` to `unctx` transforms list

Comment (Mini-ghost) [reply packages/nuxt/src/app/nuxt.ts:498]: May I ask what the `unctx` transforms list refers to?

Comment (huang-julien) [reply packages/nuxt/src/app/nuxt.ts:498]: you can take a look here https://github.com/nuxt/nuxt/blob/160efe7a7fe0a65755d9f7181a2a7f5b2532b66f/packages/nuxt/src/core/nuxt.ts#L396

It's needed server side to avoid cross request state pollution for node < 20 (or 22?) and client side to correctly keep context in promises as async context isn't supported yet in JS

Comment (huang-julien) [reply packages/nuxt/src/app/nuxt.ts:498]: We probably don't need to, callWithNuxt uses `vueApp.runWithContext`

**Review by danielroe — COMMENTED** [review]
Is it possible to solve this issue without adding a new composable that differs _ever so slightly_ from the existing one?

I'd even be happy with inlining a solution in `defineNuxtComponent`.

(would also be good to add a test so we know it works.)

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
thank you! ❤️
