### PR TITLE
fix: keep-alive component data should not be updated

### LINKED ISSUE #5166: keep-alive not working, resets data after change tab
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/9z8p69427r](https://codesandbox.io/s/9z8p69427r)

### Steps to reproduce

1. Click on ROEL USER button to go to Profile tab, which is an url (/roelmagdaleno/profile)
2. Go to Posts or Payments tab, when the component renders for the first time, it will show you the data.
3. Go back to Profile and then go to posts or payments again.
4. The current data that should kept alive has been reset to the initial values, an empty array.

### What is expected ?

Keep alive the current tab data, so it won't make another API call.

### What is actually happening?

The data is reset when user change the tab and enter again.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8776">#c8776</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix #5166

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/client.js [hunk 1]
```diff
@@ -491,6 +491,7 @@ function fixPrepatch(to, ___) {
       if (
         instance.constructor._dataRefresh &&
         Components[i] === instance.constructor &&
+        instance.$vnode.data.keepAlive !== true &&
```
Comment (pi0) [inline packages/vue-app/template/client.js]: Just to be sure, is the default value of `keepAlive`, `false` by default? If it is true, isn't this a minor breaking change?

Comment (clarkdo) [reply packages/vue-app/template/client.js]: The default value is `undefined`, it's just a flag in Vue for `keepAlive` cached component.

I don't think it's a breaking change, it should be a bug because `component` under `keep-alive` should be cached and never reload data as Vue is doing.

**Review by pi0 — APPROVED** [review]

**Comment by clarkdo** [comment]
Thanks, bro.

File: packages/vue-app/template/client.js (hunk 1 above)
Comment (ppsshh) [reply packages/vue-app/template/client.js:494]: Just wondering, shouldn't it be `data.props.keepAlive` instead of `data.keepAlive`? Because in bunch of files (`packages/vue-app/template/components/nuxt.js`, etc), `keepAlive` property is being wrapped into `props` object.

I ran into an issue when component is still trying to update its data() even though it has `keep-alived` enabled.
Changing this line to `data.props.keepAlive` solved problem for me.

PS: Nuxt v2.15.2 (seems like nothing have been changed with keep-alived behaviour ever since this commit)

Comment (clarkdo) [reply packages/vue-app/template/client.js:494]: keepAlive here is checking vue keep-alive component which will add keepAlive to vnode.data https://github.com/vuejs/vue/blob/b51430f598b354ed60851bb62885539bd25de3d8/src/core/components/keep-alive.js#L120

Comment (ppsshh) [reply packages/vue-app/template/client.js:494]: Thanks for your reply.

Sorry, but what should be the keep-alive component in here? Because debugger says that `instance` is a page component. Also, `instance.$vnode.data` doesn't have `keepAlive` property, but it does have `props.keepAlive`.

Screenshot:

Comment (clarkdo) [reply packages/vue-app/template/client.js:494]: I think the component in your screenshot is NuxtChild which has keep-alive prop for enabling keepAlive on it.

https://nuxtjs.org/docs/2.x/features/nuxt-components#keep-alive

Comment (ppsshh) [reply packages/vue-app/template/client.js:494]: You right, it is NuxtChild component.
I thought it should work the same way for any components, but seems like it is not the case.
I'll try to investigate it a little bit further and maybe come back with new issue and/or PR.
Thanks for your comments 👍
