### PR TITLE
fix(nuxt): load `spaLoadingTemplate` if file exists

### LINKED ISSUE #23047: fix(nuxt): allow load default spa loading indicator
### Environment

- Operating System: Darwin
- Node Version:     v20.1.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      ssr, build, modules, app, css, vite, runtimeConfig
- Runtime Modules:  @vueuse/nuxt@10.4.1
- Build Modules:    -

### Reproduction

add `~/app/spa-loading-template.html`

https://stackblitz.com/edit/github-6nhkcv

### Describe the bug

Loading `spaLoadingTemplate` by default from `~/app/spa-loading-template.html` no longer works as documented.

Implemented in https://github.com/nuxt/nuxt/pull/21640
- Default value: null, then `~/app/spa-loading-template.html` was loaded.

Changed default value to `false` in https://github.com/nuxt/nuxt/pull/22798
- `false` if undefined or null, then `~/app/spa-loading-template.html` is never loaded.

### Additional context

Since last version, `spaLoadingTemplate: true` only loads nuxt animation and does not load `~/app/spa-loading-template.html` if exist.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by davidglezz**
### 🔗 Linked issue

resolves #23047

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The behavior is not the same as documented because was changed in https://github.com/nuxt/nuxt/pull/22798

This PR restores the loading of ~/app/spa-loading-template.html when `spaLoadingTemplate` is `true`

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/app.ts [hunk 1]
```diff
@@ -189,12 +189,13 @@ export default defineUntypedSchema({
...
   /**
-   * A path to an HTML file, the contents of which will be inserted into any HTML page
+   * Boolean or a path to an HTML file with the contents of which will be inserted into any HTML page
    * rendered with `ssr: false`.
    *
-   * By default Nuxt will look in `~/app/spa-loading-template.html` for this file.
+   * Default value: `false` (Disabled).
    *
-   * You can set this to `false` to disable any loading indicator.
+   * If true, Nuxt will look for `~/app/spa-loading-template.html` file, if it does not exist,
```
Comment (danielroe) [inline packages/schema/src/config/app.ts:197]: I think the presence of `~/app/spa-loading-template.html` should enable the template. I think the default Nuxt image should only be used if this is set to `true` and if that file is not present:

- `true` +  `~/app/spa-loading-template.html` - template provided
- `true` - default nuxt icon
- `false` - no template
- unset +  `~/app/spa-loading-template.html` - template provided
- unset - no template

What do you think?

Comment (davidglezz) [reply packages/schema/src/config/app.ts]: Thanks for your review.
I implemented in that way.

Since its my first contribution, I expect change request.

File: packages/nuxt/src/core/nitro.ts [hunk 2]
```diff
@@ -415,3 +402,24 @@ export async function initNitro (nuxt: Nuxt & { _nitro?: Nitro }) {
 function relativeWithDot (from: string, to: string) {
   return relative(from, to).replace(/^([^.])/, './$1') || '.'
 }
+
+function spaLoadingTemplate (options: Nuxt['options']) {
```
Comment (danielroe) [inline packages/nuxt/src/core/nitro.ts:406]: Totally minor point, but let's take `nuxt` as the argument, for consistency with other code.

File: packages/schema/src/config/app.ts (hunk 1 above)
Comment (danielroe) [reply packages/schema/src/config/app.ts]: nice work

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Thank you for your great work on this PR ❤️
