### PR TITLE
fix(nuxt): warn when async data doesn't return a value

### LINKED ISSUE #27594: useAsyncData unexpected behaviour when callback return falsy value
### Environment

- Operating System: Darwin
- Node Version:     v20.2.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[Codesandbox link](https://codesandbox.io/p/devbox/asyncdata-deduplication-bug-2ywm5w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxdgf65800073b6jeonz2s2q%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxdgf65800023b6j09sj83ci%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxdgf65800043b6jiezwwyiw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxdgf65800063b6ju6e6pzsm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxdgf65800023b6j09sj83ci%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdgf65700013b6jbkfgrlj5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxdgf65800023b6j09sj83ci%2522%252C%2522activeTabId%2522%253A%2522clxdgf65700013b6jbkfgrlj5%2522%257D%252C%2522clxdgf65800063b6ju6e6pzsm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdgf65800053b6j3f7t5aal%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxdgf65800063b6ju6e6pzsm%2522%252C%2522activeTabId%2522%253A%2522clxdgf65800053b6j3f7t5aal%2522%257D%252C%2522clxdgf65800043b6jiezwwyiw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdgf65800033b6jovogrjn0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxdgf65800043b6jiezwwyiw%2522%252C%2522activeTabId%2522%253A%2522clxdgf65800033b6jovogrjn0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

- reload page
- view server logs, `callback log` message should be printed
- view client logs, `callback log` message should not be printed, but it is printed

### Describe the bug

When useAsyncData callback returns any falsy value(undefined, null, 0, false) that causes callback to execute both server and client side when only server side is expected

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/27594

### 📚 Description

This adds a log (server-side) in dev mode when `useAsyncData` or `useFetch` doesn't return a value.

### CODE REVIEW

File: packages/nuxt/src/app/composables/asyncData.ts [hunk 1]
```diff
@@ -311,6 +311,11 @@ export function useAsyncData<
           result = pick(result as any, options.pick) as DataT
         }
 
+        if (import.meta.dev && import.meta.server && !result) {
+          // @ts-expect-error private property
+          console.warn(`[nuxt] \`${options._functionName || 'useAsyncData'}\` should return a value that is not \`null\` or \`undefined\`.`)
```
Comment (manniL) [inline packages/nuxt/src/app/composables/asyncData.ts:316]: Would ti make sense to mention *why* it should?
