### PR TITLE
fix(vue-app): use browser to handle scrolling position on page reload

### LINKED ISSUE #3471: Reloading the page causes the scroll position to be reset to the top.
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://capu-zennio.github.io/nuxt-scroll-position-bug/index.html](https://capu-zennio.github.io/nuxt-scroll-position-bug/index.html).

### Steps to reproduce

1.- Load the Nuxt site.
2.- Scroll down.
3.- Refresh the page.

### What is expected ?

The scroll position should be the same as it was before reloading.

### What is actually happening?

The scroll is reset to the top of the page.

### Additional comments?

This issue is related to `window.history.scrollRestoration` (https://github.com/nuxt/nuxt.js/blob/b022d21bd3df08870171727eab9ad89dc1f9944f/lib/app/router.js#L41). If set to `auto`, the bug disappears.

I haven't taken an in-depth look at this, but something inside this file is causing the scroll to be set to [0,0].

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7284">#c7284</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by ahus1**
also for cases when returning to a nuxt site using a back button. 

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

When leaving the page, the scrollRestoration is restored to 'auto', as this will instruct the browser to memorize the scroll position. vue-router will not restore the scroll position on page reload and when navigating back from a different page. 

It solves the problem that the browser scrolls to the top when reloading a Nuxt page, as seen in Chrome for example with https://blog.lichter.io/.
Steps to reproduce: go to nuxt site, scroll down, press F5, browser will be at top of page and not at original scrolling position as expected.

Resolves #3471 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
(this fixes a browser scrolling issue on full page reload, I assume this can't be tested automatically)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/router.js [hunk 1]
```diff
@@ -86,7 +86,18 @@ Vue.use(Router)
 const scrollBehavior = <%= serializeFunction(router.scrollBehavior) %>
 <% } else { %>
 if (process.client) {
-  window.history.scrollRestoration = 'manual'
+  if ('scrollRestoration' in window.history) {
+    window.history.scrollRestoration = 'manual'
+    // reset scrollRestoration to auto when leaving page, allowing page reload and back-navigation from other pages
```
Comment (galvez) [inline packages/vue-app/template/router.js]: Thanks @ahus1 -- this looks good to me.

Please trim the comments to about 80 columns, for better readability.

Comment (ahus1) [reply packages/vue-app/template/router.js]: @galvez - comments are now re-formatted. Tests are still green. Changes force-pushed.

**Comment by manniL** [comment]
From Alex to Alex: Well done and thanks for the contribution 👏 Greetings to Frankfurt! ☺️

**Review by TheAlexLichter — APPROVED** [review]

**Review by galvez — APPROVED** [review]

**Comment by husayt** [comment]
This was really needed. Thanks

**Comment by pi0** [comment]
This fix is available on nuxt 2.5.5
