### PR TITLE
fix(schema): update vite `import.meta` types

### LINKED ISSUE #15645: ViteImportMeta `import.meta.glob` does not change types for the `eager: true` flag
### Environment

Nuxt project info:                                                                                                                                          04:18:43

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `ssr`, `pages`, `app`, `css`, `plugins`, `modules`, `runtimeConfig`, `devServer`, `tailwindcss`, `postcss`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/tailwindcss@6.1.3`, `@funken-studio/sitemap-nuxt-3@4.0.4`, `nuxt-swiper@0.1.6`
- Build Modules:    `-`
------------------------------

### Reproduction

I don't think a reproducer is needed here.

### Describe the bug

The `ViteImportMeta` type in the following file appears to be derived from an older version of Vite.

https://github.com/nuxt/framework/blob/a9df4b75d622b21c1c0cc6f3e601722e42714b90/packages/schema/src/types/global/vite.ts#L34

Current versions of vite have a generic that differs the return type based on whether eager is true or false.

https://github.com/vitejs/vite/blob/main/packages/vite/types/importMeta.d.ts

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by clarkdo**
### 🔗 Linked issue

Fix https://github.com/nuxt/nuxt/issues/15645

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)

### 📚 Description

Sync ImportMeta from Vite and try to import from Vite exported types.

### CODE REVIEW

File: packages/schema/src/types/global/vite.ts [hunk 1]
```diff
@@ -1,35 +1,15 @@
...
-  send (event: any, data?: any): void
-}
-
-export interface ViteGlobOptions {
-  as?: string
-  eager?: boolean
-  import?: string
-  query?: string | Record<string, string | number | boolean>
-  exhaustive?: boolean
-}
```
Comment (danielroe) [inline packages/schema/src/types/global/vite.ts:27]: For now, could we keep these inlined, but updated to match the latest upstream vite types?

I would be very willing to consider directly referencing or adding vite types to the `nuxt.d.ts` build conditionally, in line with your previous PR - let's discuss at https://github.com/nuxt/nuxt/issues/14131.

Comment (clarkdo) [reply packages/schema/src/types/global/vite.ts:27]: > updated to match the latest upstream vite types?

Sorry, can you please clarify the benefits ?  This also already has vite as dev dep, so it doesn't introduce any structural change, and I think it doesn't have conflict with `directly referencing or adding vite types to the nuxt.d.ts`, we can always remove this file when it's resolved.

Comment (danielroe) [reply packages/schema/src/types/global/vite.ts:27]: The reason these are currently here and not already directly depending on vite's types is that @pi0 was reluctant to depend on vite's types because we may not support all of them, and this way we curate the types that are made available. You can see the context here: https://github.com/nuxt/framework/pull/1439.

Let's discuss a different approach in the linked issue, but for now (in this PR) we should keep the current approach but update the types.

Comment (clarkdo) [reply packages/schema/src/types/global/vite.ts]: Makes sense, I've updated the pr accordingly, thanks!

**Review by danielroe — APPROVED** [review]
Thank you. ❤️

**Comment by clarkdo** [comment]
@danielroe What formatter rules are we following in nuxt now ? I don't see any prettier config, is it only editorconfig ?
