### PR TITLE
fix(nuxt): remove backticks around runtimeConfig warning log

### LINKED ISSUE #27548: Wrong link in the devtools when accessing private env
### Environment

Doesn't matter

### Reproduction

Paste it into your devtools and click on the link.

```
console.warn(`See \`https://nuxt.com/docs/guide/going-further/runtime-config\` for more information.`)
```

### Describe the bug

After updating to 3.12 I've got an error in my devtools.

```
[nuxt] Could not access `nuxt-schema-org`. The only available runtime config keys on the client side are `public` and `app`. See `https://nuxt.com/docs/guide/going-further/runtime-config` for more information.
```

After click on the link my browser open a wrong link: `https://nuxt.com/docs/guide/going-further/runtime-config%60`

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #27555: Runtime config warning (typo error link)
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  bun@1.0.30
- Builder:          -
- User Config:      devtools, runtimeConfig, modules, image, sanity, site, seo, build
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxtjs/tailwindcss@6.12.0, @nuxt/image@1.7.0, @nuxtjs/sanity@1.11.3, @nuxtjs/seo@2.0.0-rc.10
- Build Modules:    -
------------------------------

### Reproduction

I'm not providing a reproduction because there is only a small typo error:

```
[nuxt] Could not access `nuxt-schema-org`. The only available runtime config keys on the client side are `public` and `app`. See `https://nuxt.com/docs/guide/going-further/runtime-config` for more information.
```

I noticed that the link redirects to this:
https://nuxt.com/docs/guide/going-further/runtime-config%60

### Describe the bug

I noticed that the link redirects to this:
https://nuxt.com/docs/guide/going-further/runtime-config%60

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by letstri**
### 🔗 Linked issue

resolves #27548
resolves https://github.com/nuxt/nuxt/issues/27555

### 📚 Description

I've added a `#` to fix the link.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

File: packages/nuxt/src/app/nuxt.ts [hunk 1]
```diff
@@ -568,7 +568,7 @@ function wrappedConfig (runtimeConfig: Record<string, unknown>) {
       if (typeof p === 'string' && p !== 'public' && !(p in target) && !p.startsWith('__v') /* vue check for reactivity, e.g. `__v_isRef` */) {
         if (!loggedKeys.has(p)) {
           loggedKeys.add(p)
-          console.warn(`[nuxt] Could not access \`${p}\`. The only available runtime config keys on the client side are ${keys.join(', ')} and ${lastKey}. See \`https://nuxt.com/docs/guide/going-further/runtime-config\` for more information.`)
+          console.warn(`[nuxt] Could not access \`${p}\`. The only available runtime config keys on the client side are ${keys.join(', ')} and ${lastKey}. See https://nuxt.com/docs/guide/going-further/runtime-config for more information.`)
```
Comment (pi0) [inline packages/nuxt/src/app/nuxt.ts:571]: I think format was supposed to be passed to consola for proper formatting

Comment (letstri) [reply packages/nuxt/src/app/nuxt.ts:571]: I think consola should have several formats to avoid this bug

Comment (danielroe) [reply packages/nuxt/src/app/nuxt.ts:571]: I don't think `consola` is enabled in the browser console.
