### PR TITLE
fix(nitro): break recursive rendering deadlocks during prerender

### LINKED ISSUE #33871: Prerender silently failures if errors occur in middleware
### Environment

|                      |                                                                                    |
| -------------------- | ---------------------------------------------------------------------------------- |
| **Operating system** | `Windows 10.0.26100`                                                               |
| **CPU**              | `AMD Ryzen 7 5800H with Radeon Graphics          (16 cores)`                       |
| **Node.js version**  | `v24.4.1`                                                                          |
| **nuxt/cli version** | `3.31.2`                                                                           |
| **Package manager**  | `pnpm@9.6.0`                                                                       |
| **Nuxt version**     | `4.2.2`                                                                            |
| **Nitro version**    | `2.12.9`                                                                           |
| **Builder**          | `vite@7.2.7`                                                                       |
| **Config**           | `compatibilityDate`, `css`, `devtools`, `modules`, `nitro`, `routeRules`, `vite`   |
| **Modules**          | `@nuxt/ui@4.2.1`                                                                   |

### Reproduction

setup prerenderer in `nuxt.config.ts` with
```
  routeRules: {
    "/": { prerender: true },
  },
```

create a global middleware called `auth.global.ts
```typescript
export default defineNuxtRouteMiddleware(async (to, _from) => {
  const isAuthenticated = !!(await useFetch("/api/auth/session")).data.value // This is a dead api url

  if (!isAuthenticated && to.path.startsWith("/me")) { // simulate guarded routes
    return navigateTo("/login")
  }
})
```

The build fails

### Describe the bug

When an error is thrown in a middleware, the build process fails silently.

### Additional context

_No response_

### Logs

```shell-script
$ bun run --bun nuxt build
│
▲  Changing NODE_ENV from development to production, to avoid unintended behavior.
┌  Building Nuxt for production...
│
●  Nuxt 4.2.2 (with Nitro 2.12.9, Vite 7.2.7 and Vue 3.5.25)
[12:33:15] ℹ Nuxt Icon server bundle mode is set to remote
│
●  Nitro preset: vercel-edge
[12:33:16] ℹ Building client...
[12:33:16] ℹ vite v7.2.7 building client environment for production...
[12:33:22] ℹ ✓ 709 modules transformed.
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/manifest.json                   1.71 kB │ gzip:   0.43 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/error-500.DLkAwcfL.css    1.91 kB │ gzip:   0.76 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/error-404.BLrjNXsr.css    2.43 kB │ gzip:   0.90 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/entry.Cqen4AGv.css      173.88 kB │ gzip:  25.00 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/DlAUqK2U.js               0.09 kB │ gzip:   0.10 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/D5a8P_r9.js               0.13 kB │ gzip:   0.14 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/BYtXygAl.js               0.17 kB │ gzip:   0.16 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/r0Kettj0.js               3.50 kB │ gzip:   1.60 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/C26EZytt.js               3.79 kB │ gzip:   1.75 kB
[12:33:23] ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/BEfRW1wf.js             350.93 kB │ gzip: 127.49 kB
[12:33:23] ℹ ✓ built in 6.53s
[12:33:23] ✔ Client built in 6573ms
[12:33:23] ℹ Building server...
[12:33:23] ℹ vite v7.2.7 building ssr environment for production...
[12:33:25] ℹ ✓ 119 modules transformed.

[12:33:25]  WARN  [plugin @tailwindcss/vite:generate:build] Sourcemap is likely to be incorrect: a plugin (@tailwindcss/vite:generate:build) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help


[12:33:25]  WARN  [plugin @tailwindcss/vite:generate:build] Sourcemap is likely to be incorrect: a plugin (@tailwindcss/vite:generate:build) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help (x2)


[12:33:25]  WARN  [plugin @tailwindcss/vite:generate:build] Sourcemap is likely to be incorrect: a plugin (@tailwindcss/vite:generate:build) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help (x3)


[12:33:25]  WARN  [plugin @tailwindcss/vite:generate:build] Sourcemap is likely to be incorrect: a plugin (@tailwindcss/vite:generate:build) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help (x4)

[12:33:25] ℹ ✓ built in 2.27s
[12:33:25] ✔ Server built in 2282ms
[nitro 12:33:25] ℹ Initializing prerenderer

[12:33:26]  WARN  "file:///D:/CodeFolders/nuxt-err/node_modules/@nuxt/nitro-server/dist/runtime/utils/cache-driver.js" is imported by "virtual:#nitro-internal-virtual/storage", but could not be resolved – treating it as an external dependency.

[nitro 12:33:27] ℹ Prerendering 1 routes
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/33871

### 📚 Description

when a global route middleware called `useFetch` (or made a fetch request) that was resolved by a path that made the same request. in this instance, the build silently exited with code 0 and the affected page was missing from the output.

the issue was a cyclic await with `sharedPrenderData`

this PR detects these cyclical renders when prerendering, and throws a 508 error.

### CODE REVIEW

File: packages/nitro-server/src/runtime/handlers/renderer.ts [hunk 1]
```diff
@@ -65,6 +65,22 @@ const handler: ReturnType<typeof defineEventHandler> = defineEventHandler(async
...
   }
 
+  if (import.meta.prerender && prerenderRenderingURLs) {
+    const renderingURL = event.url.pathname + event.url.search
+    const stack = prerenderRenderingURLs.getStore()
+    if (stack?.includes(renderingURL)) {
+      throw new HTTPError({
+        status: 508,
+        statusText: `Loop detected while prerendering "${renderingURL}". A request was made to this URL while the same URL was already being rendered in the same call chain (commonly caused by calling \`useFetch\`/\`$fetch\` in route middleware against a path that is not handled at build time).`,
+      })
```
Comment (atinux) [inline packages/nitro-server/src/runtime/handlers/renderer.ts:80]: I like it, what do you think of having a way to display the chain calls to easier spot the one that create the loop?

Comment (danielroe) [reply packages/nitro-server/src/runtime/handlers/renderer.ts:80]: nice idea - so something like `/ -> /about -> /`?

**Review by atinux — APPROVED** [review]
Left a comment on how we can improve the error message if possible, otherwise looks good to me!
