### PR TITLE
fix: normalize routes and decode resolved query

### LINKED ISSUE #8429: Query string parameters are not URI-decoded in route.query
### Versions

- nuxt: v2.14.8 and v2.14.9
- node: v15.3.0

### Reproduction

Since updating to nuxt v2.14.8, query string parameters with encoded characters are passed un-decoded in `route.query` in `context` to `asyncData`. The v2.14.9 hotfix did not fix this issue.

<details>
<summary>Additional Details</summary>

```js

  async asyncData ({ app, route, error }) {
    let data = {
      search: {
        query: route.query.q,
        location: route.query.gl,
        registrar: route.query.r,
        terms: route.query.t,
        defaults: route.query.d,
        results: []
      },
      metadata: {
        domain: route.params.domain
      }
    }

    // BUG: data.search.terms == 'coffee%2Cfood' instead of 'coffee,food'

    // ...

    return data
  }
```
</details>

### Steps to reproduce

- Visit `/?t=coffee,food`
- In `asyncData`, extract the `t` query string parameter

### What is Expected?

`route.query.t == 'coffee,food'`

### What is actually happening?

`route.query.t == 'coffee%2Cfood'`

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- History: vuejs/vue-router#3350 > #8325 > #8421 
- Resolves #8429, #8442

Since `vue-router@2.14.9` makes it mandatory to use `encodeURI` when using `RouterLink`, `NuxtLink` and  `router.push`, we introduced a fix by automatically encoding URIs. But seems it makes regression when a query param (and probably path param) is encoded and not being properly decoded.

Changes:
- Use `normalizeURL` from [`@nuxt/ufo`](https://github.com/nuxt-contrib/ufo)
- Decode `route.resolved.query` with `decodeURIComponent`
- Encode redirect path with `normalizeURL` since http headers should be encoded

--- 

Foot note: Case of #8429 only happens when manually using `encodeURIComponent` on query parameters instead of `encodeURI`  and at least chrome auto fixes this. (still this is a regression that we should fixed)

record

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by ydnar** [comment]
Note: we see this issue when a browser visits the encoded URL (via typing, for instance), without any router push.

**Review by clarkdo — APPROVED** [review]

**Review by clarkdo — APPROVED** [review]

File: packages/utils/src/route.js [hunk 1]
```diff
@@ -280,3 +279,11 @@ export const promisifyRoute = function promisifyRoute (fn, ...args) {
   }
   return promise
 }
+
+export function safeEncodeComponent (str) {
+  return /%[0-9a-fA-F]{2}/.test(str) ? str : encodeURI(str)
+}
+
+export function safeEncode (str) {
+  return str.split('/').map(safeEncodeComponent).join('/')
```
Comment (clarkdo) [inline packages/utils/src/route.js:288]: What if url includes %.. as path or parameter ?

Like/rate/%30?max=%90

File: packages/utils/src/route.js [hunk 2]
```diff
@@ -280,3 +279,11 @@ export const promisifyRoute = function promisifyRoute (fn, ...args) {
   }
   return promise
 }
+
+export function safeEncodeComponent (str) {
+  return /%[0-9a-fA-F]{2}/.test(str) ? str : encodeURI(str)
```
Comment (clarkdo) [inline packages/utils/src/route.js:284]: What if url includes %.. as path or parameter ?

Like: /rate/%30?max=%90

Comment (pi0) [reply packages/utils/src/route.js:284]: `/%[0-9a-fA-F]{2}/.test('/rate/%30?max=%90')` > true

In this case we avoid encoding

Comment (clarkdo) [reply packages/utils/src/route.js:284]: So if url also includes special characters, we’ll skip encoding, is that expected?

Like: /rate/%30?max=%90&name= тест

Comment (pi0) [reply packages/utils/src/route.js:284]: Last commit: `/rate/%30?max=%90&name= тест` => `/rate/%30?max=%90&name=%20%D1%82%D0%B5%D1%81%D1%82`

Comment (pi0) [reply packages/utils/src/route.js:284]: Last update: `/rate/%30?max=%90&name=%20%D1%82%D0%B5%D1%81%D1%82`

File: packages/server/src/server.js [hunk 3]
```diff
@@ -162,12 +162,16 @@ export default class Server {
...
-    if (this.options.dev && this.nuxt.options.router.base !== '/') {
+    const routerBase = this.nuxt.options.router.base
+    if (this.options.dev && routerBase !== '/') {
       this.useMiddleware({
         prefix: false,
-        handler: (req, res) => {
-          const to = urlJoin(this.nuxt.options.router.base, req.url)
-          consola.info(`[Development] Redirecting from \`${decodeURI(req.url)}\` to \`${decodeURI(to)}\` (router.base specified).`)
+        handler: (req, res, next) => {
+          if (decodeURI(req.url).startsWith(decodeURI(routerBase))) {
```
Comment (danielroe) [inline packages/server/src/server.js:170]: shouldn't we assume that user-provided data like `router.base` is already decoded?

Comment (pi0) [reply packages/server/src/server.js:170]: routerBase is intentionally encoded and normalized in `options.js`

File: packages/utils/src/route.js (hunk 2 above)
Comment (danielroe) [reply packages/utils/src/route.js:284]: Is there any merit in using something like this as our util - not reinventing url parsing?
```js
const url = '/rate/%30?max=%90&name= тест'
const { pathname, search } = new URL('http://localhost${url}')
return `${pathname}${search}`
// "/rate/%30?max=%90&name=%20%D1%82%D0%B5%D1%81%D1%82"
```

Comment (pi0) [reply packages/utils/src/route.js:284]: I would like to at least use a URL aware solution instead of splitting (and finally we should move url utils to a package). But depending on environment URL, might be tricky and inconsistent. At least here is IE 11 behavior:

image

Comment (danielroe) [reply packages/utils/src/route.js:284]: In fact we also get benefit of leading slash normalisation if we do:
```js
function safeEncode (str) {
  const { pathname, search } = new URL(str, 'http://localhost')
  return `${pathname}${search}`
}
```

About IE - it is one of the few exceptions - could we polyfill in this case?

Comment (pi0) [reply packages/utils/src/route.js:284]: Indeed we can but it costs bundle size for modern browsers and actually it is not enough to make url utils (for joining or ensure there is no leading slash for example) -- not specific to this PR's case

Comment (danielroe) [reply packages/utils/src/route.js:284]: In fact IE11 works fine for me - just have to wrap in brackets.
Screenshot from 2020-12-04 16-23-20

Comment (pi0) [reply packages/utils/src/route.js:284]: Fair enough :) Switching to URL

Comment (pi0) [reply packages/utils/src/route.js:284]: There is just one downside that it is implicit it is full url or URI :))

Comment (pi0) [reply packages/utils/src/route.js:284]: Thanks for bringing it up. Working on util before merge ;)
