### PR TITLE
fix(nuxt): add types for webpack/vite environments

### LINKED ISSUE #14131: add asset import typings for webpack and vite builders
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3-27571095.9379606`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `trpc`, `typescript`, `runtimeConfig`, `css`
- Runtime Modules:  `trpc-nuxt@0.1.24`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Create an `asset` folder in project root
2. Add any image to it.
3. Import this image from a TypeScript
	```ts
	import MyImage from 'assets/my-image.png'
	```

### Describe the bug

TS got type error:
```ts
import MyImage from 'assets/my-image.png'
// TS2307: Cannot find module 'assets/my-image.png' or its corresponding type declarations.
```

### Additional context

In the case of Vite, this error is easily corrected by adding "client" to the [`types`](https://github.com/nuxt/framework/blob/603f07c3b8f93feefb8c59c5ff3a970a60e38041/packages/nuxi/src/utils/prepare.ts#L23) in generated `.nuxt/tsconfig.json`. Something like: 
```diff
// nuxi/src/utils/prepare.ts
export const writeTypes = async (nuxt: Nuxt) => {
  const modulePaths = getModulePaths(nuxt.options.modulesDir)

  const tsConfig: TSConfig = defu(nuxt.options.typescript?.tsConfig, {
    compilerOptions: {
      jsx: 'preserve',
      target: 'ESNext',
      module: 'ESNext',
      moduleResolution: 'Node',
      skipLibCheck: true,
      strict: nuxt.options.typescript?.strict ?? false,
      allowJs: true,
      noEmit: true,
      resolveJsonModule: true,
      allowSyntheticDefaultImports: true,
-     types: ['node'],
+     types: nuxt.options.builder === '@nuxt/vite-builder' ? ["node", 'vite/client'] : ['node'],
      baseUrl: relative(nuxt.options.buildDir, nuxt.options.rootDir),
      paths: {}
    },
    include: [
      './nuxt.d.ts',
      join(relative(nuxt.options.buildDir, nuxt.options.rootDir), '**/*'),
      ...nuxt.options.srcDir !== nuxt.options.rootDir ? [join(relative(nuxt.options.buildDir, nuxt.options.srcDir), '**/*')] : []
    ]
  })
```

But I'm not sure how to fix this if the webpack is used as a builder

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/14131

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds asset typings and other environment types that are more precisely tailored to the builder the end user is using.

~~With https://github.com/nuxt/nuxt/pull/20748,~~ When `@nuxt/module-builder` is detected, we can disable this so that our crafted types in `@nuxt/schema/env` can be used to prevent wrongly relying on features specific to just one of the builders (https://github.com/nuxt/framework/pull/5376#issuecomment-1177938331).

We also avoid polluting the global context when importing from `@nuxt/schema` directly.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/typescript.ts [hunk 1]
```diff
@@ -13,6 +14,14 @@ export default defineUntypedSchema({
      */
     strict: true,
 
+    /**
+     * whether or not to write declaration files to add specific types based on your builder environment. It is
+     * advised to turn this off for module authors, who should support multiple possible builders.
+     */
+    builderEnv: {
+      $resolve: async (val, get) => val ?? await resolvePath('@nuxt/module-builder', { url: await get('modulesDir') }).then(path => !path).catch(() => null) ?? true,
```
Comment (pi0) [inline packages/schema/src/config/typescript.ts:22]: If both are installed in a mono-repo, this can make issues. Can we simply support `typescript.builder` as a way to override default (top level) `builder` only for types and also use `vite | webpack` instead of package names?

Comment (danielroe) [reply packages/schema/src/config/typescript.ts:22]: I'm also very happy to add the override directly from nuxt/module-builder. 👍

**Review by pi0 — APPROVED** [review]
Small nit pick: It is `build(er)` vs `build-env`. Othwrwise lgtm...
