### PR TITLE
fix(router): optional dynamic routing in children routes

### LINKED ISSUE #7571: Optional dynamic route not generated as expected
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://codesandbox.io/s/naughty-framework-qb4jg?file=/pages/home/foo/edit/_id.vue](https://codesandbox.io/s/naughty-framework-qb4jg?file=/pages/home/foo/edit/_id.vue)

### Steps to reproduce

see the repo link folder, same as:
```
├── about.vue
├── home
│   ├── _user.vue
│   ├── foo
│   │   ├── edit
│   │   │   └── _id.vue
│   │   ├── index.vue
│   │   └── list
│   │       └── index.vue
│   └── foo.vue
└── index.vue
```

### What is expected ?

```js
routes: [{
    path: "/about",
    component: _bde21ea8,
    name: "about"
  }, {
    path: "/home/foo",
    component: _aef39672,
    children: [{
      path: "",
      component: _ba586bec,
      name: "home-foo"
    }, {
      path: "list",
      component: _43d1f2ce,
      name: "home-foo-list"
    }, {
    //  expect the path is optional
      path: "edit/:id?",
      component: _53866cad,
      name: "home-foo-edit-id"
    }]
  }, {
    path: "/home/:user?",
    component: _324f446b,
    name: "home-user"
  }, {
    path: "/",
    component: _7e72691e,
    name: "index"
  }]
```

### What is actually happening?

```js
routes: [{
    path: "/about",
    component: _bde21ea8,
    name: "about"
  }, {
    path: "/home/foo",
    component: _aef39672,
    children: [{
      path: "",
      component: _ba586bec,
      name: "home-foo"
    }, {
      path: "list",
      component: _43d1f2ce,
      name: "home-foo-list"
    }, {
      //  but it is not optional router
      path: "edit/:id",
      component: _53866cad,
      name: "home-foo-edit-id"
    }]
  }, {
    path: "/home/:user?",
    component: _324f446b,
    name: "home-user"
  }, {
    path: "/",
    component: _7e72691e,
    name: "index"
  }]
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10817">#c10817</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by farnabaz**
When processing child routes `route.path` and `route.name` has a difference, and this difference causes invalid optional detection in `cleanChildrenRoutes` function. (`route.path` is relative to parent `path`, but `route.name` always contains all parts of route). Example:
```js
{
    name: 'home-foo',
    path: '/home/foo',
    children: [
        {
            name: 'home-foo-index',
            path: ''
        },
        {
            name: 'home-foo-list-index',
            path: '/list'
        },
        {
            name: 'home-foo-edit-id',
            path: '/edit/:id?'
        }
    ]
}
```

### Update 1:
Case 1: `edit/:id` **is** child of `/home/foo`
Screen Shot 2020-08-04 at 12 44 44 PM

Case 2: `edit/:id` **is not** child of `/home/foo`.(Just remove `/home/foo.vue` from Case 1)
Screen Shot 2020-08-04 at 12 47 51 PM

Fix #7571

## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by rchl** [comment]
Can you show the output routes both before and after the fix?

File: packages/utils/src/route.js [hunk 1]
```diff
@@ -41,29 +41,26 @@ export const flatRoutes = function flatRoutes (router, fileName = '', routes = [
   return routes
 }
 
-function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-', trailingSlash) {
-  let start = -1
+function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-', trailingSlash, namePrefix) {
```
Comment (rchl) [inline packages/utils/src/route.js:44]: I don't know if the fix is sound in general so you might hold off addressing my comments but... wouldn't it be better to call the new argument `parentRouteName`? A bit easier to understand?

File: packages/utils/src/route.js [hunk 2]
```diff
@@ -41,29 +41,26 @@ export const flatRoutes = function flatRoutes (router, fileName = '', routes = [
...
   const regExpIndex = new RegExp(`${routeNameSplitter}index$`)
   const routesIndex = []
   routes.forEach((route) => {
     if (regExpIndex.test(route.name) || route.name === 'index') {
       // Save indexOf 'index' key in name
-      const res = route.name.split(routeNameSplitter)
-      const s = res.indexOf('index')
-      start = start === -1 || s < start ? s : start
+      const res = route.name.replace(namePrefix, '').split(routeNameSplitter)
```
Comment (rchl) [inline packages/utils/src/route.js:50]: Do you want to only remove prefix if it's at the beginning of the name? In that case, it would probably make sense to make this replace more robust so that it doesn't try to replace anywhere within the name.

**Comment by farnabaz** [comment]
> Can you show the output routes both before and after the fix?

I've added two cases in description

File: packages/utils/src/route.js [hunk 3]
```diff
@@ -41,13 +41,13 @@ export const flatRoutes = function flatRoutes (router, fileName = '', routes = [
   return routes
 }
 
-function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-', trailingSlash, namePrefix) {
+function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-', trailingSlash, parentRouteName) {
   const regExpIndex = new RegExp(`${routeNameSplitter}index$`)
```
Comment (rchl) [inline packages/utils/src/route.js:45]: Not a new code but I belive this could be like some and there would be no need for `route.name === 'index'` check below.
```suggestion
  const regExpIndex = new RegExp(`(^|${routeNameSplitter})index$`)
```

Comment (farnabaz) [reply packages/utils/src/route.js:45]: `regExpIndex` is used to remove the last occurrence of `-index from `route.name` in line 77, this change will break the replacement

Comment (rchl) [reply packages/utils/src/route.js:45]: OK, never mind. :)

File: packages/utils/src/route.js [hunk 4]
```diff
@@ -41,29 +41,26 @@ export const flatRoutes = function flatRoutes (router, fileName = '', routes = [
   return routes
 }
 
-function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-', trailingSlash) {
-  let start = -1
+function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-', trailingSlash, parentRouteName) {
   const regExpIndex = new RegExp(`${routeNameSplitter}index$`)
+  const regExpParentRouteName = new RegExp(`^${parentRouteName}-`)
```
Comment (rchl) [inline packages/utils/src/route.js:46]: Should use `routeNameSplitter` instead of hardcoded `-`.

Comment (farnabaz) [reply packages/utils/src/route.js]: Thanks

**Review by pi0 — APPROVED** [review]
