### PR TITLE
fix(nuxt): update nitropack preset directory

### LINKED ISSUE #2846: netlify presets: [plugin impound] This module cannot be imported in server runtime
### Environment

`nuxi info` output:
```
Nuxt project info:                                                    19:22:11

------------------------------
- Operating System: Linux
- Node Version:     v18.20.4
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.11.0
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/eslint@0.6.1, @nuxt/content@2.13.4, nuxt-time@0.1.3, nuxt-gtag@3.0.1, notivue/nuxt, @nuxtjs/sitemap@5.3.5, @nuxt/image@1.8.1, nuxt-jsonld@2.0.8, @nuxt/fonts@0.9.2, nuxt-purgecss@2.0.0, @nuxt/icon@1.6.1
- Build Modules:    -

```

### Reproduction

`NITRO_PRESET=netlify-legacy pnpm build` in a recently upgraded nuxt project to v3.14.0

### Describe the bug

Build fails when trying to use either `netlify-legacy` or `netlify` presets with the following error:
```
[19:21:13]  ERROR  [plugin impound] This module cannot be imported in server runtime. [importing node_modules/.pnpm/nitropack@2.10.2_typescript@5.6.3_webpack-sources@3.2.3/node_modules/nitropack/dist/presets/netlify/legacy/runtime/_deno-env-polyfill from node_modules/.pnpm/nitropack@2.10.2_typescript@5.6.3_webpack-sources@3.2.3/node_modules/nitropack/dist/presets/netlify/legacy/runtime/netlify.mjs]
```

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #29777: Some nitro presets fail to build with 3.14.0
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.10.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  npm@10.9.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Add following to `nuxt.config.ts`:

```ts
  nitro: {
    preset: "node-cluster"
  },
```

Then `npm run build`

### Describe the bug

Building server runtime fails with the following message:

```
ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/dist/presets/node/runtime/node-server.mjs from node_modules/nitropack/dist/presets/node/runtime/node-cluster.mjs]
```

### Additional context

https://github.com/nitrojs/nitro/issues/2846

### Logs

```
npm run build

> build
> nuxt build

Nuxt 3.14.0 with Nitro 2.10.2                                                                                                                                                                                                                                                                               22:29:36
ℹ Building client...                                                                                                                                                                                                                                                                                       22:29:37
ℹ vite v5.4.10 building for production...                                                                                                                                                                                                                                                                  22:29:37
ℹ ✓ 133 modules transformed.                                                                                                                                                                                                                                                                               22:29:38
ℹ .nuxt/dist/client/manifest.json                   1.06 kB │ gzip:  0.29 kB                                                                                                                                                                                                                               22:29:38   
ℹ .nuxt/dist/client/_nuxt/error-500.D6506J9O.css    1.88 kB │ gzip:  0.72 kB                                                                                                                                                                                                                               22:29:38
ℹ .nuxt/dist/client/_nuxt/error-404.CoZKRZXM.css    3.56 kB │ gzip:  1.10 kB                                                                                                                                                                                                                               22:29:38
ℹ .nuxt/dist/client/_nuxt/entry.Dhfs5r89.css       12.41 kB │ gzip:  2.57 kB                                                                                                                                                                                                                               22:29:38   
ℹ .nuxt/dist/client/_nuxt/fUemcxuZ.js               3.39 kB │ gzip:  1.53 kB                                                                                                                                                                                                                               22:29:38   
ℹ .nuxt/dist/client/_nuxt/CyNs78vZ.js               9.31 kB │ gzip:  3.74 kB                                                                                                                                                                                                                               22:29:38   
ℹ .nuxt/dist/client/_nuxt/k56FkBKk.js             219.08 kB │ gzip: 62.60 kB                                                                                                                                                                                                                               22:29:38   
ℹ ✓ built in 765ms                                                                                                                                                                                                                                                                                         22:29:38   
✔ Client built in 774ms                                                                                                                                                                                                                                                                                    22:29:38   
ℹ Building server...                                                                                                                                                                                                                                                                                       22:29:38   
ℹ vite v5.4.10 building SSR bundle for production...                                                                                                                                                                                                                                                       22:29:38   
ℹ ✓ 48 modules transformed.                                                                                                                                                                                                                                                                                22:29:38   
ℹ .nuxt/dist/server/_nuxt/entry-styles.2WiZsmcQ.mjs             0.08 kB                                                                                                                                                                                                                                    22:29:38   
ℹ .nuxt/dist/server/_nuxt/error-500-styles.DqmriZ_b.mjs         0.08 kB                                                                                                                                                                                                                                    22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-404-styles.DRLC0U6S.mjs         0.08 kB                                                                                                                                                                                                                                    22:29:39   
ℹ .nuxt/dist/server/_nuxt/welcome-styles.DA1Jnpwh.mjs           0.15 kB                                                                                                                                                                                                                                    22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-404-styles.BcoFjqgl.mjs         0.15 kB                                                                                                                                                                                                                                    22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-500-styles.DPP87-Dp.mjs         0.15 kB                                                                                                                                                                                                                                    22:29:39   
ℹ .nuxt/dist/server/styles.mjs                                  1.11 kB                                                                                                                                                                                                                                    22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-DiWYPNRc.js    2.10 kB │ map:   0.12 kB                                                                                                                                                                                                                   22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-D8Sw_W7I.js    3.80 kB │ map:   0.12 kB                                                                                                                                                                                                                   22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-500-DBmARhSQ.js                 4.54 kB │ map:   5.35 kB                                                                                                                                                                                                                   22:29:39   
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-qoWoZyO1.js       12.67 kB │ map:   0.11 kB                                                                                                                                                                                                                   22:29:39   
ℹ .nuxt/dist/server/_nuxt/error-404-CrStZ1l5.js                15.45 kB │ map:  28.66 kB                                                                                                                                                                                                                   22:29:39   
ℹ .nuxt/dist/server/server.mjs                                124.48 kB │ map: 177.06 kB                                                                                                                                                                                                                   22:29:39   
ℹ ✓ built in 304ms                                                                                                                                                                                                                                                                                         22:29:39   
✔ Server built in 306ms                                                                                                                                                                                                                                                                                    22:29:39
✔ Generated public .output/public                                                                                                                                                                                                                                                                    nitro 22:29:39
ℹ Building Nuxt Nitro server (preset: node-cluster, compatibility date: 2024-04-03)                                                                                                                                                                                                                  nitro 22:29:39   

 ERROR  RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/dist/presets/node/runtime/node-server.mjs from node_modules/nitropack/dist/presets/node/runtime/node-cluster.mjs]                                                           nitro 22:29:39  


undefined


 ERROR  [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/dist/presets/node/runtime/node-server.mjs from node_modules/nitropack/dist/presets/node/runtime/node-cluster.mjs]                                                                              22:29:39  

  at getRollupError (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
  at error (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
  at Object.error (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:20604:20)
  at Object.resolveId (/D:/random/nuxt314-cluster/node_modules/impound/dist/index.js:29:11)
  at /D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:20789:40
  at async PluginDriver.hookFirstAndGetPlugin (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:20689:28)
  at async resolveId (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:19293:26)
  at async ModuleLoader.resolveId (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:19722:15)
  at async Object.resolveId (/D:/random/nuxt314-cluster/node_modules/@rollup/plugin-commonjs/dist/es/index.js:600:10)
  at async PluginDriver.hookFirstAndGetPlugin (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:20689:28)
  at async resolveId (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:19293:26)
  at async ModuleLoader.resolveId (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:19722:15)
  at async ModuleLoader.resolveDynamicImport (/D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:20125:82)
  at async /D:/random/nuxt314-cluster/node_modules/rollup/dist/es/shared/node-entry.js:20013:32



 ERROR  [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/dist/presets/node/runtime/node-server.mjs from node_modules/nitropack/dist/presets/node/runtime/node-cluster.mjs]                                                                              
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/29777
resolves https://github.com/nitrojs/nitro/issues/2846

### 📚 Description

this updates the preset directory for Nitro v2.10+.

## Summary by CodeRabbit

- **New Features**
	- Enhanced import protection rules to exclude the `presets` directory from module imports.

- **Bug Fixes**
	- Improved regex pattern for better handling of module import patterns.

### CODE REVIEW

File: packages/nuxt/src/core/plugins/import-protection.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export const createImportProtectionPatterns = (nuxt: { options: NuxtOptions }, o
     ])
   }
 
-  for (const i of [/(^|node_modules\/)@nuxt\/(kit|test-utils)/, /(^|node_modules\/)nuxi/, /(^|node_modules\/)nitro(?:pack)?(?:-nightly)?(?:$|\/)(?!(?:dist\/)?runtime|types)/, /(^|node_modules\/)nuxt\/(config|kit|schema)/]) {
+  for (const i of [/(^|node_modules\/)@nuxt\/(kit|test-utils)/, /(^|node_modules\/)nuxi/, /(^|node_modules\/)nitro(?:pack)?(?:-nightly)?(?:$|\/)(?!(?:dist\/)?(?:presets|runtime|types))/, /(^|node_modules\/)nuxt\/(config|kit|schema)/]) {
```
Comment (pi0) [inline packages/nuxt/src/core/plugins/import-protection.ts:39]: It would be better if we didn't depend on internal structure (even at cost of less import protection)

Comment (danielroe) [reply packages/nuxt/src/core/plugins/import-protection.ts:39]: perhaps nitro v3 would be a good time to revisit?

Comment (pi0) [reply packages/nuxt/src/core/plugins/import-protection.ts:39]: While there is low chance for v2 to have major changes, internals changes can always happen. I believe we should instead protect only known subpath patterns (`nitropack` / `nitropack/kit` are main ones) + this logic should go into nitro itself for import protection (via unjs package)

Comment (danielroe) [reply packages/nuxt/src/core/plugins/import-protection.ts:39]: let's do it!

**Comment by HigherOrderLogic** [comment]
This doesn't seem to solve the issue completely. See [this action result](https://github.com/HigherOrderLogic/higherorderlogic.github.io/actions/runs/11703318563/job/32593468849).

If needed, I can try to make a minimal reproduction.

**Comment by yschroe** [comment]
Same problem here. I still get `RollupError: [plugin impound] This module cannot be imported in server runtime. [importing node_modules/nitropack/node_modules/crossws/dist/adapters/node.mjs from node_modules/nitropack/dist/presets/_nitro/runtime/nitro-dev.mjs]` in v3.14.159.

Can also work on a minimal repro if needed.

**Comment by they-cloned-me** [comment]
The issue with `cloudflare-preset` #29784 persists, unfortunately. 😞

Don't know if I should re-open it.
