### PR TITLE
fix(nuxt): let router handle internal redirects within middleware

### LINKED ISSUE #15407: Component setup runs before router middleware is resolved
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `vite`, `modules`, `i18n`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.1`
- Build Modules:    `-`
------------------------------

### Reproduction

```js
// middleware/auth.global.js
export default defineNuxtRouteMiddleware(async (to)=> {
  if (process.client) return

  const app = useNuxtApp()
  const event = app.ssrContext.event
  const accessToken = getCookie(event, 'accessToken')
  
  // Authenticate if accessToken exists
  // ...

  const { isLoggedIn } = useUserStore()
  const publicPaths = [
    //.. some public paths not needing authentication
  ]
  if (!publicPaths.includes(to.path) && !isLoggedIn) {
    return navigateTo('/login')
  } else if (publicPaths.includes(to.path) && isLoggedIn) {
    return navigateTo('/')
  } 
})

```
```js
// pages/index.vue
export default defineNuxtComponent({
  async setup() {
    const {data: someData} = await useAsyncData(()=> {
      return $fetch('/api/some_api_auth_required', {
        method: 'get',
        headers: useRequestHeaders(['cookie'])
      })
    })
    return {
      someData
    }
  }
})
```

### Describe the bug

I'm seeing that setup block data fetching is being called before router middleware is resolved.

When I visit '/' without authentication, the page redirects to '/login' like expected.

But, on nuxt server console, I'll see that `'/api/some_api_auth_required'` was called and 
failed because accesstoken doesnt exist (not authenticated).

Is this normal behavior? If so, how w

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #15738: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
### Environment

------------------------------
- Operating System: `Linux`
 - Description:	Ubuntu 20.04.5 LTS
 - Release:	20.04
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `ssr`, `app`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Created an error.vue page [like this](https://nuxt.com/docs/getting-started/error-handling#example)

```
<template>
  <div>
    <div class="container max-w-200">
      <h1>{{ error.message }}</h1>
      There was an error 😱
      <br />
      <button @click="handleError">Clear error</button>
      <br />
      <NuxtLink to="/404"> Trigger another error </NuxtLink>
      <br />
      <NuxtLink to="/"> Navigate home </NuxtLink>
    </div>
  </div>
</template>

<script setup>
const router = useRouter();
const props = defineProps({ error: Object });

if (router.currentRoute.value.fullPath === "/old-slug") {
  await navigateTo("/new-slug", {
    redirectCode: 301,
  });
}

const handleError = () => clearError({ redirect: "/" });
</script>


```

### Describe the bug

When i curl this url :

```
$ curl http://192.168.0.117:3000/old-slug -v
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Access-Control-Allow-Origin: *
< location: /new-slug
< content-type: text/html
< server-timing: -;dur=0;desc="Generate"
< date: Wed, 30 Nov 2022 18:25:24 GMT
< connection: close
< content-length: 95
< 
* Closing connection 0
<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/new-slug"></head></html>
```

**everything works correctly except get this error on server:**

```
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at Object.errorhandler [as onError] (/nuxt3test/nuxt-app/.nuxt/dev/index.mjs:427:20)
    at Server.toNodeHandle (/nuxt3test/nuxt-app/node_modules/h3/dist/index.mjs:752:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/15407, resolves https://github.com/nuxt/nuxt/issues/15738

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When we redirect within middleware, we need to tell vue router not to finish the route navigation or the page will load after all (on server side). This wasn't affecting the response but it was allowing forbidden routes to be hit on server side, and causing some unexplained errors in server logs.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/composables/router.ts [hunk 1]
```diff
@@ -97,8 +98,15 @@ export const navigateTo = (to: RouteLocationRaw | undefined | null, options?: Na
   if (process.server) {
     const nuxtApp = useNuxtApp()
     if (nuxtApp.ssrContext && nuxtApp.ssrContext.event) {
+      // Let vue-router handle internal redirects within middleware
+      // to prevent the navigation happening after response is sent
+      if (isProcessingMiddleware() && !isExternal) {
+        setResponseStatus(options?.redirectCode || 302)
+        return to
```
Comment (pi0) [inline packages/nuxt/src/app/composables/router.ts:105]: Would it properly work with prerendering?

Comment (danielroe) [reply packages/nuxt/src/app/composables/router.ts:105]: It should behave the same as the current behavior.

Comment (danielroe) [reply packages/nuxt/src/app/composables/router.ts:105]: (The below code will still be run, just after the middleware finishes processing.)

Comment (pi0) [reply packages/nuxt/src/app/composables/router.ts:105]: It is returning but i trust you it will 👍🏼

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/app/composables/router.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/app/composables/router.ts:105]: This will call `navigateTo` again:

https://github.com/nuxt/nuxt.js/blob/83a8e1378e565784f3ae18026ca7c36751f384e9/packages/nuxt/src/pages/runtime/plugins/router.ts#L181-L185

**Comment by ydnar** [comment]
This change seems to break route middleware that strips trailing slashes, e.g. `/about/` → `/about`, which match the same destination route. SSR emits status code 301 (or 302), but responds with content and no `Location` header.

**Comment by manniL** [comment]
> This change seems to break route middleware that strips trailing slashes, e.g. `/about/` → `/about`, which match the same destination route. SSR emits status code 301 (or 302), but responds with content and no `Location` header.

Please create a new issue with reproduction then :)
