### PR TITLE
fix(vue-app): fallback to global nuxt instance of `$root` is not available

### LINKED ISSUE #8995: custom components in vuetify-dialog not working
### Versions

- nuxt: v2.15.3
- node: v12.20.2

### Steps to reproduce

Use vuetify-dialog plugin with custom components 

### What is Expected?

components should work in dialogs as they do everywhere else

### What is actually happening?

$nuxt is not accessible because vuetify-dialog uses a seperate Vue instance. Because of this for example fetch is not working. 

### Proposed fix

I fixed it by modifying the $nuxt property in index.js:

```
Object.defineProperty(Vue.prototype, '$nuxt', {
  get() {
    return this.$root.$options.$nuxt || window.$nuxt
  },
  configurable: true
})
```

### PR DESCRIPTION
**Pull request by vcordes79**
## Types of changes
return window.$nuxt if $root is not set
- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
$nuxt was not always accessible (if $root was not set), so return the property from window object

fixes #8995

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by vcordes79** [comment]
fixes #8995

File: packages/vue-app/template/index.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ Vue.component(Nuxt.name, Nuxt)
 
 Object.defineProperty(Vue.prototype, '<%= globals.nuxt %>', {
   get() {
-    return this.$root.$options.<%= globals.nuxt %>
+    return this.$root.$options.<%= globals.nuxt %> || (process.client && typeof window !== 'undefined' && window.<%= globals.nuxt %>)
```
Comment (danielroe) [inline packages/vue-app/template/index.js:49]: I'm worried this will lead to inconsistent behaviour between client/server rendering.

Comment (pi0) [reply packages/vue-app/template/index.js:49]: Indeed we have to double-check this. Check-related issue #8995 is due to usage of the second app by vuetify.

Comment (vcordes79) [reply packages/vue-app/template/index.js:49]: I don't see any inconsistant behaviour between client/server. 

In the server it will be `this.$root.$options.<%= globals.nuxt %>` if it's defined. If it's not defined, it will still be undefined, because window is not defined server side. 

On the client it won't change anything if `$root` exists - only if it does not. Could you please explain, what the prolem is?

Comment (clarkdo) [reply packages/vue-app/template/index.js:49]: It looks OK, but as @pi0 mentioned, let double check, a test for this would be test.

BTW, I think we can split this complex expression into if/else, sth like:

```js
const globalNuxt = this.$root.$options.<%= globals.nuxt %>

if(process.client && !globalNuxt && window) {
  return window.<%= globals.nuxt %>
}

return globalNuxt
```

**Comment by PayelKarmakar06** [comment]
I recently tried upgrading to 2.15.4, but I am still facing $root not available issue.

`Cannot read property '$options' of undefined`
