### PR TITLE
fix(nuxt): apply right types to modules and their runtime files

### LINKED ISSUE #22988: Incorrect types of auto-imports in modules
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      modules, auth, security, typescript, devtools, i18n, postcss, tailwindcss, vue, vite
- Runtime Modules:  nuxt-security@0.14.4, @sidebase/nuxt-auth@0.5.0, @nuxtjs/tailwindcss@6.8.0, nuxt-svgo@3.5.0, @vueuse/nuxt@10.4.1, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xodh6t?file=modules%2Fexample%2Fpages%2Fsomething%2Findex.vue

### Describe the bug

There are missing types from auto-imports, and that the ref, $fetch, or other variables are being inferred as `any` in modules.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kecrily**
### 🔗 Linked issue

close https://github.com/nuxt/nuxt/issues/22988

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Supports auto import in modules, using the `runtime/` directory as a convention. This helps speed up development and maintains auto import consistent with the rest of nuxt.

Based on the discussion, add the following to `tsconfig.json`:

```json
"inclued": [
  "module/runtime"
],
"exclude": [
  "module/runtime/server"
]
```

add the following to `tsconfig.server.json`:

```json
"inclued": [
  "module/runtime/server"
]
```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] (N/A) ~~I have updated the documentation accordingly.~~

### CODE REVIEW

File: packages/kit/src/template.ts [hunk 1]
```diff
@@ -143,10 +143,11 @@ export async function writeTypes (nuxt: Nuxt) {
       ...nuxt.options._layers.map(layer => layer.config.srcDir ?? layer.cwd)
         .filter(srcOrCwd => !srcOrCwd.startsWith(rootDirWithSlash) || srcOrCwd.includes('node_modules'))
         .map(srcOrCwd => join(relative(nuxt.options.buildDir, srcOrCwd), '**/*')),
-      ...nuxt.options.typescript.includeWorkspace && nuxt.options.workspaceDir !== nuxt.options.rootDir ? [join(relative(nuxt.options.buildDir, nuxt.options.workspaceDir), '**/*')] : []
+      ...nuxt.options.typescript.includeWorkspace && nuxt.options.workspaceDir !== nuxt.options.rootDir ? [join(relative(nuxt.options.buildDir, nuxt.options.workspaceDir), '**/*')] : [],
+      ...nuxt.options.modulesDir.map(m => join(relativeWithDot(nuxt.options.buildDir, m), 'runtime'))
     ],
     exclude: [
-      ...nuxt.options.modulesDir.map(m => relativeWithDot(nuxt.options.buildDir, m)),
```
Comment (danielroe) [inline packages/kit/src/template.ts:149]: We probably still need to exclude the root module directory, for example if it is a subfolder of the srcDir, e.g. `~/modules/some-module/mod.ts`

File: packages/kit/src/template.ts [hunk 2]
```diff
@@ -143,10 +143,11 @@ export async function writeTypes (nuxt: Nuxt) {
       ...nuxt.options._layers.map(layer => layer.config.srcDir ?? layer.cwd)
         .filter(srcOrCwd => !srcOrCwd.startsWith(rootDirWithSlash) || srcOrCwd.includes('node_modules'))
         .map(srcOrCwd => join(relative(nuxt.options.buildDir, srcOrCwd), '**/*')),
-      ...nuxt.options.typescript.includeWorkspace && nuxt.options.workspaceDir !== nuxt.options.rootDir ? [join(relative(nuxt.options.buildDir, nuxt.options.workspaceDir), '**/*')] : []
+      ...nuxt.options.typescript.includeWorkspace && nuxt.options.workspaceDir !== nuxt.options.rootDir ? [join(relative(nuxt.options.buildDir, nuxt.options.workspaceDir), '**/*')] : [],
+      ...nuxt.options.modulesDir.map(m => join(relativeWithDot(nuxt.options.buildDir, m), 'runtime'))
```
Comment (danielroe) [inline packages/kit/src/template.ts:147]: modulesDir is actually not a list of modules but of `node_modules` folders. We likely need to iterate over the actual list of modules (e.g. from `nuxt.options._installedModules`?)

File: packages/kit/src/template.ts [hunk 3]
```diff
@@ -113,6 +113,13 @@ export async function writeTypes (nuxt: Nuxt) {
 
   const rootDirWithSlash = withTrailingSlash(nuxt.options.rootDir)
 
+  const modules = nuxt.options._installedModules
+    .filter(m => m.entryPath)
+    .map(m => m.entryPath.startsWith(rootDirWithSlash)
+      ? m.entryPath.split('/index.ts')[0]
+      : rootDirWithSlash + 'node_modules/' + m.entryPath
```
Comment (danielroe) [inline packages/kit/src/template.ts:120]: we might need to resolve the module path with `tryResolveModule` or similar instead - in a monorepo or in non-hoisted pnpm setup we can't necessarily assume that `~/node_modules/<module-name>` is correct.

**Review by danielroe — APPROVED** [review]
