### PR TITLE
fix(nuxt): add overloads for `asyncData` generic + default

### LINKED ISSUE #22164: TypeScript type error in `useFetch` default option with `ResT` generic and `transform` returning `unknown` when making external server requests
### Environment

Node Version: v16.20.0
Nuxt Version: 3.6.2

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xrqqhx?file=composables%2Ftest.ts

### Describe the bug

When using `useFetch` with the `ResT` generic, a TypeScript type error occurs with the `default` option. The error message is as follows:

```ts
useFetch<number[]>('/api/count', {
  default: () => [0]
}
```

```
Type '() => number[]' is not assignable to type '() => Ref<null> | null'.
```

However, the error can be resolved by using the following syntax:

```ts
useFetch<number[]>('/api/count', {
  default: (): number[] => [0]
}
```

But when making requests to an external server, using this syntax causes the `res` parameter in the `transform` function to be of type `unknown` instead of `number[]`. An example of this issue is shown below:

```ts
const { data: data2 } = useFetch('https://reqres.in/api/users?page=2', {
  default: (): number[] => [],
  transform(res){
    return res.map(i => i);
  }
});
```

```
'res' is of type 'unknown'.
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by 94726**
### 🔗 Linked issue

resolves #22164

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds overloads to `useFetch` and `useAsyncData` (+Lazy variants) for handling the correct type of the default function while also changing the type of `data` from `DataT | null` to `DataT` when providing a default.

I tried implementing it without adding even more overloads, but I just couldn't figure it out :/

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
Thank you! Would you mind adding some tests to `test/fixtures/basic-types/types.ts` to cover these changes?

File: test/fixtures/basic-types/types.ts [hunk 1]
```diff
@@ -309,6 +309,22 @@ describe('composables', () => {
...
+    useLazyFetch<string>('/test', { default: () => 0 })
+    // @ts-expect-error default type should match generic type
+    useAsyncData<string>(() => $fetch('/test'), { default: () => 0 })
+    // @ts-expect-error default type should match generic type
+    useLazyAsyncData<string>(() => $fetch('/test'), { default: () => 0 })
+
+    expectTypeOf(useFetch<string>('/test', { default: () => 'test' }).data).toEqualTypeOf<Ref<string>>()
+    expectTypeOf(useLazyFetch<string>('/test', { default: () => 'test' }).data).toEqualTypeOf<Ref<string>>()
+    expectTypeOf(useAsyncData<string>(() => $fetch('/test'), { default: () => 'test' }).data).toEqualTypeOf<Ref<string>>()
+    expectTypeOf(useLazyAsyncData<string>(() => $fetch('/test'), { default: () => 'test' }).data).toEqualTypeOf<Ref<string>>()
```
Comment (danielroe) [inline test/fixtures/basic-types/types.ts:325]: nice. could you also add tests with both default + transform so we verify those still work?

Comment (94726) [reply test/fixtures/basic-types/types.ts:325]: I just noticed that providing a generic parameter results in the `transform` not being able to return a different type.
e. g. this is not possible because `number` isn't assignable to `string`
```ts
useFetch<string>('/test', {default: () => 'test', transform: (arg) => 0})
```
Unfortunately this seems to be a typescript limitation at the moment, see https://github.com/microsoft/TypeScript/issues/14400

---
Should I simply add tests for the case of returning the matching type?

Comment (danielroe) [reply test/fixtures/basic-types/types.ts:325]: As long as it's not a regression in this PR, I'm happy just documenting current behaviour in the tests 👍

Comment (94726) [reply test/fixtures/basic-types/types.ts:325]: Added some more tests and there shouldn't be any regressions :)

**Review by danielroe — APPROVED** [review]
Thank you ❤️

**Comment by qoo1476** [comment]
resolves #21277 too, thanks
