### PR TITLE
fix(cli): disable parallel build behaviour when generating

### LINKED ISSUE #7390: How to fix Nuxt Warning :Starting with Nuxt version 3 this will be a fatal error
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/fpl1104/nuxttest.git](https://github.com/fpl1104/nuxttest.git)

### Steps to reproduce

npx create-nuxt-app ..
...
...
...
Edit nuxt.config.js =>buid:{        cache: true,parallel: true,}

run generate => OK
run generate again =>Nuxt Warning

 
   │                                                                                      
   │   ⚠ Nuxt Warning                                                                     │
   │                                                                                      │
   │   The command 'nuxt generate' finished but did not exit after 5s                     │
   │   This is most likely not caused by a bug in Nuxt.js                                 │
   │   Make sure to cleanup all timers and listeners you or your plugins/modules start.   │
   │   Nuxt.js will now force exit                                                        │
   │                                                                                      │
   │   DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error        │
   │                                                                                      │

### What is expected ?

generate ok & no warning

### What is actually happening?

I get a warning 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10680">#c10680</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by danielroe**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
* prevents leftover timers and listeners after build

closes #7390

## Checklist:

- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/cli/src/commands/generate.js [hunk 1]
```diff
@@ -80,6 +80,9 @@ export default {
 
     // Set flag to keep the prerendering behaviour
     config._legacyGenerate = true
+    if (config.build) {
+      config.build.parallel = false
```
Comment (pi0) [inline packages/cli/src/commands/generate.js:84]: - It would be nice if we can investigate more what is root cause and possibly report/fix in upstream
- It seems a webpack bug (?) but only happening for generate?
- Linking related issue to workaround at least would be nice :)

Comment (danielroe) [reply packages/cli/src/commands/generate.js:84]: Issue only happens when generate includes build step before, like also #7855. Skipping build in full static solves issue.

Comment (pi0) [reply packages/cli/src/commands/generate.js:84]: But only one instance of nuxt initializes webpack right?

Comment (pi0) [reply packages/cli/src/commands/generate.js:85]: Update: Added comments for fast merge still think worth checking rootCause instead of patch in longer term :)
