### PR TITLE
fix: useFetch in middleware that returns undefined gives useAsyncData warning

### LINKED ISSUE #31211: `useFetch` in middleware that returns `undefined` gives `useAsyncData` warning
### Environment

- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.15.4
- CLI Version:      3.21.1
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.4
- Builder:          -
- User Config:      extends, modules, devtools, app, runtimeConfig, future, compatibilityDate, telemetry, eslint
- Runtime Modules:  @nuxt/ui@2.21.0, @nuxt/eslint@1.1.0, @vueuse/nuxt@12.7.0, @nuxt/image@1.9.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-fj7smbt7?file=app.vue

### Describe the bug

Hi,

When a `useFetch` is used in a Nuxt middleware and it returns `undefined` - the wrong `warn` is given:

````
 WARN  [nuxt] useAsyncData must return a value (it should not be undefined) or the request may be duplicated on the client side.
````

### Additional context

_No response_

### Logs

```shell-script

```

### LINKED ISSUE #31259: Wrong warn is given during `useFetch` or `useLazyFetch` execution on the server-side.
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.0`
- Nuxt Version:     `4.0.0-0`
- CLI Version:      `3.22.4`
- Nitro Version:    `-`
- Package Manager:  `pnpm@10.5.2`
- Builder:          `-`
- User Config:      `modules`, `pages`, `dir`, `typescript`
- Runtime Modules:  `()`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-pmvrs6vw?file=app.vue

### Describe the bug

Wrong warn is given during `useFetch` or `useLazyFetch` execution on the server-side.
It was mentioned here https://github.com/nuxt/nuxt/issues/31211 but without fix in useLazyFetch.

### Additional context

_No response_

### Logs

```shell-script
WARN  [nuxt] useAsyncData must return a value (it should not be undefined) or the request may be duplicated on the client side.
```

### PR DESCRIPTION
**Pull request by moshetanzer**
### 🔗 Linked issue
resolves https://github.com/nuxt/nuxt/issues/31211
resolves https://github.com/nuxt/nuxt/issues/31259
closes https://github.com/nuxt/nuxt/pull/31260

### 📚 Description
Should fix above issue not sure what perf cost is

### CODE REVIEW

File: packages/nuxt/src/app/composables/fetch.ts [hunk 1]
```diff
@@ -144,7 +144,7 @@ export function useFetch<
     watch: watch === false ? [] : [_fetchOptions, _request, ...(watch || [])],
   }
 
-  if (import.meta.dev && import.meta.client) {
+  if (import.meta.dev) {
```
Comment (danielroe) [inline packages/nuxt/src/app/composables/fetch.ts:147]: The warning is only triggered on the server so in fact the check should be:

```suggestion
  if (import.meta.dev && import.meta.server) {
```

**Review by danielroe — APPROVED** [review]
