### PR TITLE
fix(nuxt): do not redirect when `vue-router` normalises url

### LINKED ISSUE #14316: Infinite redirect when the url contains ANY "+" character breaking the application
Hi guys, first of all thanks for the amazing job in this awesome tool!

I'm facing an several issue when the user tries to access the Nuxt application (SSR mode) using an url that contains any "+" character, the application apply an endless 302 redirect breaking all the application.

### Versions

- nuxt: [3.0.0-rc.4, 3.0.0-rc.5]
- node: [14.17.1, 16.14.2, 16x (Vercel)]

### Reproduction

Url to test:
https://test-nuxt-error.vercel.app/?asd=1231+

Example repo with the error:
https://github.com/igortrinidad/test-nuxt-error

### Steps to reproduce
Deploy an application on Vercel that contains vue-router (using Nuxt pages), if the application does not contains vue-router it won't happens...

### What is Expected?
The application been served normally

### What is actually happening?
Infinite redirects 302 breaking the application

### I tried
Update the vue-router to the latest version
Create a new installation of Nuxt and deploy it
If the installations doesn't have pages (router...) the error doesn't happens
If the application has pages (what is pretty normal to an web application) the error starts to happens..

### Why

Why i need to access an url that contains the"+" character in my application, im implementing Google auth and the redirect url from the provider come with the "+" character in it which i can't control or sanitize.

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/14316

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

vue router normalises `/?asd=1231%20` to `/?asd=1231+` but this isn't actually a redirect performed by middleware. We can respect `to.redirectedFrom` to tell us whether there's been an _explicit_ redirection rather than just vue-router normalising things for us.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by smaeda-ks — APPROVED** [review]
Confirmed this is working as expected on Vercel deployment 👍 Thank you! 💯

File: packages/nuxt/src/pages/runtime/plugins/router.ts [hunk 1]
```diff
@@ -178,11 +178,10 @@ export default defineNuxtPlugin({
           statusMessage: `Page not found: ${to.fullPath}`
         })])
       } else if (process.server) {
-        const currentURL = to.fullPath || '/'
-        if (!isEqual(currentURL, initialURL, { trailingSlash: true })) {
+        if (to.redirectedFrom) {
```
Comment (pi0) [inline packages/nuxt/src/pages/runtime/plugins/router.ts:181]: Shouldn't we still check if `redirectedFrom` is not duplicate of current route (with/without trailing slash) to avoid loops?

Comment (danielroe) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:181]: Vue router handles that for us. If users do redirect to the same route then we never get to this point. A 500 error is returned from vue-router and this warning is printed in the console:

```
[10:31:52 AM] [Vue Router warn]: Detected an infinite redirection in a navigation guard when going from "/" to "/?test". Aborting to avoid a Stack Overflow. This will break in production if not fixed.
```

Comment (danielroe) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:181]: (I'll add a test.)

Comment (pi0) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:181]: Good to know. Considering there are developers that simply ignore such warnings or situations that ONLY this trailing slash is reproducable in production, does it makes sense that we still either explicitly handle it (also for production) or make an improvement to vue-router to do this for production?

Comment (danielroe) [reply packages/nuxt/src/pages/runtime/plugins/router.ts:181]: It also does it in production.

**Review by pi0 — APPROVED** [review]
LGTM 👍🏼

**Review by pi0 — APPROVED** [review]
