### PR TITLE
fix(nuxt): remove router.replace in HMR to fix top-level await error

### LINKED ISSUE #33275: HMR error when use top level await in page？
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v20.12.1
- Nuxt Version:     4.1.2
- CLI Version:      3.28.0
- Nitro Version:    2.12.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      ssr, compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://codesandbox.io/p/devbox/romantic-dream-gfvxkr?workspaceId=ws_Dd6qoRmec96FvmKpLpdPwh

### Describe the bug

Image

I’m seeing an error when I edit code in a page that uses a top-level await in the <script setup>.
(I’ve attached a screenshot from when the error occurs after changing only a console.log and saving.)

Since this reproduces with a very minimal example, I’m thinking I might be misunderstanding something rather than it being a framework issue. Could you tell me what I’m doing wrong?

### Additional context

```
<script setup lang="ts">
console.log("test1"); // when changed, error below is happened
await new Promise((r) => setTimeout(r, 1000));
</script>

<template>test</template>

```

```
[Vue warn]: Unhandled error during execution of component update 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage > 
  at <NuxtLayoutProvider layoutProps= Object key="default" name="default"  ... > 
  at <NuxtLayout > 
  at <App key=4 > 
  at <NuxtRoot>
```

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js?v=ba41949b:50:30)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?v=ba41949b:5507:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js?v=ba41949b:207:19)
    at ReactiveEffect.runIfDirty (reactivity.esm-bundler.js?v=ba41949b:245:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js?v=ba41949b:197:33)
    at flushJobs (runtime-core.esm-bundler.js?v=ba41949b:405:9)
```

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Flo0806**
### 🔗 Linked issue

 Fixes #33275 #31493

## Summary
~~- Remove `router.replace()` call in route HMR handler that causes errors with top-level await~~
- Replace router.replace() with router.resolve() + Object.assign() in route HMR handler to safely update route meta without triggering navigation

## Problem
When a page uses top-level await (e.g., `await useFetch()`), editing the script section during initial load causes:
Cannot read properties of null (reading 'parentNode')

### Why router.replace() crashed:
  - Triggers a real navigation → Vue Router lifecycle
  - With top-level await: Suspense is pending → DOM doesn't exist yet
  - Vue tries unmount/mount → parentNode is null → crash

## Solution
~~Remove the `router.replace(router.currentRoute.value.fullPath)` line. Query params and route state are preserved without it.~~
Use router.resolve() + Object.assign() instead:
```typescript
  router.isReady().then(() => {
    const newRoute = router.resolve(router.currentRoute.value.fullPath)
    Object.assign(router.currentRoute.value.meta, newRoute.meta)
  })
```

## Testing
- Added E2E Test for top-level await during HMR. Fails without fix.

### CODE REVIEW

**Comment by danielroe** [comment]
we do need to replace the route (as seen in the test failures)

but if the issue is about router being ready, maybe we can move the line or ensure that whatever needs to happens hould happen first?

**Comment by Flo0806** [comment]
~~Yes... I guess I got it... nuxt:hooks are my friends... I try something, update will follow~~
New way: I use the better `router.resolve` + additional `router.ready`  to handle it. Now we have both: Correct page + meta data and we  can handle top level await.

btw: Sorry for the unnecessary merge commit. I wasn't paying attention

File: packages/nuxt/src/pages/module.ts [hunk 1]
```diff
@@ -672,6 +672,12 @@ if (import.meta.hot) {
       for (const route of routes) {
         router.addRoute(route)
       }
+      router.isReady().then(() => {
+        // Resolve the current path against the new routes to get updated meta
+        const newRoute = router.resolve(router.currentRoute.value.fullPath)
+        // Patch meta directly (avoids navigation which causes errors with top-level await)
+        Object.assign(router.currentRoute.value.meta, newRoute.meta)
```
Comment (danielroe) [inline packages/nuxt/src/pages/module.ts:682]: do we also need to unset old values?

Comment (Flo0806) [reply packages/nuxt/src/pages/module.ts:682]: hmm... good point. It won't hurt.

File: packages/nuxt/src/pages/module.ts [hunk 2]
```diff
@@ -672,6 +672,12 @@ if (import.meta.hot) {
       for (const route of routes) {
         router.addRoute(route)
       }
+      router.isReady().then(() => {
+        // Resolve the current path against the new routes to get updated meta
+        const newRoute = router.resolve(router.currentRoute.value.fullPath)
+        // Patch meta directly (avoids navigation which causes errors with top-level await)
```
Comment (danielroe) [inline packages/nuxt/src/pages/module.ts]: can we reproduce in our `hmr.test.ts` fixture to avoid regression in future?

Comment (Flo0806) [reply packages/nuxt/src/pages/module.ts]: I hoped you wouldn't ask about that... I'll try. E2E tests are my final boss.

**Review by danielroe — APPROVED** [review]
