### PR TITLE
fix(webpack): remove `lodash-es` + simplify postcss resolution

### LINKED ISSUE #23644: Switched from bun to pnpm and  builder: 'webpack'
### Environment

Nuxt 3.8.0-28284309.b3d3d7f4 with Nitro 2.6.3                                      
                   

### Reproduction

                                                                                                                            
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Adding @auth/nuxt module... { verifyClientOnEveryRequest: true,                                                                              @auth/nuxt 5:49:16 PM
  guestRedirectTo: '/',
  authenticatedRedirectTo: '/',
  baseUrl: '' }
✔ Added @auth/nuxt module successfully.                                                                                                        @auth/nuxt 
ℹ Using default Tailwind CSS file                                                                                                        nuxt:tailwindcss 

 WARN  Nuxt DevTools only supports Vite mode, module is disabled.                                                                                          5:49:19 PM

ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                                      nuxt:tailwindcss  

 ERROR  Cannot start nuxt:  Maximum call stack size exceeded                                                                                               

### Describe the bug

  at deepmerge (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:100:19)
  at cloneUnlessOtherwiseSpecified (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:34:5)
  at node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:94:23
  at Array.forEach (<anonymous>)
  at mergeObject (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:86:18)
  at deepmerge (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:117:10)
  at cloneUnlessOtherwiseSpecified (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:34:5)
  at node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:94:23
  at Array.forEach (<anonymous>)
  at mergeObject (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:86:18)

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23644

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This removes `lodash-es` which was being called recursively when nuxt/tailwindcss + webpack builder were used together. I think there is no particular reason to keep it when we already have `defu`.

I've also slightly refactored the postcss configuration resolution to make it clearer/simpler. I would appreciate a quick check to make sure I've not missed anything in doing so.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/webpack/src/utils/config.ts [hunk 1]
```diff
@@ -68,5 +68,5 @@ export function fileName (ctx: WebpackConfigContext, key: string) {
 
 export function getWebpackConfig (ctx: WebpackConfigContext): Configuration {
   // Clone deep avoid leaking config between Client and Server
-  return cloneDeep(ctx.config)
+  return defu({}, ctx.config)
```
Comment (pi0) [inline packages/webpack/src/utils/config.ts:71]: Please notice that defu only clones on merge not always. For safer alternative, i would suggest clona (we use it for nitro config too)
