### PR TITLE
fix(nuxt): handle more edge cases with external/custom links

### LINKED ISSUE #27312: Warning will appear when passing an external link to `<NuxtLink>`
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.0-28606556.69430aa2
- CLI Version:      3.11.2-1716385490.bfaf128
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jphpju?file=app.vue

### Describe the bug

1. Start [Reproduction](https://stackblitz.com/edit/nuxt-starter-jphpju?file=app.vue). It includes the following code:
   ```html
   <NuxtLink to="https://nuxt.com/">Nuxt</NuxtLink>
   ```
2. Open the Console panel in DevTools.
3. A warning appears: `[Vue Router warn]: No match found for location with path "https://nuxt.com/"`.

截圖 2024-05-23 凌晨1 29 32

### Additional context

This might be related to this PR: #26522.

### Logs

N/A

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/25532
resolves https://github.com/nuxt/nuxt/issues/27312

### 📚 Description

This handles a few things:

1. improves types for `defineNuxtLink` so it doesn't require specifying `activeClass`, `exactActiveClass`, `prefetchedClass`
2. handles basic resolution of object syntax routes when `external` is passed
3. does not apply trailing slash behaviour to external links

cc: @Mini-ghost

### CODE REVIEW

File: packages/nuxt/src/app/components/nuxt-link.ts [hunk 1]
```diff
@@ -183,7 +189,7 @@ export function defineNuxtLink (options: NuxtLinkOptions) {
       isExactActive: link?.isExactActive ?? computed(() => to.value === router.currentRoute.value.path),
       route: link?.route ?? computed(() => router.resolve(to.value)),
       async navigate () {
-        await navigateTo(href.value, { replace: props.replace, external: props.external })
+        await navigateTo(href.value, { replace: props.replace, external: isExternal.value || hasTarget.value })
       },
     } satisfies ReturnType<typeof useLink> & {
       to: ComputedRef<string | RouteLocationRaw>
```
Comment (Mini-ghost) [inline packages/nuxt/src/app/components/nuxt-link.ts:195]: I apologize for not noticing that this is also present here. 

This revision did not change this part. Would it be strange to modify them together?

```suggestion
      to: ComputedRef<RouteLocationRaw>
```

**Comment by Mini-ghost** [comment]
That's great! I manually tested using external links on `<NuxtLink>` and checked the reactivity of `useNuxtLink`. Everything seems to be working as expected now. 

Thank you!

**Comment by harlan-zw** [comment]
Nice :clap:
