### PR TITLE
fix(config): move `preset` to inner `postcssOptions`

### LINKED ISSUE #19482: Impossible to configure `postcss-preset-env` in Nuxt 2.16
### Environment

System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 AMD EPYC
    Memory: 14.14 GB / 15.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @nuxt/vue-app: ^2.16.2 => 2.16.2 
    nuxt: ^2.16.2 => 2.16.2 

### Reproduction

https://codesandbox.io/p/github/obulat/starter/draft/admiring-goldwasser?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%257D%252C%2522currentSpace%2522%253Anull%252C%2522spacesOrder%2522%253A%255B%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### Describe the bug

It is impossible to configure `postcss-preset-env` in Nuxt 2.16. There is a `preset` property in `nuxt.config`'s `build.postcss.postcssOptions`, but Nuxt does not use it. Instead, it tries to use the old `preset` option in `build.postcss` object.

It seems that #8899 might be touching this functionality, but I'm not sure if it's fixing this issue.

We have tried to update Nuxt from 2.15.8 to 2.16.x in [Openverse](https://github.com/WordPress/openverse), but it breaks the RTL layout because the `preset-env` by default is set not to support CSS logical properties like `margin-inline-start` (they are stage 2 of browser support).

The `postcss.preset` settings from `nuxt.config` are not passed to the `postcss-preset-env` plugin.

Currently, if postcss settings are not set using a file (the deprecated way), `webpack/src/utils` gets 2 objects from `nuxt.config`: `postcssLoaderOptions` (the value of `build.postcss`) and `postcssOptions` (the value of `build.postcss.postcssOptions`). 

`defaultPostcssOptions` sets the `postcss-preset-env` options as `this.postcssLoaderOptions.preset || {}`, but `postcss.preset` was deprecated in Nuxt 2.16. It should be replaced with `this.postcssOptions.preset || {}`.

Also, `PostcssConfig.config()` method returns 
```
return {
        sourceMap: this.cssSourceMap,
        ...postcssLoaderOptions,
        postcssOptions
      }
```
However, `postcssLoaderOptions` is not necessary because its plugins are already copied into `postcssOptions`, and the key is deleted; the `preset` and `order` properties are also deleted in the `config()` function

### Additional context

<details>
<summary>My attempt at passing the preset config to the plugin</summary>

```
diff --git a/packages/webpack/src/utils/postcss.js b/packages/webpack/src/utils/postcss.js
index 68f4fc52d..5b60e6efe 100644
--- a/packages/webpack/src/utils/postcss.js
+++ b/packages/webpack/src/utils/postcss.js
@@ -83,7 +83,7 @@ export default class PostcssConfig {
         'postcss-url': {},
 
         // https://github.com/csstools/postcss-preset-env
-        'postcss-preset-env': this.postcssLoaderOptions.preset || {},
+        'postcss-preset-env': this.postcssOptions.preset || {},
 
         cssnano: dev
           ? false
@@ -199,12 +199,10 @@ export default class PostcssConfig {
         if (!postcssOptions.plugins || isPureObject(postcssOptions.plugins)) {
           postcssOptions.plugins = { ...postcssLoaderOptions.plugins || {}, ...postcssOptions.plugins || {} }
         }
-        delete postcssLoaderOptions.plugins
       }
       if ('order' in postcssLoaderOptions) {
         // Prioritise correct config value
         postcssOptions.order = postcssOptions.order || postcssLoaderOptions.order
-        delete postcssLoaderOptions.order
       }
 
       if (Array.isArray(postcssOptions.plugins)) {
@@ -216,11 +214,9 @@ export default class PostcssConfig {
       }
 
       delete postcssOptions.order
-      delete postcssLoaderOptions.preset
 
       return {
         sourceMap: this.cssSourceMap,
-        ...postcssLoaderOptions,
         postcssOptions
       }
     }

```
</details>

### Logs

_No response_

### PR DESCRIPTION
**Pull request by obulat**
### 🔗 Linked issue

#19482 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #19482. Nuxt 2.16 has updated PostCSS to version 8, and introduced a change into the `nuxt.config` `build.postcss` settings. It did not, however, update the way the defaults are set, which made it impossible to set `preset`.

This PR moves the default `preset` from `build.postcss` to `build.postcss.postcssOptions`. It also adds a test for the default setting, and updates the snapshots.

This PR was extracted from #19495 to make it easier to review.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/webpack/src/utils/postcss.js [hunk 1]
```diff
@@ -210,6 +210,14 @@ export default class PostcssConfig {
       if (Array.isArray(postcssOptions.plugins)) {
         defaults(postcssOptions, this.defaultPostcssOptions)
       } else {
+        if (postcssOptions.preset || postcssLoaderOptions.preset) {
+          postcssOptions.plugins = {
+            ...postcssOptions.plugins || {},
+            'postcss-preset-env': merge({}, postcssOptions.preset || postcssLoaderOptions.preset)
```
Comment (danielroe) [inline packages/webpack/src/utils/postcss.js:216]: it might be worth merging _all_ of them to support legacy modules (e.g. tailwind module) that are still interacting with nuxt config based on the old patterns.

Comment (obulat) [reply packages/webpack/src/utils/postcss.js:216]: Do you mean merging _all_ plugins, @danielroe? The `postcss.plugins` with `postcss.postcssOptions.plugins`? I think that that is done on lines 199...202.

Currently, the type for postcss is set to `postcss?: string[] | boolean | { postcssOptions: PostcssConfiguration | (() => PostcssConfiguration) }`, so it actually disallows the old way of setting the options. Should this type be ignored or updated to include the values that will be deprecated but are still in use?

I tried refactoring a `normalize` function (https://gist.github.com/obulat/4fd4cf28ec816c20e5818a053b15f3c5) to move all the top-level properties (plugins, order, preset) inside the inner `postcssOptions`, prioritizing the values that are already within `postcssOptions`. Would this be useful?

Comment (danielroe) [reply packages/webpack/src/utils/postcss.js:260]: The normalize function sounds great! My primary concern is not to support users explicitly passing in an old format but rather to handle the case where _modules_ set `nuxt.options.build.postcss.plugins` (or similar). This happens after we initially normalise the config.

Comment (obulat) [reply packages/webpack/src/utils/postcss.js]: I didn't know about modules setting plugins :) Do they set it _after_ getting the config using `postcss.config()`? Then this solution will not work. But if they update the build config, and then call `postcss.config` with it, then this `normalize` function should work:

The config gets the outer `postcss` object, and then converts it by moving any top-level `plugins`, `preset` and `order` values to the inner `postcssOptions` object. Thus, the _config object_ that we use to load plugins is `{postcssOptions: {plugins: {}|[], preset: {}, order: {}}`, with _no other top-level properties_ but `postcssOptions`.

I spent a lot of time trying to debug the plugins that `postcss-preset-env` loads. I incorrectly understood the documentation to say, "the higher you set the `stage`, the more plugins will be added", and in fact, it is the opposite. While reading the documentation, I also saw that the default `stage` is already set in `postcss-preset-env` at `2`, so **I removed the default stage option** of `{preset: { stage: 2 }}`  from the settings here (replaced with `{preset: {} }`. Please, let me know if it's better to add it back.

File: packages/webpack/src/utils/postcss.js [hunk 2]
```diff
@@ -79,11 +83,11 @@ export default class PostcssConfig {
           })
         },
 
-        // https://github.com/postcss/postcss-url
+        // https://github.com/csstools/postcss-plugins/plugin-packs/postcss-url
         'postcss-url': {},
 
-        // https://github.com/csstools/postcss-preset-env
-        'postcss-preset-env': this.postcssLoaderOptions.preset || {},
+        // https://github.com/csstools/postcss-plugins/plugin-packs/postcss-preset-env
```
Comment (danielroe) [inline packages/webpack/src/utils/postcss.js:89]:
```suggestion
        // https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env
```

File: packages/webpack/src/utils/postcss.js [hunk 3]
```diff
@@ -79,11 +83,11 @@ export default class PostcssConfig {
           })
         },
 
-        // https://github.com/postcss/postcss-url
+        // https://github.com/csstools/postcss-plugins/plugin-packs/postcss-url
```
Comment (danielroe) [inline packages/webpack/src/utils/postcss.js:86]: I think the old url is still correct:

```suggestion
        // https://github.com/postcss/postcss-url
```

File: packages/webpack/src/utils/postcss.js [hunk 4]
```diff
@@ -141,12 +145,58 @@ export default class PostcssConfig {
...
+    if (postcssOptions.postcssOptions && typeof postcssOptions.postcssOptions === 'function') {
+      consola.warn('Using a Function as `build.postcss.postcssOptions` is not yet supported in Nuxt 2.16.2')
+      return { postcssOptions: {} }
+    }
+    if (!('postcssOptions' in postcssOptions)) {
+      if (Object.keys(postcssOptions).length > 0) {
+        consola.warn('Using the top-level properties in `build.postcss` will be deprecated in Nuxt 3. Please move' +
+          'the settings to `postcss.postcssOptions`')
+      }
+      postcssOptions = { postcssOptions: {} }
```
Comment (danielroe) [inline packages/webpack/src/utils/postcss.js:179]: should this be:
```suggestion
      postcssOptions = { postcssOptions }
```

**Review by danielroe — COMMENTED** [review]
This looks great! ❤️

**Review by danielroe — APPROVED** [review]

**Comment by danielroe** [comment]
Thank you for all your work on this ❤️
