### PR TITLE
fix: enable `allowArbitraryExtensions` by default in generated tsconfig

### LINKED ISSUE #34083: TSError `--allowArbitraryExtensions` is not set when importing components built with `@nuxt/module-builder`
### Environment

|                      |                                                                             |
| -------------------- | --------------------------------------------------------------------------- |
| **Operating system** | `Windows 10.0.26200`                                                        |
| **CPU**              | `12th Gen Intel(R) Core(TM) i5-12600KF (16 cores)`                          |
| **Node.js version**  | `v24.11.0`                                                                  |
| **nuxt/cli version** | `3.31.3`                                                                    |
| **Package manager**  | `pnpm@10.26.1`                                                              |
| **Nuxt version**     | `4.2.2`                                                                     |
| **Nitro version**    | `2.12.9`                                                                    |
| **Builder**          | `vite@7.3.0`                                                                |
| **Config**           | `compatibilityDate`, `css`, `devtools`, `eslint`, `modules`, `routeRules`   |
| **Modules**          | `@nuxt/eslint@1.12.1`, `@nuxt/ui@4.3.0`                                     |

### Reproduction

- https://stackblitz.com/edit/github-je2hykje?file=app%2Futils%2Ftest.ts
- https://github.com/Teages/why-we-need-allow-arbitrary-extensions

### Describe the bug

When importing Vue components that were built using @nuxt/module-builder, the editor throws the following error:

```
Module '@nuxt/ui/components/App.vue' was resolved to 'node_modules/@nuxt/ui/dist/runtime/components/App.d.vue.ts', but '--allowArbitraryExtensions' is not set.(6263)
```

But it's wired that LSP is complain the config but vue-tsc didn't look at it.

### Additional context

- [TSConfig Reference: allowArbitraryExtensions](https://www.typescriptlang.org/tsconfig/#allowArbitraryExtensions)
- https://github.com/vuejs/core/pull/13301
- https://github.com/volarjs/volar.js/pull/277

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Teages**
### 🔗 Linked issue

Resolve #34083

### 📚 Description

The PR enabled `allowArbitraryExtensions` by default in all generated TSConfig, include `tsconfig.app.json`, `tsconfig.server.json`, `tsconfig.node.json`, `tsconfig.shared.json` and the legacy `tsconfig.json`.

### CODE REVIEW

File: packages/kit/src/template.ts [hunk 1]
```diff
@@ -375,6 +375,7 @@ export async function _generateTypes (nuxt: Nuxt): Promise<GenerateTypesReturn>
       moduleDetection: 'force',
       isolatedModules: true,
       verbatimModuleSyntax: true,
+      allowArbitraryExtensions: true,
```
Comment (danielroe) [inline packages/kit/src/template.ts:378]: might we need to do the same for the other type contexts?

Comment (Teages) [reply packages/kit/src/template.ts:378]: Yes, we should add it for all type context, user may indirect import types from such files like `.vue`.

**Review by danielroe — APPROVED** [review]
thank you!
