### PR TITLE
fix(nuxt): cache-bust payloads with build id

### LINKED ISSUE #15427: Adding hashes to the _payload.js files
### Describe the feature

When using a CDN like Cloudflare it's normal to use hashes on .js files in order for the cache to be automatically cleared on redeployment as the file name (and the hash) changes.

Now it's not really possible to do that so it's hard to manage re-deployment as we have to manually clean the cache each time. At least that's what I see from the docs.

It would be nice if Nuxt would generate the payload files with a hash, like this: `_payload.{hash}.js` by default. Or at least an option to specify the file name would be nice to have.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/15427

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This moves payload hashes to a query string and uses the build ID to provide cache-busting capability.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/composables/payload.ts [hunk 1]
```diff
@@ -50,14 +51,14 @@ export function preloadPayload (url: string, opts: LoadPayloadOptions = {}) {
...
-const extension = renderJsonPayloads ? 'json' : 'js'
+const filename = renderJsonPayloads ? '_payload.json' : '_payload.js'
 function _getPayloadURL (url: string, opts: LoadPayloadOptions = {}) {
   const u = new URL(url, 'http://localhost')
   if (u.host !== 'localhost' || hasProtocol(u.pathname, { acceptRelative: true })) {
     throw new Error('Payload URL must not include hostname: ' + url)
   }
-  const hash = opts.hash || (opts.fresh ? Date.now() : '')
-  return joinURL(useRuntimeConfig().app.baseURL, u.pathname, hash ? `_payload.${hash}.${extension}` : `_payload.${extension}`)
+  const hash = opts.hash || (opts.fresh ? Date.now() : (useAppConfig().nuxt as any)?.buildId)
```
Comment (pi0) [inline packages/nuxt/src/app/composables/payload.ts:60]: I haven't tested but this wouldn't affect on domain prerenderin (in runtime) and only append buildId as hash in `prerender` env right?

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/app/composables/payload.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/app/composables/payload.ts:60]: No, this would always add the hash, so that when a pre-rendered payload is re-requested it bypasses browser cache

**Comment by axelerod12** [comment]
Is it possible to include the build ID here as well?https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/core/runtime/nitro/renderer.ts#L434
https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/core/runtime/nitro/renderer.ts#L394

**Comment by danielroe** [comment]
That's a good idea. I'd welcome a PR to do it @axelerod12 🙏
