### PR TITLE
fix(vite): respect `isCustomElement` config for jsx transform

### LINKED ISSUE #19024: add support for configuring @vitejs/plugin-vue-jsx's isCustomElement option
### Describe the feature

there is currently no way to configure `@vitejs/plugin-vue-jsx` via nuxt's config. see this line from `@nuxt/vite-builder` https://github.com/nuxt/nuxt/blob/523b495e1d808c3a1e57e190d73f460ddf3b3d8b/packages/vite/src/client.ts#LL63C23-L63C23

my use case is that i need to pass an `isCustomElement` function to the vue jsx plugin. the jsx plugin needs its own `isCustomElement` function (as well as the usual one you'd pass to the more common vue plugin). without this, i get "Failed to resolve component" warnings logged in the console.

there are two possible approaches to solving this that i see

1. internally pass the same `isCustomElement`  function to both vue and jsx plugins. i can't imagine why you'd ever need them to differ, and this means things would "just work" if you configure it once. however i understand this is a little magical, and may not be paletable to you
2. a simpler option is to add a new config section specifically for the jsx plugin. this could be top-level alongside `vue` like `vueJsx`, or a child key of vue like `vue.jsx`, or whatever makes sense

i am more than happy to work on a PR immediately for this following agreement from maintainers.

thanks!

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by WickyNilliams**
### 🔗 Linked issue

resolves #19024 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds ability to configure `@vitejs/plugin-vue-jsx` via the nuxt config. This config will live at config path `vite.vueJsx`. 

Without this, it is impossible to silence console warnings pertaining to custom elements usage in JSX. However opening up this config is more generally useful for configuring other aspects of `@vitejs/plugin-vue-jsx`.

To simplify the common use case, `vue.comilerOptions.isCustomElement` is used as a smart default for `vite.vueJsx.isCustomElement`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by WickyNilliams** [comment]
i struggled to check whether the docs were ok, since the [instructions for running the docs](https://nuxt.com/docs/community/framework-contribution#set-up-documentation-website-in-local-environment) seem to be incorrect/out of date... they recommend running `yarn` commands, but the repo is configured for `pnpm`. also the `dev` command it asks you to run starts the playground rather than the docs. 

so i'm not sure how to test. but it seems config docs are auto-generated, so perpaps i don't actually need to do anything here anyway? please let me know what's required here :) if nothing, i will cross off the item in the checklist

File: packages/schema/src/types/config.ts [hunk 1]
```diff
@@ -95,10 +96,16 @@ export interface NuxtOptions extends Omit<ConfigSchema, 'builder'> {
 export interface ViteConfig extends ViteUserConfig {
   /**
    * Options passed to @vitejs/plugin-vue
-   * @see https://github.com/vitejs/vite/tree/main/packages/plugin-vue
+   * @see https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue
```
Comment (WickyNilliams) [inline packages/schema/src/types/config.ts:99]: the url here was out of date, so i updated

File: packages/schema/src/config/vite.ts [hunk 2]
```diff
@@ -43,6 +43,11 @@ export default defineUntypedSchema({
         }
       }
     },
+    vueJsx: {
+      isCustomElement: {
+        $resolve: async (val, get) => val ?? (await get('vue')).compilerOptions?.isCustomElement
```
Comment (WickyNilliams) [inline packages/schema/src/config/vite.ts:48]: i wasn't sure if needed the optional chaining here?

Comment (WickyNilliams) [reply packages/schema/src/config/vite.ts]: that makes a lot of sense, thanks

**Review by danielroe — APPROVED** [review]

**Comment by WickyNilliams** [comment]
thank you so much @danielroe! really appreciate all the extra work you put in to get this over the line 🚀
