### PR TITLE
 fix: duplicate style in extractCSS 

### LINKED ISSUE #4173: Repeat the package to style after using CSS module.
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/su1924/nuxt-cssModules](https://github.com/su1924/nuxt-cssModules)

### Steps to reproduce

nuxt2.20
After using cssModules(<style module>) and setting extractCSS: true, CSS packages the files, but it will be repeatedly packaged into style. How do you solve this problem?

### What is expected ?

Package to file only

### What is actually happening?

Packaging to files and pages <style>

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8015">#c8015</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix #4173
1. Set `exportOnlyLocals` for css-loader of cssModules
1. Ignore `vue-style-loader` in server build when extractCSS enabled for avoiding inject duplicate style.
1. Refactor `style-loader` slightly

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/webpack/src/utils/style-loader.js [hunk 1]
```diff
@@ -64,32 +68,25 @@ export default class StyleLoader {
...
 
   css(options) {
-    if (this.isServer && this.extractCSS) {
-      options.exportOnlyLocals = true
-    }
-    return {
-      loader: 'css-loader',
-      options
-    }
+    options.exportOnlyLocals = this.exportOnlyLocals
```
Comment (pi0) [inline packages/webpack/src/utils/style-loader.js]: It would be more better to make options immutable. But there are other parts that need such refactor. So just ignore this comment for this PR :D

**Review by pi0 — APPROVED** [review]
