### PR TITLE
fix(schema): accept single string for `extends`

### LINKED ISSUE #23791: fix: type error on `extends` in v3.8
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-bnn6ap?file=nuxt.config.ts

### Describe the bug

Upgrading to Nuxt 3.8 leads to a type issue for me: the `extends` key in `nuxt.config.ts` seems to not accept an array of strings anymore.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23791

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This fixes a typo in http://github.com/nuxt/nuxt/pull/23782.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/common.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ export default defineUntypedSchema({
    * You can use `github:`, `gh:` `gitlab:` or `bitbucket:`.
    * @see https://github.com/unjs/c12#extending-config-layer-from-remote-sources
    * @see https://github.com/unjs/giget
-   * @type {(string|string|[string, typeof import('c12').SourceOptions?])[]}
+   * @type {string | string[] | [string, typeof import('c12').SourceOptions?]}
```
Comment (danielroe) [inline packages/schema/src/config/common.ts:17]:
```suggestion
   * @type {string | string[] | [string, typeof import('c12').SourceOptions?] | [string, typeof import('c12').SourceOptions?][]}
```

**Review by pi0 — APPROVED** [review]
How i missed it! Thanks!

 (BTW in general, at least for docs we might advice using array even for single extends for consistency IMO)
