### PR TITLE
fix(nuxt): warn when ignoring duplicate island/server component

### LINKED ISSUE #22693: Conflict between `.server` components and `island` components
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pa96dq?file=nuxt.config.ts,components%2FHello.server.vue,components%2FWorld.server.vue,app.vue

### Describe the bug

- Island component have a higher priority when having  a `.server` component from the same name; 
- `.server` components are accessible as remote island.

### Additional context

Found by @danielroe 's comment on https://github.com/nuxt/nuxt/pull/22685#discussion_r1298152870

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue
resolve #22693 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Hi :wave: this pr warns the user when a component is being ignored.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/scan.ts [hunk 1]
```diff
@@ -139,6 +139,8 @@ export async function scanComponents (dirs: ComponentsDir[], srcDir: string): Pr
       // Ignore component if component is already defined (with same mode)
       if (!components.some(c => c.pascalName === component.pascalName && ['all', component.mode].includes(c.mode))) {
         components.push(component)
+      } else {
+        console.warn(`${component.pascalName} is already defined, ${component.filePath} will be ignored.`)
```
Comment (danielroe) [inline packages/nuxt/src/components/scan.ts:143]:
```suggestion
        console.warn(`[nuxt] \`<${component.pascalName}>\` is already defined, so \`~/${relative(srcDir, filePath)}\` will be ignored.`)
```

**Review by danielroe — APPROVED** [review]

**Review by TheAlexLichter — APPROVED** [review]
