### PR TITLE
fix(vite): normalise development ssr app stacktrace

### LINKED ISSUE #33917: Error stack highlights wrong line when an error is thrown in app
### Environment

|                      |                                                   |
| -------------------- | ------------------------------------------------- |
| **Operating system** | `Windows 10.0.22631`                              |
| **CPU**              | `12th Gen Intel(R) Core(TM) i7-12700K (20 cores)` |
| **Node.js version**  | `v22.20.0`                                        |
| **nuxt/cli version** | `3.31.3`                                          |
| **Package manager**  | `pnpm@10.26.0`                                    |
| **Nuxt version**     | `4.2.2`                                           |
| **Nitro version**    | `2.12.9`                                          |
| **Builder**          | `vite@7.3.0`                                      |
| **Config**           | `compatibilityDate`, `devtools`                   |
| **Modules**          | `-`                                               |

### Reproduction

https://stackblitz.com/edit/github-uwac4mps-wtxkeln9?file=app%2Fpages%2Findex.vue

### Describe the bug

Hello! I have found that when any error is thrown (only during SSR), Nuxt highlights an incorrect line in the command line and error page.

In the reproduction, I used `createError()` but I believe it can happen anywhere in the `script` or `template` tags.

Image

Not sure if this is Nuxt-related, though

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #33917

### 📚 Description

This PR fixes stacktraces for errors triggered within the vue application in SSR.
The issue lies in vite which uses an [offset](https://github.com/vitejs/vite/blob/36d936117cfd0ca86586d910188728dd5b1ba81d/packages/vite/src/node/ssr/ssrStacktrace.ts#L5)  and the error coming from nitro which has no offset on the stack traces lines. This offset causes vite's `ssrFixStacktrace` to not be able to correctly get the position of the error from sourcemaps.

Not sure whether this should be fixed within Nuxt or if Vite should provide a way to trigger `ssrFixStacktrace` without offset.

We could also implement an utility to retrieve sourcemap from the vite runner and fix the stacktrace on nuxt's side instead of add an offset and calling `ssrFixStacktrace` from vite.

### CODE REVIEW

File: packages/nitro-server/src/runtime/handlers/renderer.ts [hunk 1]
```diff
@@ -139,6 +151,7 @@ export default defineRenderHandler(async (event): Promise<Partial<RenderResponse
 
     // Use explicitly thrown error in preference to subsequent rendering errors
     const _err = (!ssrError && ssrContext.payload?.error) || error
+    _err.stack = await ssrFixStacktrace(_err.stack)
```
Comment (danielroe) [inline packages/nitro-server/src/runtime/handlers/renderer.ts]: should we only do this in dev mode?

Comment (huang-julien) [reply packages/nitro-server/src/runtime/handlers/renderer.ts]: oops I forgot to wrap it

**Comment by huang-julien** [comment]
@danielroe test are throwing i'll fix it later. 

Do you think we could open a PR to vite to allow calling `ssrFixStacktrace` without it using offset since we're fixing an error outside of the vite-runner ? 
If not should we keep this implementation ? Or should we have an utility to fix stacktraces by retrieving the sourcemap from the vite runner instead of sending the error stracktrace to vite. 
It's more about whether 
- We update the stacktrace to include the offset then call `ssrFixStacktrace` from vite
- Open a PR to vite to allow calling `ssrFixStacktrace` without calculating the offset. This way, we don't need to add manually the offset before calling ssrFixStacktrace from vite
- We get the sourcemap from vite, then fix the stacktrace ourself

**Comment by danielroe** [comment]
the ideal scenario is that we implement this entirely in the vite-builder package (or upstream in vite or vite-node) as it sounds like it is entirely an artifact of the vite node dev server implementation we have

do you think that's possible?

**Comment by huang-julien** [comment]
Just looked at vite-node. The fix should probably done here.
Vite-node could expose it's own `ssrFixStacktrace` as everything needed is already available in `ViteNodeRunner`.

I think i'll try to work on it. Once merged, this PR could get a rework to use the exposed `ssrFixStacktrace` from vite node runner.

**Comment by huang-julien** [comment]
OK so let's add a `ssrFixStacktrace` to `vite-node`. Probably won't be used in Nuxt 5 since nitro's moving to vite plugin but it's nice to fix it for 4.x. I think this could also go in to 3.x
I've reworked the PR to use the PR from vite-node

**Comment by huang-julien** [comment]
@danielroe I can't reproduce the CI failing locally 🤔 . the import for vite node runner should be removed by rollup since it's wrapped with `import.meta.dev`

File: packages/nitro-server/src/runtime/handlers/error.ts [hunk 2]
```diff
@@ -7,11 +7,20 @@ import { useNitroApp, useRuntimeConfig } from 'nitropack/runtime'
 import { isJsonRequest } from '../utils/error'
 import { generateErrorOverlayHTML } from '../utils/dev'
 
+let runner: { ssrFixStacktrace(error: Error): Promise<Error> } | undefined
```
Comment (danielroe) [inline packages/nitro-server/src/runtime/handlers/error.ts]: ideally I would like to fix this without adding anything to the `nitro-server/` package (other than perhaps a hook, if we can't do it any other way) ....

I'm trying to decouple the builders (vite/webpack) and nuxt core from the nitro builder

Comment (huang-julien) [reply packages/nitro-server/src/runtime/handlers/error.ts]: Yes, i've been looking for ways to do it directly within the vite package for a while. I can try continue looking for a better solution

**Comment by huang-julien** [comment]
@danielroe is there a reason we don't allow importing anything from vite-builder in nitro ? I think it should be OK.

**Comment by danielroe** [comment]
it's not a dependency of nitro and it should be conceptually separate - it helps us build good abstractions internally.

**Review by danielroe — APPROVED** [review]
