### PR TITLE
fix(nuxt): use key to force server component re-rendering

### LINKED ISSUE #19884: Islands components not updating in production
### Environment

All 

from Nuxt 3.3.0 to current edge version

### Reproduction

https://stackblitz.com/edit/github-qwz87m?file=package.json,components%2Fislands%2FTest.vue,app.vue,nuxt.config.ts

npm run build 
node .output/server/index.mjs

Click on  `add + 1`

the count is not updated

### Describe the bug

It seems that we have some issues with updating the render of a `NuxtIsland` and `.server` (only) components in production.

It may comes from the usage of `createStaticVNode` ?

The render function is correctly triggered from `NuxtIsland` but DOM nodes are not getting updated

https://github.com/nuxt/nuxt/pull/19605 did not solve this issue

### Additional context
At `setupRenderEffect`, the `nextTree` doesn't have any dom node at `el` in production. In dev mode, the `el` represents a `Fragment` marker `<!--[-->`

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue
resolve https://github.com/nuxt/nuxt/issues/19884

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
hi :wave: 

This PR fix https://github.com/nuxt/nuxt/issues/19884 by wrapping the staticNode within a functionnal component and adding a key to it to force re-render the staticVNode
It also use `NuxtIsland` for `.server` component

### 📝 Checklist and TODO

- [x] I have linked an issue or discussion.
- [x] Implement Tests fixtures for server components re-rendering

### CODE REVIEW

**Comment by huang-julien** [comment]
Before merging this please check https://github.com/nuxt/nuxt/pull/19851#issuecomment-1484244890. This PR introduce another issue on #19851 :/

**Comment by huang-julien** [comment]
https://github.com/nuxt/nuxt/pull/19851 includes this PR

**Comment by huang-julien** [comment]
reopen in case of a minor fix patch

File: packages/nuxt/src/components/runtime/server-component.ts [hunk 1]
```diff
@@ -1,102 +1,15 @@
...
-
-    const res = useAsyncData(
-      `${props.name}:${hashId.value}`,
-      async () => {
-        nuxtApp[pKey] = nuxtApp[pKey] || {}
-        if (!nuxtApp[pKey][hashId.value]) {
-          nuxtApp[pKey][hashId.value] = _fetchComponent().finally(() => {
-            delete nuxtApp[pKey]![hashId.value]
-          })
-        }
```
Comment (danielroe) [inline packages/nuxt/src/components/runtime/server-component.ts:72]: The main reason there was a separate `NuxtServerComponent` component is to allow us to include its content in the payload so we can prefetch it. This isn't ideal as it inflates the payload, but maybe we could instead add the uid into the payload and also add a plugin to prefetch any prerendered server components?

Comment (huang-julien) [reply packages/nuxt/src/components/runtime/server-component.ts:72]: I don't really get why do we need to prefetch it since the HTML part wil be already loaded 🤔 . Did i miss something about it ?

Comment (danielroe) [reply packages/nuxt/src/components/runtime/server-component.ts:72]: I mean, for subsequent navigation. We ideally don't want to click a link and _then_ download html for a server component on another page. Just as we have prefetched the payload in advance, we can prefetch used server components in advance.

Comment (huang-julien) [reply packages/nuxt/src/components/runtime/server-component.ts:72]: i see i'll set back NuxtServerComponent with the fix

**Review by danielroe — APPROVED** [review]
