### PR TITLE
fix(kit): support calling Nuxt 2 modules with module container

### LINKED ISSUE #15507: installModule doesn't work with nuxt 2 modules
### Environment

Operating System: Windows
Node Version: v14.17.1
Nuxt Version: 2.15.8
Nitro Version: -
Package Manager: npm@6.14.13
Builder: nxut2(webpack )
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

The latest version of @nuxt/kit has a problem with @nuxtjs/tailwindcss
problem version : 3.0.0-rc.14

and seems like versions below 3.0.0-rc.14 work properly 

### Describe the bug

npm run dev doesn't work properly 

### Additional context

_No response_

### Logs

```shell
npm run dev doesn't work properly as following below 

i Using default Tailwind CSS file from runtime/tailwind.css                                                                                                                        nuxt:tailwindcss 17:04:00

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                                                                            17:04:00  

  at postcss8Module (node_modules\@nuxt\postcss8\dist\index.js:15:10)
  at installModule (/C:/Users/jun/Desktop/projects/nuxtjs2/node_modules/@nuxtjs/tailwindcss/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (/C:/Users/jun/Desktop/projects/nuxtjs2/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:196:7)
  at async ModuleContainer.normalizedModule (/C:/Users/jun/Desktop/projects/nuxtjs2/node_modules/@nuxtjs/tailwindcss/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #15507

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This calls Nuxt 2 modules with the module container to support kit-defined modules installing non-kit modules

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

File: packages/kit/src/module/install.ts [hunk 1]
```diff
@@ -10,7 +11,12 @@ export async function installModule (moduleToInstall: string | NuxtModule, _inli
   const { nuxtModule, inlineOptions } = await normalizeModule(moduleToInstall, _inlineOptions)
 
   // Call module
-  const res = await nuxtModule(inlineOptions, nuxt) ?? {}
+  const res = (
+    isNuxt2()
+      // @ts-expect-error Nuxt 2 `moduleContainer` is not typed
+      ? await nuxtModule.call(nuxt.moduleContainer, inlineOptions, nuxt)
```
Comment (pi0) [inline packages/kit/src/module/install.ts:17]: (i am not sure about functions binding but i guess we were already bounding utils to this)
