### PR TITLE
fix(nitro): ensure ssr error `statusCode` is a number

### LINKED ISSUE #18992: SSR errors in `error.vue` have string statusCode but client errors are numbers
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ugcjap?file=error.vue

### Describe the bug

Props Error on error page has String type in statusCode after abortNavigation, but must be Number

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by clarkdo**
### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)

### 📚 Description

Fix https://github.com/nuxt/nuxt/issues/18992.

For keeping consistent type on ssr error, statusCode should be number, so this pr is normalizing the string value from the error getting by querystring.

### CODE REVIEW

File: packages/nuxt/src/core/runtime/nitro/renderer.ts [hunk 1]
```diff
@@ -157,6 +157,17 @@ async function getIslandContext (event: H3Event): Promise<NuxtIslandContext> {
   return ctx
 }
 
+const normalizeSsrError = (ssrErrorQuery: ReturnType<typeof getQuery>) => {
```
Comment (clarkdo) [inline packages/nuxt/src/core/runtime/nitro/renderer.ts:160]: The test is failing because the code added extra bundle size, do you want me:

- Reduce the amount of code
  - Remove the new added function and just parse statusCode in defineRenderHandler
- Or modify the threshold

Comment (danielroe) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:160]: Let's try just parsing the statusCode in the render handler 🤞

If that doesn't work, then yes, we can bump the threshold...

Comment (clarkdo) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts]: It seems that 90000 is matching the minimum size of the current bundle, I've moved statusCode casting inline and increase threshold slightly.

Comment (danielroe) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts]: sorry for the pain there - this looks great 👌

**Review by danielroe — APPROVED** [review]
