### PR TITLE
fix(vite): add nitro dev handler after vite proxy middleware

### LINKED ISSUE #34348: Negative regex as target in Vite proxy config does not exclude URLs
### Environment

|                      |                                                                                                                 |
| -------------------- | --------------------------------------------------------------------------------------------------------------- |
| **Operating system** | `Linux 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36` |
| **CPU**              | `Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (8 cores)`                                                            |
| **Node.js version**  | `v20.19.1`                                                                                                      |
| **nuxt/cli version** | `3.33.1`                                                                                                        |
| **Package manager**  | `pnpm@8.15.6`                                                                                                   |
| **Nuxt version**     | `4.3.1`                                                                                                         |
| **Nitro version**    | `2.13.1`                                                                                                        |
| **Builder**          | `vite@7.3.1`                                                                                                    |
| **Config**           | `compatibilityDate`, `vite`                                                                                     |
| **Modules**          | `-`                                                                                                             |

### Reproduction

https://stackblitz.com/edit/github-7veaw6mb?file=nuxt.config.ts,vite.config.ts

### Describe the bug

Using a negative lookahead regex as the Vite proxy target like `['^(?!/foo)']`, requests to the excluded URL (`/foo`) are still proxied. Logging the requests shows that they are going to to `/__skip_vite/foo` but only for the excluded URL. Other URLs are proxied as normal.

### Additional context

The bug:
- does not happen when using Vite directly (try it in the repro repo)
- was introduced in Nuxt v4.2.0 and v3.20.0
- happens independent of the Vite version (I tried v5 to v8)

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by lllomh**
## Description

This pull request fixes #34348 where negative regex patterns in Vite proxy configuration were not properly excluding URLs.

## Problem

When using a negative lookahead regex as the Vite proxy target (e.g., `^(?!/foo)`), URLs that should be excluded from proxying (like `/foo`) were still being proxied in Nuxt v4.2.0 and v3.20.0. This issue did not occur when using Vite directly.

### Root Cause

The bug was in the dev server middleware logic where `req._skip_transform` was being set for all non-Vite routes, regardless of whether they should be proxied:

1. When a URL didn't match any proxy pattern, `isViteRoute` was false
2. The middleware set `req._skip_transform = true` for all such URLs
3. The URL was then modified to `/__skip_vite/...`
4. Vite's proxy middleware re-evaluated the modified URL, which could then unexpectedly match the negative regex pattern (since `/__skip_vite/foo` doesn't start with `/foo`)
5. Result: the request was proxied despite user's exclusion pattern

## Solution

Only set `req._skip_transform` for URLs that should actually be proxied:

```typescript
let isProxyRoute = false
if (!isViteRoute) {
  isProxyRoute = isProxyPath(url)
  isViteRoute ||= isProxyRoute
}

if (isProxyRoute) {
  req._skip_transform = true
}
```
This ensures that URL modification only happens for actual proxy requests, preserving the original URL for negative regex pattern evaluation.

## Testing

- Reproduces the issue from the [StackBlitz example](https://stackblitz.com/edit/github-7veaw6mb?file=nuxt.config.ts,vite.config.ts)
- Verified no TypeScript or linting errors
- The fix maintains backward compatibility with existing proxy configurations

## Checklist

- [x] Code follows the style guidelines
- [x] No console.log or debug code
- [x] Self-review completed
- [x] Comments added for complex logic (if any)
- [x] No breaking changes

Closes #34348

### CODE REVIEW

File: packages/vite/src/plugins/dev-server.ts [hunk 1]
```diff
@@ -162,11 +163,12 @@ export function DevServerPlugin (nuxt: Nuxt): Plugin {
...
           }
           // Check proxy paths
-          isViteRoute ||= isProxyPath(url)
+          isProxyRoute = isProxyPath(url)
+          isViteRoute ||= isProxyRoute
         }
 
         const { req, res } = 'runtime' in event ? event.runtime!.node! : event.node
-        if (!isViteRoute) {
+        if (isProxyRoute) {
```
Comment (danielroe) [inline packages/vite/src/plugins/dev-server.ts]: as I understand it, we simply need to avoid changing the url for proxy paths, which we could do with another private property on the req, and then in L78, we test for that private property.

as the PR is currently written, vite will transform paths that should instead be handled by nitro, which is why the tests are all failing

Comment (lllomh) [reply packages/vite/src/plugins/dev-server.ts]: The test-fixtures (windows-latest, built, vite-env-api, ...) failure is a pre-existing flaky test in suspense.test.ts about rapid navigation race conditions, unrelated to this PR's changes (which only modify the Vite dev server middleware). The test fails due to Windows CI timing variance, not proxy routing logic.

Comment (danielroe) [reply packages/vite/src/plugins/dev-server.ts]: thank you for updating!

**Review by danielroe — APPROVED** [review]
