### PR TITLE
fix(schema): add direnv and vendor to default ignore

### LINKED ISSUE #30756: Ignoring certain folders seems not to work
### Environment

```
Working directory: /home/PUZZLE-IT/joop/dev/repro-nuxt-permission-issue                                                          nuxi 8:51:52 PM
Nuxt project info: (copied to clipboard)                                                                                         nuxi 8:51:52 PM
/
------------------------------
- Operating System: Linux
- Node Version:     v22.12.0
- Nuxt Version:     3.15.3
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

```

### Reproduction

A reproduction in Stackblitz doesn't work because you can't use `chmod` and `chown` in there.
I have a git repo with a README.md which guides you through the steps, basically: clone, chmod, chown, pnpm i, pnpm dev

### Describe the bug

Looks like #30459 hasn't been resolved.

### Additional context

_No response_

### Logs

```shell-script
Zie the README.md in the repro repo for the logs
```

### LINKED ISSUE #31575: EMFILE Error During Development with Nuxt Devtools (3.16 - 3.16.1) - Too Many Open Files
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v23.10.0
- Nuxt Version:     3.16.1
- CLI Version:      3.23.1
- Nitro Version:    2.11.7
- Package Manager:  bun@1.2.6
- Builder:          -
- User Config:      future, srcDir, devtools, vite, ssr, typescript, imports, modules, shadcn, tailwindcss, runtimeConfig, compatibilityDate
- Runtime Modules:  @vueuse/motion/nuxt@3.0.3, @nuxtjs/tailwindcss@6.13.2, @nuxt/test-utils/module@3.17.2, @vueuse/nuxt@13.0.0, @nuxtjs/device@3.2.4, shadcn-nuxt@1.0.3, nuxt-icon@0.6.10, @pinia/nuxt@0.10.1, @nuxt/fonts@0.11.0, @formkit/auto-animate@0.8.2, nuxt-toast@1.1.4
- Build Modules:    -
------------------------------

### Reproduction

Install a new nuxt project
Install laravel together with nuxt project
change nuxt.config.ts srcDir to 'client' instead of 'app'
composer install to generate vendor folder
bun install to generate node_modules

then nuxt start

### Describe the bug

I'm encountering an EMFILE: too many open files, watch error when running my Nuxt 3 project in development mode with Nuxt Devtools enabled. This issue appears to have started with version 3.16 and persists in 3.16.1.

### Additional context

After further investigation, vendor folder seems like the culprit. Deleting the vendor folder entirely fixes the problem for me.

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by onmax**
Closes #31575
Closes #30756

## Summary
Add `.direnv` and `/vendor` to default ignore patterns to prevent EMFILE errors from file watchers.

| Directory | Used by | Why many files |
|-----------|---------|----------------|
| `.direnv` | [direnv](https://direnv.net/) (popular in Nix/NixOS) | Cached environment files |
| `vendor` | PHP/Composer, Go modules | Dependencies (like node_modules) |

**Note**: Uses `/vendor` (not `vendor`) to match only root-level vendor directory, preserving `server/utils/vendor/` etc.

## Why `vite.server.watch.ignored` Doesn't Work

Users tried `vite: { server: { watch: { ignored: ['vendor'] } } }` but still got EMFILE errors.

**Root cause**: Nuxt has 5+ independent file watchers:

| Watcher | Uses `nuxt.options.ignore`? |
|---------|---------------------------|
| Nuxt builder (chokidar) | ✅ via `createIsIgnored()` |
| Nuxt builder (parcel) | ✅ directly |
| Vite dev server | ✅ (merged with Nuxt's defaults) |
| Nitro internal | Partial |
| Schema watcher | ❌ hardcoded |

`vite.server.watch.ignored` only affects Vite's watcher. The **canonical solution** is `nuxt.options.ignore` which is used by most watchers via `createIsIgnored()`.

Adding `/vendor` and `.direnv` to **defaults** ensures all watchers respect them automatically.

## StackBlitz

| | Link | Expected |
|---|---|---|
| Bug | [nuxt-31575](https://stackblitz.com/github/onmax/repros/tree/repro/nuxt-31575/nuxt-31575?startScript=dev) | ❌ EMFILE error |
| Fix | [nuxt-31575-fix](https://stackblitz.com/github/onmax/repros/tree/repro/nuxt-31575/nuxt-31575-fix?startScript=dev) | ✅ Dev starts |

## CLI Reproduction

```bash
git clone --depth 1 --filter=blob:none --sparse --branch repro/nuxt-31575 https://github.com/onmax/repros.git
cd repros && git sparse-checkout set nuxt-31575
cd nuxt-31575 && pnpm i && pnpm dev
```

## Verify fix

```bash
git sparse-checkout add nuxt-31575-fix
cd ../nuxt-31575-fix && pnpm i && pnpm dev
```

The `-fix` folder uses [pnpm patch](https://pnpm.io/cli/patch) to apply the fix locally.

### CODE REVIEW

File: packages/schema/src/config/common.ts [hunk 1]
```diff
@@ -228,7 +228,8 @@ export default defineResolvers({
         '**/*.{spec,test}.{js,cts,mts,ts,jsx,tsx}', // ignore tests
         '**/*.d.{cts,mts,ts}', // ignore type declarations
         '**/*.d.vue.{cts,mts,ts}',
-        '**/.{pnpm-store,vercel,netlify,output,git,cache,data}',
+        '**/.{pnpm-store,vercel,netlify,output,git,cache,data,direnv}',
+        '/vendor',
```
Comment (danielroe) [inline packages/schema/src/config/common.ts:232]: should this be:

```suggestion
        'vendor',
```

Comment (onmax) [reply packages/schema/src/config/common.ts:232]: I used `/vendor` intentionally to preserve nested vendor dirs (e.g., `server/utils/vendor/`). Should we ignore all `vendor` dirs instead?"

Comment (danielroe) [reply packages/schema/src/config/common.ts:232]: you're right, it should just be the top level dir

**Review by danielroe — APPROVED** [review]
