### PR TITLE
fix(nuxt): include plugin templates in `plugins.d.ts` if they will be written

### LINKED ISSUE #22617: Plugin created from a template doesn't get registered into `plugins.d.ts`
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:    ` v16.20.0`
- Nuxt Version:    `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `./modules/hello.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-avmg3e

Run: `nuxi prepare`

### Describe the bug

Starting from nuxt `3.5.0`, plugins created by template (`addPluginTemplate` / `addTemplate` -> `addPlugin`) don't get registered to `.nuxt/types/plugins.d.ts` when generated inside the `.nuxt` folder.

As we can see from the reproduction repo, the `InjectionType<typeof import("../plugins/hello").default>` is missing from the `plugins.d.ts`.

It causes the `useNuxtApp().$hello` type to be `unknown`.

### Additional context

If we generate the template outside the `.nuxt` folder, it requires running `nuxi prepare` **at least twice** to make it registered to `.nuxt/types/plugins.d.ts`.

Reproduction: https://stackblitz.com/edit/nuxt-starter-9mc6yi

### Logs

_No response_

### PR DESCRIPTION
**Pull request by nasrob**
### 🔗 Linked issue

#22617

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #22617

### 📝 Checklist

- [X] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/templates.ts [hunk 1]
```diff
@@ -103,7 +103,7 @@ export const pluginsDeclaration: NuxtTemplate<TemplateContext> = {
   getContents: (ctx) => {
     const EXTENSION_RE = new RegExp(`(?<=\\w)(${ctx.nuxt.options.extensions.map(e => escapeRE(e)).join('|')})$`, 'g')
     const tsImports = ctx.app.plugins
-      .filter(p => !isAbsolute(p.src) || existsSync(p.src) || existsSync(p.src.replace(EXTENSION_RE, '.d.ts')))
+      .filter(p => !isAbsolute(p.src) || existsSync(p.src) || (p.src.includes('.d.ts') && existsSync(p.src.replace(EXTENSION_RE, '.d.ts'))))
```
Comment (danielroe) [inline packages/nuxt/src/core/templates.ts:106]: this doesn't look quite right to me...

can you provide an example?

Comment (nasrob) [reply packages/nuxt/src/core/templates.ts:106]: Do you have any suggestions, please?

Here is a branch with a plugin example in the playground : 

https://github.com/nasrob/nuxt/tree/fix/22617-demo/playground/plugins

It prints the message using the plugin, as shown in the screenshot. However, I get this message
`'__VLS_ctx.$hello' is of type 'unknown'.ts(18046)` in the `template` of `app.vue`

Capture d’écran 2023-10-26 à 23 29 45

Comment (danielroe) [inline packages/nuxt/src/core/templates.ts:106]:
```suggestion
      .filter(p => !isAbsolute(p.src)  || ctx.app.templates.some(t => t.dst === p.src && t.write) || existsSync(p.src) || existsSync(p.src.replace(EXTENSION_RE, '.d.ts')))
```
