### PR TITLE
fix(utils): remove optional params in routes ending with `index`

### LINKED ISSUE #5874: Unable to create a dynamic route with required parameter by following the guide
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[n/a](n/a)

### Steps to reproduce

Create following file/directory structure:
```
/pages/test1/_param1.vue
/pages/test2/_param2/index.vue
```

### What is expected ?

Routes to be generated as:
```
/test1/:param1?
/test2/:param2
```

### What is actually happening?

Routes are generated as:
```
/test1/:param1?
/test2/:param2?
```

### Additional comments?

The [guide](https://nuxtjs.org/guide/routing/#dynamic-routes) says:
> As you can see the route named `users-id` has the path `:id?` which makes it optional, if you want to make it required, create an `index.vue` file in the `users/_id` directory instead.

Following this advice (test2) results the parameter still being optional.

The test related to this functionality (https://github.com/nuxt/nuxt.js/blob/2fabea9402864828fe9aafe8b0d13bcc674a1b3b/packages/utils/test/route.test.js#L174) seems to cover only cases where the parameter is defined in a filename, eg being the very last node.

I believe that any parameters specified as directories should be treated as required, so it would be possible to have full control over whether a route parameter is required or optional without resorting to any workarounds.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9312">#c9312</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by farnabaz**
Make sure the last param of routes that end with `index` is non-optional

fix #5874

## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/utils/src/route.js [hunk 1]
```diff
@@ -57,6 +57,9 @@ function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-',
   routes.forEach((route) => {
     route.path = isChild ? route.path.replace('/', '') : route.path
     if (route.path.includes('?')) {
+      if (route.name.endsWith('-index')) {
```
Comment (pi0) [inline packages/utils/src/route.js:60]: We may use `routeNameSplitter` :)

**Comment by pi0** [comment]
@farnabaz Would you please also resolve merge conflict?

**Review by pi0 — APPROVED** [review]
