### PR TITLE
fix: exit with proper error code on errors

### LINKED ISSUE #4718: nuxt build error exits with code 0
### Version

[edge](https://github.com/nuxt.js/releases/tag/edge)

### Reproduction link

[https://github.com/sh/nuxt-build-error-should-exit](https://github.com/sh/nuxt-build-error-should-exit)

### Steps to reproduce

1. `npm run build` in the sample repo (or any repo that throws a build error)
2. 
```
ERROR  Nuxt Build Error                                                                                                                                                                             09:35:12

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack-edge/dist/webpack.js:5213:15)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

3. `echo $?` returns 0

### What is expected ?

A failing build should exit with status > 0

### What is actually happening?

Build fails, logs error and exits with status code 0

### Additional comments?

We're building a docker image in our CI/CD pipeline, the image was built successfully although the build logged an error but did exit with status 0 (all good)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8433">#c8433</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves #4718

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: distributions/nuxt-legacy/bin/nuxt-legacy.js [hunk 1]
```diff
@@ -24,3 +24,6 @@ require('@babel/register')({
 
 const suffix = require('../package.json').name.includes('-edge') ? '-edge' : ''
 require('@nuxt/cli' + suffix).run()
+  .catch((error) => {
+    require('consola').fatal(error)
```
Comment (pi0) [inline distributions/nuxt-legacy/bin/nuxt-legacy.js]: The error may be thrown before registering reporter that handles `fatal`. I suggest explicitly calling `process.exit(2)` after fatal error.

Comment (aldarund) [reply distributions/nuxt-legacy/bin/nuxt-legacy.js]: ye, indeed while it would be rare it could in theory happen

**Review by pi0 — APPROVED** [review]
