### PR TITLE
fix(nuxt): exclude head runtime from unhead imports transform

### LINKED ISSUE #34149: v4.3.0: Bun/pnpm - Maximum call stack size exceeded on composibles.js 31:44
### Environment

|                      |                                                             |
| -------------------- | ----------------------------------------------------------- |
| **Operating system** | `Windows 10.0.26200`                                        |
| **CPU**              | `AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 cores)` |
| **Node.js version**  | `v24.12.0`                                                  |
| **nuxt/cli version** | `3.32.0`                                                    |
| **Package manager**  | `bun@1.3.5`                                                 |
| **Nuxt version**     | `4.3.0`                                                     |
| **Nitro version**    | `2.13.1`                                                    |
| **Builder**          | `vite@7.3.1`                                                |
| **Config**           | `compatibilityDate`, `devtools`                             |
| **Modules**          | `-`                                                         |

### Reproduction

Just create the project with bun on minimal template and try to run dev and render the page (with modules or not)
_**Bun only** Node looks working fine_

### Describe the bug

The page doesn't load, returning a server error (500) with an error of not found (404) on the terminal.

Looks like is a problem with the useHead and something on try throw error:

On page:

Maximun call stack size exceeded
```JS
RangeError {


  stack: 'Maximum call stack size exceeded\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:44)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)\n' +
  'at useHead (C:/Users/gabri/Documents/programming/js/loko-tasks/node_modules/nuxt/dist/head/runtime/composables.js:31:43)'... 242 more characters,
  message: 'Maximum call stack size exceeded',
}
```

On terminal:
```bash
 ERROR  [request error] [unhandled] [GET] http://localhost:3000/_nuxt/                                        16:57:25


ℹ Error:

 ⁃ at createError (C:/Users/gabri/documents/programming/js/loko-tasks/node_modules/@nuxt/cli/dist/dev-KB30iboK.mjs:54:14)

   49 ┃         }
   50 ┃  };
   51 ┃  function createError(input) {
   52 ┃         if (typeof input === "string") return new H3Error(input);
   53 ┃         if (isError(input)) return input;
 ❯ 54 ┃         const err = new H3Error(input.message ?? input.statusMessage ?? "", { cause: input.cause || input });
   55 ┃         if (hasProp(input, "stack")) try {
   56 ┃                 Object.defineProperty(err, "stack", { get() {
   57 ┃                         return input.stack;
   58 ┃                 } });
   59 ┃         } catch {

 ⁃ at NuxtDevServer.toNodeHandle (C:/Users/gabri/documents/programming/js/loko-tasks/node_modules/@nuxt/cli/dist/dev-KB30iboK.mjs:264:18)
 ⁃ at runNextTicks (node:internal/process/task_queues:64:5)
 ⁃ at process.processImmediate (node:internal/timers:472:9)

[CAUSE]
{
  status: 404,
}
```

The page even needs to be modified, and if done, nothing changes, keep the error

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by onmax**
Closes #34149

## Summary

`UnheadImportsPlugin` was transforming Nuxt's own `head/runtime/composables.js`, rewriting `@unhead/vue` imports to `#app/composables/head` which re-exports from `#unhead/composables` (same file) → infinite recursion causing `Maximum call stack size exceeded`.

The existing `distDir` exclusion used path prefix matching that fails with pnpm/bun symlinks. Added explicit regex pattern to exclude `node_modules/nuxt/dist/head/runtime/`.

## StackBlitz

| | Link | Expected |
|---|---|---|
| Bug | [nuxt-34149](https://stackblitz.com/github/onmax/repros/tree/repro/nuxt-34149/nuxt-34149?startScript=dev) | ❌ Stack overflow (may not reproduce on all systems) |
| Fix | [nuxt-34149-fix](https://stackblitz.com/github/onmax/repros/tree/repro/nuxt-34149/nuxt-34149-fix?startScript=dev) | ✅ Page renders |

## CLI Reproduction

```bash
git clone --depth 1 --filter=blob:none --sparse --branch repro/nuxt-34149 https://github.com/onmax/repros.git
cd repros && git sparse-checkout set nuxt-34149
cd nuxt-34149 && pnpm i && pnpm dev
```

## Verify fix

```bash
git sparse-checkout add nuxt-34149-fix
cd ../nuxt-34149-fix && pnpm i && pnpm dev
```

The `-fix` folder uses [pnpm patch](https://pnpm.io/cli/patch) to apply the fix locally.

### CODE REVIEW

File: packages/nuxt/src/head/plugins/unhead-imports.ts [hunk 1]
```diff
@@ -15,6 +15,7 @@ interface UnheadImportsPluginOptions {
 }
 
 const UNHEAD_LIB_RE = /node_modules[/\\](?:@unhead[/\\][^/\\]+|unhead)[/\\]/
+const NUXT_HEAD_RE = /node_modules[/\\]nuxt[/\\]dist[/\\]head[/\\]runtime[/\\]/
```
Comment (danielroe) [inline packages/nuxt/src/head/plugins/unhead-imports.ts:18]: it looks good to me, but what if it's more deeply nested? do we need this to be more permissive?

Comment (onmax) [reply packages/nuxt/src/head/plugins/unhead-imports.ts:18]: The regex uses `.test()` which finds the pattern anywhere in the string, so it handles deeply nested paths:

- pnpm: `/node_modules/.pnpm/nuxt@3.x/node_modules/nuxt/dist/head/runtime/...`
- bun/yarn: `/node_modules/.store/nuxt-virtual-xxx/node_modules/nuxt/dist/head/runtime/...`
- nested within runtime: `runtime/plugins/nested/deep.js`

No anchors (`^` or `$`) in the regex, so any path containing `node_modules/nuxt/dist/head/runtime/` will match regardless of prefix depth.

**Review by danielroe — APPROVED** [review]
