### PR TITLE
fix(nuxt): support custom route name meta with `typedPages`

### LINKED ISSUE #21637: [TYPED ROUTER] - Custom route name through definePageMeta are ignored on generated routes types
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ufaubc?file=test.ts

### Describe the bug

Using the new experimental typed router,  when overriding a route name through `definePageMeta`, the new route name should be taken into account when generating routes types at build-time.

Example : 

```ts
// ROUTE: index.vue
definePageMeta({
  name: 'home'
})
```

Expected generated route name type : `home`
Currently generated : `index`

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by ChronicStone**
### 🔗 Linked issue

#21637 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #21637 by parsing at build-time definePageMeta on routes & extracting custom route name

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/pages/utils.ts [hunk 1]
```diff
@@ -63,6 +64,12 @@ export function generateRoutesFromFiles (files: string[], pagesDir: string): Nux
       children: []
     }
 
+    const fileContent = fs.readFileSync(resolve(pagesDir, file), 'utf-8')
```
Comment (danielroe) [inline packages/nuxt/src/pages/utils.ts:67]: We should also support reading from virtual fs (accessible from `nuxt.vfs`).

File: packages/nuxt/src/pages/utils.ts [hunk 2]
```diff
@@ -94,6 +101,12 @@ export function generateRoutesFromFiles (files: string[], pagesDir: string): Nux
   return prepareRoutes(routes)
 }
 
+function getRouteName (file: string) {
+  const regExp = /definePageMeta\(\s*{[^}]*name:\s*(["'`])((?:[^"'`\\]|\\.)+?)\1/g
+  const match = regExp.exec(file)
```
Comment (danielroe) [inline packages/nuxt/src/pages/utils.ts:106]: slightly better perf to hoist regexp out of function, and I think also we don't want it to be global.

```suggestion
const PAGE_META_NAME_RE = /definePageMeta\(\s*{[^}]*name:\s*(["'`])((?:[^"'`\\]|\\.)+?)\1/
function getRouteName (file: string) {
  const match = PAGE_META_NAME_RE.exec(file)
```

Comment (danielroe) [reply packages/nuxt/src/pages/utils.ts:106]: Having said that, I do have questions about whether this might yield false positives - I'll need to do some testing

File: packages/nuxt/src/pages/utils.ts (hunk 1 above)
Comment (ChronicStone) [reply packages/nuxt/src/pages/utils.ts]: Not 100% sure I got it right but this has been added as well

File: packages/nuxt/src/pages/utils.ts [hunk 3]
```diff
@@ -94,6 +101,12 @@ export function generateRoutesFromFiles (files: string[], pagesDir: string): Nux
   return prepareRoutes(routes)
 }
 
+const PAGE_META_NAME_RE = /definePageMeta\(\s*{[^}]*name:\s*(["'`])((?:[^"'`\\]|\\.)+?)\1/
```
Comment (danielroe) [inline packages/nuxt/src/pages/utils.ts:104]: I think this is too permissive.

For example, this matches:

```ts
definePageMeta({
 something: () => ({ name: 'test' })
})
```

I think we probably would need to parse the file.

**Comment by ChronicStone** [comment]
Following @danielroe feedback, the route name resolver now uses estree parser to extract value from AST

**Comment by ChronicStone** [comment]
Updated with your latest advice @danielroe. Now AST parsing happens only if definePageMeta is defined, and happen only on the definePageMeta portion of code to minimize AST parsing.

**Comment by danielroe** [comment]
Would you mind taking a look at the failing CI?

**Comment by ChronicStone** [comment]
@danielroe Yep, I planned to have a look tomorrow

**Comment by ChronicStone** [comment]
@danielroe  Failing CI issue solved, unit tests now work properly with new implementation of `generateRoutesFromFiles`. 

Also new unit test implemented to cover route name override

**Comment by ChronicStone** [comment]
@danielroe Sorry to mention, I know it isn't ideal, but the new error on CI seems to be related to commits from main being merged to local branch.

Considering the mature of the issue, I'm a bit confused on how I sould proceed to fix this.

`packages/schema/src/types/config.ts:141`

image

**Comment by danielroe** [comment]
The CI error is because you haven't added all the dependencies you're using to the package.json dependencies, and they are being inlined in the package output.

**Review by danielroe — APPROVED** [review]
