### PR TITLE
fix(nuxt): use name to index route providers in dev

### LINKED ISSUE #31446: hmr error TypeError: parentComponent.ctx.deactivate is not a function
### Environment

latest
chrome 134

### Reproduction

https://stackblitz.com/edit/nuxt-starter-pqimgjtz?file=pages%2Findex.vue

### Describe the bug

Image

nuxt 3.16.0,   I modified the index.vue and encountered an error triggering hot-reload.   using keepalive.

### Additional context

_No response_

### Logs

```shell-script
TypeError: parentComponent.ctx.deactivate is not a function
    at unmount (runtime-core.esm-bun…?v=1bf3769f:5847:27)
    at patch (runtime-core.esm-bun…s?v=1bf3769f:4673:7)
    at sharedContext.activate (runtime-core.esm-bun…s?v=1bf3769f:2592:7)
    at processComponent (runtime-core.esm-bun…?v=1bf3769f:5198:29)
    at patch (runtime-core.esm-bun…?v=1bf3769f:4722:11)
    at patchSuspense (runtime-core.esm-bun…s?v=1bf3769f:6961:9)
    at Object.process (runtime-core.esm-bun…s?v=1bf3769f:6797:7)
    at patch (runtime-core.esm-bun…?v=1bf3769f:4747:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bun…s?v=1bf3769f:5430:9)
    at ReactiveEffect.run (reactivity.esm-bundl…s?v=1bf3769f:198:19)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/31446

### 📚 Description

as proposed by @Mini-ghost, this uses the route name to index the route providers in development.

I've also moved the map out of the component setup function as the route provider component is only unique by name, and we also now only use it in the browser to avoid any memory issues on the server

### CODE REVIEW

File: packages/nuxt/src/pages/runtime/page.ts [hunk 1]
```diff
@@ -191,11 +191,14 @@ export default defineComponent({
...
-                let PageRouteProvider = routerProviderLookup.get(routerComponentType)
+                const routeProviderKey = import.meta.dev ? routerComponentType.name || routerComponentType.__name : routerComponentType
+                let PageRouteProvider = import.meta.client ? _routeProviders.get(routeProviderKey) : undefined
 
                 if (!PageRouteProvider) {
                   PageRouteProvider = defineRouteProvider(routerComponentType.name || routerComponentType.__name)
-                  routerProviderLookup.set(routerComponentType, PageRouteProvider)
+                  if (import.meta.client) {
+                    _routeProviders.set(routeProviderKey, PageRouteProvider)
+                  }
```
Comment (Mini-ghost) [inline packages/nuxt/src/pages/runtime/page.ts:201]: There will only run on the client side, would it be okay if we omitted this check?

File: packages/nuxt/src/pages/runtime/page.ts [hunk 2]
```diff
@@ -31,6 +31,8 @@ export interface NuxtPageProps extends RouterViewProps {
   pageKey?: string | ((route: RouteLocationNormalizedLoaded) => string)
 }
 
+const _routeProviders = import.meta.dev ? new Map<Component, ReturnType<typeof defineRouteProvider> | undefined>() : new WeakMap<Component, ReturnType<typeof defineRouteProvider> | undefined>()
```
Comment (Mini-ghost) [inline packages/nuxt/src/pages/runtime/page.ts:34]: Would it perhaps be better to use a string as the key type?

```ts
const _routeProviders = import.meta.dev 
  ? new Map<string, ReturnType<typeof defineRouteProvider> | undefined>() 
  : new WeakMap<Component, ReturnType<typeof defineRouteProvider> | undefined>()
```
