### PR TITLE
fix: use options.server values port, host, socket

### LINKED ISSUE #3941: host and port is not able to configure from nuxt.config.json
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://gitlab.com/hosweetim/timx-site/blob/master/nuxt.config.js](https://gitlab.com/hosweetim/timx-site/blob/master/nuxt.config.js)

### Steps to reproduce

add the server object

```
server: {
        port: 8080,
        host: '0.0.0.0'
},
```

and run `npm start`

### What is expected ?

The port and host should be configured based on the `nuxt.config.json`

### What is actually happening?

Default value of host and port is used

### Additional comments?

Follow this step to configure host and port
 `Configure in nuxt.config.json` https://nuxtjs.org/faq/host-port

But when I run `npm start`, it is still using the default port and host

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7803">#c7803</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by aldarund**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves : #3941

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Atinux** [comment]
Thank you @aldarund, waiting for CI to merge

**Review by galvez — APPROVED** [review]

File: lib/core/nuxt.js [hunk 1]
```diff
@@ -142,7 +142,7 @@ export default class Nuxt {
     this.readyMessage = null
   }
 
-  listen(port = 3000, host = 'localhost', socket = null) {
+  listen(port = null, host = null, socket = null) {
```
Comment (manniL) [inline lib/core/nuxt.js]: Just a small nit: Do we have to provide default values here?

Comment (Atinux) [reply lib/core/nuxt.js]: I don't think so, will remove them, good catch @manniL

**Review by atinux — APPROVED** [review]
