### PR TITLE
fix(vue-app): fixPrepatch in-out transition fix (#5797)

### LINKED ISSUE #5797: data function is being called after mounted when using transition in-out mode
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://codesandbox.io/embed/codesandboxnuxt-i8l14](https://codesandbox.io/embed/codesandboxnuxt-i8l14)

### Steps to reproduce

set nuxt-child page transition mode to "in-out" and set transition css and set something new value in mounted lifecycle

please check Reproduction link

### What is expected ?

call data function once

### What is actually happening?

data function is being called after mounted and  $data is being overwritten

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9259">#c9259</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by Elevista**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves: #5797 

Problem: fixPrepatch + $data updates after component mounted twice. (in-out transition mode)

Please review and check if has side effect

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/client.js [hunk 1]
```diff
@@ -488,14 +488,14 @@ function showNextPage(to) {
 // Will not update the instance data, so we have to update $data ourselves
 function fixPrepatch(to, ___) {
   if (this._pathChanged === false && this._queryChanged === false) return
+  
+  const matches = []
+  const instances = getMatchedComponentsInstances(to, matches)
```
Comment (Atinux) [inline packages/vue-app/template/client.js]: Why moving this outside of `Vue.nextTick`?

Comment (Elevista) [reply packages/vue-app/template/client.js]: Unlike transition out-in mode, in in-out mode,
the "transition In" component instance has already been created in this nextTick,
so "transition In" component instance is included in array returned from the getMatchedComponentsInstances function.

Assuming the purpose of this function,
it is assumed that the newly created component should not be listed in this array.
So to get the same result as out-in mode, the code should be outside the nextTick.

Comment (Atinux) [reply packages/vue-app/template/client.js]: Alright sounds good 😄
