### PR TITLE
fix(vue-app): call ssrContext.unsetMutationObserver only if it exists

### LINKED ISSUE #10131: calling `error` from a middleware generates a TypeError in full static mode
### Versions

- nuxt: v2.15.0
- node: any

### Reproduction

[https://github.com/reegodev/nuxt-middleware-error](https://github.com/reegodev/nuxt-middleware-error)

### Steps to reproduce
- Enable full static mode
- Enable Vuex
- Create a middleware that calls the `error` function exposed through the context
- Run `yarn generate`

### What is Expected?
Route generation should fail with the error exposed through the `error` call

### What is actually happening?
Route generation fails with `TypeError: ssrContext.unsetMutationObserver is not a function`.

### Additional info
Although this does not sound like a big deal, when using Bridge + Nitro and edge rendering, if the middleware calls the `error` function the page returns a 500 error instead of our standard error page.

### PR DESCRIPTION
**Pull request by reegodev**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves: #10131
`ssrContext.unsetMutationObserver` is set after router middleware are evaluated. This causes a problem because if a middleware calls `error`, then the app calls `renderErrorPage` which in turns calls `ssrContext.unsetMutationObserver()` in the `beforeRender` function, causing an error.

[https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#L137](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#L137)
[https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#L209](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#209)
[https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#L216](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/server.js#L216)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/server.js [hunk 1]
```diff
@@ -134,7 +134,7 @@ export default async (ssrContext) => {
 
       <% if (isFullStatic && store) { %>
       // Stop recording store mutations
-      ssrContext.unsetMutationObserver()
+      ssrContext.unsetMutationObserver && ssrContext.unsetMutationObserver()
```
Comment (danielroe) [inline packages/vue-app/template/server.js:137]:
```suggestion
      // unsetMutationObserver is only set after all router middleware are evaluated
      if (ssrContext.unsetMutationObserver) {
        ssrContext.unsetMutationObserver()
      }
```

**Review by danielroe — APPROVED** [review]

**Review by pi0 — APPROVED** [review]
Thanks
