### PR TITLE
fix(utils): Router config `trailingSlash` causes error with dynamic nuxt-child routes

### LINKED ISSUE #9472: Router config `trailingSlash` causes error with dynamic nuxt-child routes
### Versions

- nuxt: tested with v2.15.6 & v2.15.7
- node: v14.16.0

### Reproduction

Following you see a still working example:

https://codesandbox.io/s/great-river-qg38y?file=/nuxt.config.js

The route structure is as following:

-- | parent.vue
-- | parent
-----| _child
-------| index.vue

### Steps to reproduce

I hope the following video helps. It shows first the working example and then the not working where the nuxt-child shows up on the parent route where it shouldn't. That happens after adding the `trailingSlash` (with `true` or `false`) option to the router config.

https://user-images.githubusercontent.com/3109921/123074295-74921880-d417-11eb-9571-b28dd905622c.mp4

Because of #9442 I added the trailingSlash router config to avoid getting the slash removed in nuxt v2.15.7. After that we recognized that this causes that dynamic nuxt-child routes stopped working correctly. We changed back to nuxt v2.15.6 but the bug was already present there.

### What is Expected?

That the dynamic nuxt-child routes work like without the router config. Means the parent route shows only the parent but the child routes show the parent including the nuxt-child.

### What is actually happening?

The router `trailingSlash` option causes that the dynamic nuxt-child gets shown on the parent route.

### PR DESCRIPTION
**Pull request by ms-fadaei**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
fix #9472 
This bug existed because `trailingSlash = true` not been considered in a specific condition and exists regex missed it!

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/utils/src/route.js [hunk 1]
```diff
@@ -56,7 +56,11 @@ function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-',
     route.path = isChild ? route.path.replace('/', '') : route.path
     if (route.path.includes('?')) {
       if (route.name.endsWith(`${routeNameSplitter}index`)) {
-        route.path = route.path.replace(/\?$/, '')
+        if (trailingSlash) {
+          route.path = route.path.replace(/\?\/$/, '/')
```
Comment (clarkdo) [inline packages/utils/src/route.js:60]: The change looks good.

Just double check, will this affect logic inside below route.path.split(/) ?

File: packages/utils/src/route.js [hunk 2]
```diff
@@ -56,7 +56,11 @@ function cleanChildrenRoutes (routes, isChild = false, routeNameSplitter = '-',
     route.path = isChild ? route.path.replace('/', '') : route.path
     if (route.path.includes('?')) {
       if (route.name.endsWith(`${routeNameSplitter}index`)) {
-        route.path = route.path.replace(/\?$/, '')
```
Comment (pi0) [inline packages/utils/src/route.js:59]: Maybe can be simplified with something like this? (not tested)

```js
route.path = route.path.replace(/\?\/?$/, trailingSlash ? '/' : '')

File: packages/utils/src/route.js (hunk 1 above)
Comment (ms-fadaei) [reply packages/utils/src/route.js:60]: No, it dosn't.

before change:
```js
[
  ':child?',
   ''
]
```

after change:
```js
[
  ':child',
  ''
]
```

it just removes `?` same as without `trailingSlash` option

File: packages/utils/src/route.js (hunk 2 above)
Comment (ms-fadaei) [reply packages/utils/src/route.js:59]: Yes, it can be.
I just do that because of more readability

Comment (pi0) [reply packages/utils/src/route.js:59]: I think it will cover are 4 possible cases (with/without trailingSlash flag x path containing trailing/not) so would be safer too :)

**Review by pi0 — COMMENTED** [review]
Thanks! <3
