### PR TITLE
fix(nuxt): prefix server component ids to avoid collisions

### LINKED ISSUE #21471: Collision between server-components id and nuxt islands id
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

- run `npx nuxi dev ./test/fixtures/basic` in the nuxt repo
- go to `/`
- click on `islands` to go to `/islands`
- see that there's a collision of `nuxt-ssr-component-uid`, we should always have 1 nde

### Describe the bug

This make slots buggy as some slots will be teleported to the wrong place

### Additional context

thanks @danielroe !!

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue
resolve https://github.com/nuxt/nuxt/issues/21471

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Hi :wave:

this is a VERY small workaround :joy:  to avoid server components and island component having the same id 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/runtime/server-component.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ const SLOT_FALLBACK_RE = /<div nuxt-slot-fallback-start="([^"]*)"[^>]*><\/div>((
 const SSR_UID_RE = /nuxt-ssr-component-uid="([^"]*)"/
 
 let id = 0
-const getId = process.client ? () => (id++).toString() : randomUUID
+const getId = process.client ? () => (id--).toString() : randomUUID
```
Comment (danielroe) [inline packages/nuxt/src/components/runtime/server-component.ts:21]: what about a prefix, like `'s-' + id`, which would also coerce the id to string

Comment (huang-julien) [reply packages/nuxt/src/components/runtime/server-component.ts:21]: sure !

**Review by danielroe — APPROVED** [review]
