### PR TITLE
fix(schema): v3 app dir backwards compatibility

### LINKED ISSUE #27527: v4 app directory force enabled when using v3 app files
**Summary (generated)**:

Here is the brief summary in English:

Environment: v3.12.0 with future compatibilityVersion 4.

Reproduction: https://stackblitz.com/edit/nuxt-starter-vtcdcp?file=nuxt.config.ts

Bug: When migrating from v3 to v4, having an existing app directory from v3 router options or spa-loading-template config automatically enables the new directory structure, preventing users from keeping the v3 structure.

<hr>

### Environment

v3.12.0 with

```ts
 future: {
    compatibilityVersion: 4,
  },
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vtcdcp?file=nuxt.config.ts

### Describe the bug

When migrating from v3 to v4, it's possible users will already have an app directory from either an `app/router.options.ts` or an `app/spa-loading-template.html` config.

With having this app folder from v3, the new directory structure is automatically enabled it, blocking users from staying on the v3 directory structure and forcing them to adopt v4 app dir.

While the migration docs does mention that you can force this behavior, I think the DX can be improved.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by harlan-zw**
### 🔗 Linked issue

https://github.com/nuxt/nuxt/issues/27527

### 📚 Description

Allows users to use v3 directory structure in v4 when they already have an app folder.

v3 dir structure:

- empty `app` folder
- app folder with only `router.options.ts`
- app folder with only `spa-loading-template.html` 
- app folder with either `router.options.ts` or  `spa-loading-template.html` 

v4 app dir:

- any file besides `router.options.ts` or  `spa-loading-template.html` in the app dir

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

**Comment by Atinux** [comment]
Good idea!

File: packages/schema/src/config/common.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
-import { existsSync } from 'node:fs'
+import { existsSync, readdirSync } from 'node:fs'
```
Comment (danielroe) [inline packages/schema/src/config/common.ts:1]:
```suggestion
import { existsSync } from 'node:fs'
```
