### PR TITLE
fix(vue-app): sanitize path with trailing slash in `getLocation` (#6744)

### LINKED ISSUE #6744: router.base is sanitized with trailing slash which does not match with path wihout trailing slash (spa mode only)
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://codesandbox.io/s/example-hello-world-no8hn](https://codesandbox.io/s/example-hello-world-no8hn)

### Steps to reproduce

Set nuxt.config
```js
{
  mode: 'spa',
  router: {
    base: "/app"
  }
}
```

Open localhost:3000/app

### What is expected ?

`index.vue` file from pages dir

### What is actually happening?

404 This page could not be found

### Additional comments?

Works fine if open localhost:3000/app/

Works fine in universal mode, but logs ssr error (The client-side rendered virtual DOM tree is not matching...)

It's happening because of `getLocation` function (https://github.com/nuxt/nuxt.js/blob/701f2d033bbc421f85f888f9bf9100b176aac818/packages/vue-app/template/utils.js#L267) and because of `router.base` is sanitizing with trailing slash (https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/options.js#L93)

So I propose change `getLocation` function

### PR DESCRIPTION
**Pull request by crutch12**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves: #6744

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/utils.js [hunk 1]
```diff
@@ -260,7 +260,7 @@ export function promisify (fn, context) {
 
 // Imported from vue-router
 export function getLocation (base, mode) {
-  let path = decodeURI(window.location.pathname)
+  let path = decodeURI(window.location.pathname + '/').replace('//', '/') // to get matched with sanitized router.base
```
Comment (pi0) [inline packages/vue-app/template/utils.js]: Some important note:

- Having double slash inside path in url is valid and if we do replace, may introduce regressions. What if we just ensure pathname is ending with slash and if not appending?

Some  general notes:

1. (not related to this PR) but can we move this after `if(mode ==='hash')`. It can prevent an extra computed var when we don't need it
2. Can you please put comment above and start first chat with upper case? (`// To get`)

**Review by pi0 — DISMISSED** [review]

File: packages/vue-app/template/utils.js (hunk 1 above)
Comment (crutch12) [reply packages/vue-app/template/utils.js]: You are right, I didn't think about this case and will fix it

Comment (crutch12) [reply packages/vue-app/template/utils.js]: Fixed

File: packages/vue-app/template/utils.js [hunk 2]
```diff
@@ -261,6 +261,10 @@ export function promisify (fn, context) {
 // Imported from vue-router
 export function getLocation (base, mode) {
   let path = decodeURI(window.location.pathname)
+  // To get matched with sanitized router.base
+  if (!/\/$/.test(path)) {
```
Comment (pi0) [inline packages/vue-app/template/utils.js]: We can also use [`endsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith)

Comment (crutch12) [reply packages/vue-app/template/utils.js]: I'm agree, didn't see this method previously, lol
Fixed

**Comment by crutch12** [comment]
@pi0 fixed getLocation again, because at first I did mutating with path and it failed tests. Now I don't mutate path
Because of mutating a lot of apps could be crushed :D

File: packages/vue-app/template/utils.js [hunk 3]
```diff
@@ -264,7 +264,8 @@ export function getLocation (base, mode) {
   if (mode === 'hash') {
     return window.location.hash.replace(/^#\//, '')
   }
-  if (base && path.indexOf(base) === 0) {
+  // To get matched with sanitized router.base add trailing slash
+  if (base && (path.endsWith('/') ? path : path + '/').startsWith(base)) {
```
Comment (pi0) [inline packages/vue-app/template/utils.js]: This is an inline patch. Not sure but may introduce inconsistencies. WDYT @pimlie @manniL?

**Review by pimlie — COMMENTED** [review]
I have nothing to add then what I've said before that we should add some sanitation methods to do this for us. It seems we have seen a rise of issues caused by trailing slashes and this is exactly what I was worried about (even though they are probably not all related)

**Comment by Elhebert** [comment]
Are there any update about the status of this PR?

We can't update Nuxt in our project as this issue is blocking us. At the moment we are stuck on `2.6.1`.

**Comment by crutch12** [comment]
I don't know the proper way how to fix my PR to be merged, so I just still waiting :)

@pi0 could you help me with PR?

**Comment by pi0** [comment]
Hi @crutch12 Sure we should merge this fix just as @pimlie mentioned, it is not only source of inconsistencies for baseURL and trailing slash handling. (like regression introduced by https://github.com/nuxt/nuxt.js/pull/6775 with 2.12). Do you mind adding an e2e test to cover this change? Meanwhile working to make a url utility package to use it on all places instead of depending on sanetization(s)

**Comment by crutch12** [comment]
Ok, I'll try

**Comment by crutch12** [comment]
@pi0 I've added some e2e tests for checking spa mode router.base (in browser, based on spa fixtures)

Basically with/without trailing slash tests.

Could you check it out?

**Review by pi0 — APPROVED** [review]
Looks awesome! Thanks for your time @crutch12 :green_heart:
