### PR TITLE
fix(nuxt): ensure `useAsyncData` reactive to `key` changes when `immediate: false`

### LINKED ISSUE #31976: URL is not watch in useFetch when `immediate` is set to `false`
### Environment

- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     3.17.1
- CLI Version:      3.25.0
- Nitro Version:    2.11.11
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4ptgsiht?file=app.vue

### Describe the bug

Hi I noticed this little bug,

If you set params `immediate` to `false` with useFetch composable, URL is not watch correctly (a new fetch is not perform when url change).

I don't know if it's due to new Data Fetching system introduce with Nuxt 3.17.

Thx in advance if you can do something about that ! 😄

#### Workaround
You can add URL to watch params like that:

```JS

const url = computed(() => ...)  // your computed url
const { data: results } = useFetch(url, {
  immediate: false,
  watch: [url]
});
```

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by Mini-ghost**
### 🔗 Linked issue

Resolves https://github.com/nuxt/nuxt/issues/31976

### 📚 Description

This PR addresses an issue where `useAsyncData` does not react to changes in the `key` parameter when `immediate: false`. As a result, data is not re-fetched upon key changes, leading to potential inconsistencies.

Thank you very much for your time and review! If there’s anything I might have overlooked, please feel free to let me know.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
I think we should probably only immediately execute asyncData when the first `execute` had already been called.

for useFetch, we need to execute regardless, because that was the behaviour previously. we can make the behaviour the same for v4, so we should export a flag for now to equalise the data.

we can use the `.immediate` trick in fetch.ts only when the flag is not defined

File: packages/nuxt/src/app/composables/asyncData.ts [hunk 1]
```diff
@@ -359,15 +359,16 @@ export function useAsyncData<
       }
     }
     const unsubKey = watch(key, (newKey, oldKey) => {
+      const hasRun = nuxtApp._asyncData[oldKey]?.data.value !== asyncDataDefaults.value
```
Comment (danielroe) [inline packages/nuxt/src/app/composables/asyncData.ts:362]:
```suggestion
      const hasRun = oldKey && nuxtApp._asyncData[oldKey]?.data.value !== asyncDataDefaults.value
```
