### PR TITLE
fix(nuxt): add auto-import declarations for `shared/` context

### LINKED ISSUE #32646: fix(imports): enable intra-directory auto-imports for shared utilities
### Problem
Nuxt 4's auto-import system has a limitation where functions exported from shared directories (e.g., `shared/utils/`) are globally auto-imported for Vue components, but TypeScript/editors don't recognize these functions when used within the same directory. This causes "Cannot find name" errors in development despite the code working correctly at runtime.

### Example
In a typical setup with shared utilities:

```typescript
// shared/utils/typeGuards.ts
export const isArray = (value: any): value is any[] => Array.isArray(value)

// shared/utils/numberHelpers.ts
export const toNumber = (v: unknown) => 
  isArray(v) ? v.map(item => toNumber(item)) : Number(v) // ❌ Cannot find name 'isArray'
```

The `isArray` function is available globally in Vue components but not recognized within the same `shared/utils/` directory.

### Root Cause
The auto-import scanning in `packages/nuxt/src/imports/module.ts` only makes exports globally available but doesn't handle intra-directory imports. The `scanDirExports` function creates imports that work globally but not within the same directory scope.

### Solution
Enhanced the import scanning logic to create duplicate import entries for shared directories:

1. **Identify shared directories**: Filter `composablesDirs` for paths containing `/shared/`
2. **Create duplicate imports**: Generate additional import entries with special metadata for intra-directory access
3. **Maintain compatibility**: Preserve existing global auto-import functionality

### Implementation Details
The fix adds this logic to the `regenerateImports` function:

```typescript
// Add intra-directory imports for shared directories
const intraDirectoryImports: Import[] = []
const sharedDirs = composablesDirs.filter(dir => dir.includes('/shared/'))
for (const sharedDir of sharedDirs) {
  const dirImports = scannedImports.filter(imp => imp.from.startsWith(sharedDir))
  for (const imp of dirImports) {
    intraDirectoryImports.push({
      ...imp,
      meta: { ...imp.meta, intraDirectory: sharedDir }
    })
  }
}
imports.push(...scannedImports, ...intraDirectoryImports)
```

### Benefits
- ✅ **TypeScript Support**: Eliminates "Cannot find name" errors in editors
- ✅ **No Breaking Changes**: Maintains existing global auto-import behavior  
- ✅ **Better DX**: Enables seamless cross-file usage within shared directories
- ✅ **Performance**: Minimal overhead, only affects shared directories

### LINKED ISSUE #32714: fix(types): v4 auto-import in shared directory
### Environment

- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     4.0.1
- CLI Version:      3.26.4
- Nitro Version:    2.12.3
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-rql8bhyh?file=shared%2Futils%2Futil.ts

Run `npm install && npm run typecheck`.

### Describe the bug

With the new Typescript project references in `tsconfig.json`, utils in the shared directory seemingly don't know about shared utils according to the typecheck. There was no error with the `tsconfig.json` that just extended `./.nuxt/tsconfig.json`.

### Additional context

I found two similar issues that may report the same issue, but their descriptions don't allow me to fully confirm this as they're missing a link to a reproduction:
- https://github.com/nuxt/nuxt/issues/32652
- https://github.com/nuxt/nuxt/issues/32646

### Logs

Image

### PR DESCRIPTION
**Pull request by cernymatej**
### 🔗 Linked issue
fix https://github.com/nuxt/nuxt/issues/32714
fix https://github.com/nuxt/nuxt/issues/32646
closes https://github.com/nuxt/nuxt/pull/32671

### 📚 Description
This PR fixes a problem where the `shared/` context didn't reference auto-import global type declarations.
Initially, I intended to update https://github.com/nuxt/nuxt/pull/32671, but I decided against it since this implementation isn't based on that PR. I thought opening a new one would be clearer.

Here, we don't create a new unimport context for `shared/` but instead create an intersection of `app/` and `server/` auto-imports. Only the ones that are available in **both** contexts are put into `types/shared-imports.d.ts`. This way, it handles imports added by `addImports`, `addServerImports` and so on...

----
@danielroe One thing I'm not entirely sure how to handle best is isomorphic functions like `useRuntimeConfig`. Initially, I implemented it to always prefer the import path **from app**, but later I thought it might be better to create a union for these types instead. This would, however, require a change in `unimport` (see: https://github.com/unjs/unimport/pull/489). What do you think?

> [!IMPORTANT]
> Just to be clear - this should not be merged in the current state before https://github.com/unjs/unimport/pull/489. Or instead we can use the [previous implementation](https://github.com/nuxt/nuxt/pull/33978/changes/ee77bebca3859b094b237297ebf2bfa94e365b1f), which always uses the path from the nuxt app context.

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
this is a nice solution that avoids creating a separate unimport instance ❤️🙏

File: packages/nuxt/src/imports/module.ts [hunk 1]
```diff
@@ -114,6 +114,12 @@ export default defineNuxtModule<Partial<ImportsOptions>>({
       await nuxt.callHook('imports:context', ctx)
     })
 
+    let nitroCtx: Unimport | undefined
+
+    nuxt.hook('nitro:init', (nitro) => {
+      nitroCtx = nitro.unimport
+    })
```
Comment (huang-julien) [inline packages/nuxt/src/imports/module.ts]: not a 100% sure about it. But can we use `useNitro()` to retrieve the nitro instance ?

Comment (cernymatej) [reply packages/nuxt/src/imports/module.ts]: Good point. I've tried it, but the modules' setup functions run before `_nitro` is assigned on the Nuxt App, so the function throws an error.

https://github.com/nuxt/nuxt/blob/3293dde6bac9e93e4609336abd8220fd97441986/packages/nuxt/src/core/nuxt.ts#L610

https://github.com/nuxt/nuxt/blob/3293dde6bac9e93e4609336abd8220fd97441986/packages/nuxt/src/core/nuxt.ts#L762-L763
in `bundleServer()` 👇
https://github.com/nuxt/nuxt/blob/3293dde6bac9e93e4609336abd8220fd97441986/packages/nitro-server/src/index.ts#L642-L643

---

It didn't feel right to call it from within the `getContents` function for the `shared-imports.d.ts` file. Is it guaranteed to be always called inside a Nuxt context? Should I use `useNitro()` there?

Comment (huang-julien) [reply packages/nuxt/src/imports/module.ts]: `It didn't feel right to call it from within the getContents function for the shared-imports.d.ts` I was thinking about that. 
Calling `useNitro` should be safe here IMO

Comment (cernymatej) [reply packages/nuxt/src/imports/module.ts]: Okay, thank you. I've updated it.

**Review by danielroe — COMMENTED** [review]
@cernymatej let's see if we can already merge this, preferring the ones from `app/` context, and then refactor to a union (for more accurate types) when the unimport PR is merged.

**Review by danielroe — APPROVED** [review]
❤️

**Comment by Nicolas-Yazzoom** [comment]
This improvement seems to have a negative impact on the suggestions inside my IDE which might be caused by an overlooked side effect. I'm having trouble with the playground on both Stackblitz and Codesandbox, so for now I'll try to explain like this, but I can retry later if required. Consider this structure:

```
root
└── shared
    └── types
        ├── api
        │   ├── types.gen.ts   // export type Feature1 = unknown
        │   └── index.ts       // export { type Feature1 } from './types.gen' 
        ├── a.ts
        └── b.ts
```

And this content for `a.ts` and `b.ts`:

```typescript
// shared/types/a.ts

import type { Feature1 } from '#shared/types/api'

export type Feature2 = Feature1 

export type Feature3 = unknown // Actual type doesn't matter

// shared/types/b.ts with nuxt@4.2.2

type Test1 = Feature1 // IDE suggests to import

type Test2 = Feature2 // IDE suggests to import

type Test3 = Feature3 // IDE suggests to import 

// shared/types/b.ts with nuxt-nightly@4.3.0-29459067.7e357c2c and later

type Test1 = Feature1 // IDE suggests to import

type Test2 = Feature2 // 'Feature2' refers to a value, but is being used as a type here. Did you mean 'typeof Feature2'?

type Test3 = Feature3 // 'Feature3' refers to a value, but is being used as a type here. Did you mean 'typeof Feature3'?
```

TypeScript incorrectly thinks some types are values. This is caused by the contents of `shared-imports.d`:

```typescript
  const Feature2: typeof import('../../shared/types/a').Feature2
  const Feature3: typeof import('../../shared/types/a').Feature3
```

Is this behavior intentional?

**Comment by dargmuesli** [comment]
@Nicolas-Yazzoom if this issue still persists in v4.3.0 released a few hours ago, please create a new issue with that description (and maybe a stackblitz link to test) :pray:
