### PR TITLE
fix(vite): log transformation result when a PARSE_ERROR happens

### LINKED ISSUE #25525: Log the whole file when a transformation issue happens
### Describe the feature

related to https://github.com/nuxt/nuxt/issues/25513

When a transform issue happens within a virtual file, it's almost impossible to get the cause of the issue. We should fidn a way to provide a log of the whole content of the file or allow the user to acces to the virtual file

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #25525 

### 📚 Description

This PR log the transform result of a file if there is a JS parsing issue following all the trasformation of a file. This will greatly help developers when an issue happens due to transfrormation plugins in vite since their own file could be 100% fine.

### CODE REVIEW

File: packages/vite/src/vite-node.ts [hunk 1]
```diff
@@ -156,13 +159,18 @@ function createViteNodeApp (ctx: ViteBuildContext, invalidates: Set<string> = ne
       if (isAbsolute(moduleId) && !isFileServingAllowed(moduleId, viteServer)) {
         throw createError({ statusCode: 403 /* Restricted */ })
       }
-      const module = await node.fetchModule(moduleId).catch((err) => {
+      const module = await node.fetchModule(moduleId).catch(async (err) => {
         const errorData = {
           code: 'VITE_ERROR',
           id: moduleId,
           stack: '',
+          message: err.message,
```
Comment (danielroe) [inline packages/vite/src/vite-node.ts:167]: does this make a difference?

File: packages/vite/src/vite-node.ts [hunk 2]
```diff
@@ -156,13 +159,18 @@ function createViteNodeApp (ctx: ViteBuildContext, invalidates: Set<string> = ne
...
           ...err,
         }
+
+        if (!errorData.frame && NEED_FRAME_ERRORS.includes(errorData.code)) {
```
Comment (danielroe) [inline packages/vite/src/vite-node.ts:171]: I think we can directly compare for a slight perf benefit (and refactor to Set if we need to check more error codes)

File: packages/vite/src/vite-node.ts (hunk 1 above)
Comment (huang-julien) [reply packages/vite/src/vite-node.ts:167]: oops, that's something i need to remove

**Review by danielroe — APPROVED** [review]
