### PR TITLE
fix(nuxt): correct css order for layers

### LINKED ISSUE #25167: css files from base layer are added to the html head after the project css files.
css files from base layer are added to the html head after the project css files.

please see: [stackblitz.com](https://stackblitz.com/edit/nuxt-starter-mvptjc?file=nuxt.config.ts)

nuxt.config.ts:

```
export default defineNuxtConfig({
  devtools: { enabled: false },
  css: ['~/assets/css/project.css'],
  extends: ['./layers/base'],
});
```

base layer nuxt.config:
```
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const currentDir = dirname(fileURLToPath(import.meta.url));

export default defineNuxtConfig({
  css: [join(currentDir, './assets/css/base.css')],
});
```

in the website source:

```
<head>
<link rel="stylesheet" href="/_nuxt/assets/css/project.css">
<link rel="stylesheet" href="/_nuxt/layers/base/assets/css/base.css">
</head>

```

project.css should clearly be after base.css file(s) so that project can overwrite styles?

_Originally posted by @kvanska in https://github.com/nuxt/nuxt/issues/13367#issuecomment-1855997214_

### PR DESCRIPTION
**Pull request by dargmuesli**
### 🔗 Linked issue

Resolves https://github.com/nuxt/nuxt/issues/25167

### 📚 Description

With this change, child projects can override CSS of parent layers.

I'm not sure if this is the correct place to put this logic. The linked issue mentions some changes to `c12` which I'm not sure where to find in the Nuxt source.

### CODE REVIEW

File: packages/nuxt/src/core/nuxt.ts [hunk 1]
```diff
@@ -155,13 +155,21 @@ export const keyDependencies = [
...
+  for (const config of reversedConfigs) {
     if (config.hooks) {
       nuxt.hooks.addHooks(config.hooks)
     }
   }
 
+  // Correct css order
+  nuxt.options.css = reversedConfigs
+    .flatMap(config => config.css || [])
+    .filter((css): css is string => typeof css === 'string')
```
Comment (danielroe) [inline packages/nuxt/src/core/nuxt.ts:171]: Maybe we could also de-duplicate?

**Review by danielroe — APPROVED** [review]

**Comment by dargmuesli** [comment]
@danielroe thank you for taking care of all the remaining work! ❤️
