### PR TITLE
fix(nuxt): redirect with hash in routeRules

### LINKED ISSUE #32802: Docs contain multiple broken anchor links
### Environment

Documentation for both versions:
 
- <https://nuxt.com/docs/4.x/>
- <https://nuxt.com/docs/3.x/>

### Reproduction

**Example 1:**

1. Got to <https://nuxt.com/docs/4.x/guide/concepts/rendering#client-side-rendering>
2. Scroll to the alert containing the link [Read more in SPA Loading Template.](https://nuxt.com/docs/api/configuration/nuxt-config#spaloadingtemplate)
3. Click the link.
4. Navigation to correct page, but the anchor is being removed.

- Link href is: https://nuxt.com/docs/api/configuration/nuxt-config#spaloadingtemplate
- Navigation to: https://nuxt.com/docs/4.x/api/nuxt-config
- Expected: https://nuxt.com/docs/4.x/api/nuxt-config#spaloadingtemplate

**Example 2:**

1. Go to <https://nuxt.com/docs/4.x/getting-started/configuration>
2. Try any of the links containing `Read more in Docs > API > Configuration > Nuxt Config`
3. It navigates always to <https://nuxt.com/docs/4.x/api/nuxt-config> instead of the anchor.

**Example 3: (actually a separate BUG, but related and maybe same fix)**

1. Go to <https://nuxt.com/docs/3.x/getting-started/configuration>
2. Try any of the links containing `Read more in Docs > API > Configuration > Nuxt Config`
3. It navigates always to Nuxt 4 docs <https://nuxt.com/docs/4.x/api/nuxt-config> instead of Nuxt 3 docs and the anchor. 

### Describe the bug

It seems to be the case for all links to the API > Configuration.

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix https://github.com/nuxt/nuxt/pull/33217#issue-3410845439
resolves https://github.com/nuxt/nuxt/issues/32802

### 📚 Description

Should we put it under a flag to avoid unexpected behavior for our users ?

### CODE REVIEW

File: packages/nuxt/src/app/middleware/manifest-route-rule.ts [hunk 1]
```diff
@@ -6,10 +6,12 @@ export default defineNuxtRouteMiddleware(async (to) => {
   if (import.meta.server || import.meta.test) { return }
   const rules = await getRouteRules({ path: to.path })
   if (rules.redirect) {
+    const hash = window.location.hash
```
Comment (Mini-ghost) [inline packages/nuxt/src/app/middleware/manifest-route-rule.ts]: I’m curious about the difference between using `window.location.hash` and `to.hash` here. Would `to.hash` be a better choice?

**Comment by danielroe** [comment]
can you reproduce this issue minimally? was just looking at this but things seem to work

**Comment by huang-julien** [comment]
> can you reproduce this issue minimally? was just looking at this but things seem to work

Doesn''t work on my side on the main branch. I'll write a E2E test

Edit: Oh i just understood what you said. Yes, i'm write a test for this

**Comment by huang-julien** [comment]
It's a bit strange. `page.waitForURL` doesn't work. Feels like an issue with playwright

**Review by danielroe — APPROVED** [review]

File: packages/nuxt/src/app/middleware/manifest-route-rule.ts [hunk 2]
```diff
@@ -6,10 +6,11 @@ export default defineNuxtRouteMiddleware(async (to) => {
   if (import.meta.server || import.meta.test) { return }
   const rules = await getRouteRules({ path: to.path })
   if (rules.redirect) {
-    if (hasProtocol(rules.redirect, { acceptRelative: true })) {
-      window.location.href = rules.redirect
+    const path = rules.redirect.includes('#') ? rules.redirect : (rules.redirect + to.hash)
```
Comment (danielroe) [inline packages/nuxt/src/app/middleware/manifest-route-rule.ts:9]: should we also support redirecting with a query string?

Comment (huang-julien) [reply packages/nuxt/src/app/middleware/manifest-route-rule.ts:9]: yeah... that's a good question...
Anchors whether present or not won't deeply affect the application while query string can trigger unwanted side-effects
