### PR TITLE
fix(nuxt): add sourcemap path transformation for client builds

### LINKED ISSUE #32009: Invalid relative paths in sourcemap "sources" under .output/public
### Environment

- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     3.17.2
- CLI Version:      3.25.0
- Nitro Version:    2.11.11
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ojzodcbq

In the reproduction repo, run `npm run build`, then check "sources" in any of the source maps:

```
~/projects/nuxt-starter-fajroeah
❯ cd .output/public/_nuxt/

~/projects/nuxt-starter-fajroeah/.output/public/_nuxt
❯ head -c 200 Dwmq4gRZ.js.map
{"version":3,"file":"Dwmq4gRZ.js","sources":["../../../../node_modules/nuxt/dist/app/components/error-500.vue"],"sourcesContent":["<script setup>\nimport { useHead } from \"#imports\";\nconst props = 

~/projects/nuxt-starter-fajroeah/.output/public/_nuxt
❯ cat ../../../../node_modules/nuxt/dist/app/components/error-500.vue
cat: ../../../../node_modules/nuxt/dist/app/components/error-500.vue: No such file or directory
```

### Describe the bug

After `nuxt build`, sourcemaps under `.output/public/_nuxt/*.map`, specifically the `"sources"` lists, are invalid (they point to missing files).

### Additional context

I understand that Nuxt builds the initial build under `.nuxt/dist/client` and then prepares `.output/public` in a separate step; the `*.map` files are copied verbatim and no wonder the relative paths become invalid. However, I believe Nuxt should post-process copied sourcemaps and fix relative source paths, otherwise the tooling breaks when it consumes the sourcemaps from `.output` (such as when I upload them to Sentry).

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by peterbud**
### 🔗 Linked issue

Resolves #32009 

### 📚 Description

This change fixes the source map paths in client builds, to point them to the right sourcemaps.

My first contribution to this repo, pls check if I used the `nuxt` config dirs properly.

**Question**: should I add a test for checking the generated sourcemap content? I have seen that all fixtures have disabled sourcemaps, so maybe I need to add a new fixture? LMK!

### CODE REVIEW

**Comment by peterbud** [comment]
Is there anything I can do to move this PR forward? Please let me know.

File: packages/vite/src/client.ts [hunk 1]
```diff
@@ -172,6 +172,20 @@ export async function buildClient (ctx: ViteBuildContext) {
...
       chunkFileNames: ctx.nuxt.options.dev ? undefined : fileNames,
       entryFileNames: ctx.nuxt.options.dev ? 'entry.js' : fileNames,
+      sourcemapPathTransform (relativeSourcePath, sourcemapPath) {
+        // client build is running in a temporary build directory, like `.nuxt/dist/client`
+        // so we need to transform the sourcemap path to be relative to the final build directory
+        // which is normally `.output/public`
+        if (relativeSourcePath.startsWith('..')) {
+          const absoluteSourcePath = resolve(dirname(sourcemapPath), relativeSourcePath)
+          const newRelativePath = relative(
+            join(ctx.config.root!, '.output/public', ctx.nuxt.options.app.buildAssetsDir),
```
Comment (danielroe) [inline packages/vite/src/client.ts]: we shouldn't hard-code `.output/public` as this will depend on the nitro preset used - we can get this from the resolved nitro options.

Comment (peterbud) [reply packages/vite/src/client.ts]: Thanks, I'll update once I'm back from the vacation

Comment (danielroe) [reply packages/vite/src/client.ts]: no worries - I hope you don't mind if I push a quick fix

**Review by danielroe — APPROVED** [review]
