### PR TITLE
fix(webpack): use lodash `cloneDeep` again

### LINKED ISSUE #23843: webpack-builder broken in nuxt 3.8.0
### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@10.1.0
- Builder:          webpack
- User Config:      devtools, builder, webpack
- Runtime Modules:  -
- Build Modules:    -

My package.json:
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/webpack-builder": "^3.8.0",
    "nuxt": "^3.8.0",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  }
}

### Reproduction

https://github.com/spreadpando/nuxt-test

Steps to reproduce:

- npx nuxi@latest init <project-name>
- cd <project-name>
- add `builder: 'webpack',` to nuxt.config.ts
- `npm run dev`
- answer "Yes" to ✔ Do you want to install @nuxt/webpack-builder package?
- see error

### Describe the bug

It appears there is an internal bug in the webpack-builder 3.8. I encountered when trying to upgrade nuxt from 3.3. 

### Additional context

Running Nuxt and webapck in production at the moment. We have need to implement several custom webpack loaders, hence the decision to user webpack over vite. Recent updates to the docs look to add some nice/necessary features to the webpack integration, we'd hope to be able to configure the esbuild process a bit, but it seems we won't be able to upgrade at present. Perhaps my config is incorrect, but it was at least working on 3.3, if a bit slow. Perhaps time to move to vue/express/webpack for the sake of simplicity.

`// https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({
  devtools: { enabled: true },
  builder: '@nuxt/webpack-builder',
  webpack: {
    loaders: {
      vue: {
        hotReload: true,
      }
    }
  }
})
`

### Logs

```shell-script
ERROR  Cannot start nuxt:  "fd" must be a positive integer: undefined                     

  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at new WriteStream (node:tty:88:11)
  at klona (node_modules/klona/dist/index.mjs:8:10)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:11:15)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:11:15)
  at klona (node_modules/klona/dist/index.mjs:35:13)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at getWebpackConfig (node_modules/@nuxt/webpack-builder/dist/index.mjs:386:10)
  at node_modules/@nuxt/webpack-builder/dist/index.mjs:1241:12
  at Array.map (<anonymous>)
  at bundle (node_modules/@nuxt/webpack-builder/dist/index.mjs:1237:72)
  at bundle (node_modules/nuxt/dist/index.mjs:4453:11)
  at async Promise.all (index 1)
  at async build (node_modules/nuxt/dist/index.mjs:4328:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:282:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:182:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:103:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23843

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This is a hotfix reverting part of https://github.com/nuxt/nuxt/pull/23692 to use `cloneDeep` for now instead of `klona`. (The webpack implementation here could likely be rewritten to avoid the need.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

File: packages/webpack/src/utils/config.ts [hunk 1]
```diff
@@ -68,5 +68,5 @@ export function fileName (ctx: WebpackConfigContext, key: string) {
 
 export function getWebpackConfig (ctx: WebpackConfigContext): Configuration {
   // Clone to avoid leaking config between Client and Server
-  return klona(ctx.config)
```
Comment (pi0) [inline packages/webpack/src/utils/config.ts:71]: Maybe a todo comment referencing to issue to not forget?

File: packages/webpack/src/utils/config.ts [hunk 2]
```diff
@@ -68,5 +68,5 @@ export function fileName (ctx: WebpackConfigContext, key: string) {
 
 export function getWebpackConfig (ctx: WebpackConfigContext): Configuration {
   // Clone to avoid leaking config between Client and Server
```
Comment (danielroe) [inline packages/webpack/src/utils/config.ts:70]:
```suggestion
  // Clone to avoid leaking config between Client and Server
  // TODO: rewrite webpack implementatation to avoid necessity for this
```
