### PR TITLE
fix: Duplicate declaration plugin when add/remove file in dev mode

### LINKED ISSUE #4275: Code duplication on hot reload
### Version
2.3.0-25689543.1a154e8
[edge](https://github.com/nuxt.js/releases/tag/edge)

### Reproduction link

[https://cmty.app](https://cmty.app)

### Steps to reproduce

During editing of page sometime hot reload fails and produce double imports in generated code
https://gist.github.com/aldarund/033b51b211d4d764fda12e36ed8ad3d0
https://i.imgur.com/Pzv43Se.png

Seems like a race condition somehwere

### What is expected ?

no code dup :)

### What is actually happening?

code dup and fail :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8088">#c8088</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Probably resolve #4275

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Review by aldarund — APPROVED** [review]

File: packages/builder/src/builder.js [hunk 1]
```diff
@@ -207,6 +207,7 @@ export default class Builder {
   async generateRoutesAndFiles() {
     consola.debug(`Generating nuxt files`)
 
+    this.plugins.length = 0
     this.plugins.push.apply(this.plugins, this.normalizePlugins())
```
Comment (pi0) [inline packages/builder/src/builder.js]: Can't we still simply set a new array to this.plugins?

Comment (manniL) [reply packages/builder/src/builder.js]: This wouldn't clear all references of `this.plugins`

Comment (clarkdo) [reply packages/builder/src/builder.js]: `BuildContext` is using it for registering alias in webpack builder.

Comment (clarkdo) [reply packages/builder/src/builder.js]: I have an idea, will open a pr.
