### PR TITLE
fix(nuxt): give priority to later middleware when deduping

### LINKED ISSUE #23513: Nuxt - Global middleware override and sort issue with layer
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4ryqhc?file=pages%2Findex.vue

### Describe the bug

Global middleware order and override seems to be not in the logic layer way.
base layer middleware shoud be overriden by project middleware and sorting should be alpha of all layers.

From the repro 
Console should show 
    00-middleware base 
    05-middleware project 
    10-middleware project 
    20-middleware base 

But show
    00-middleware base 
    10-middleware bas >
    20-middleware base
    05-middleware project 

For me 10-middleware base shoud be overriden by 10-middleware project
AND 05-middleware project should be just after 00-middleware base
  
I have made a module to correct the middleware sort (juste rename base\__modules foledr to base\module )
But can't find how to solve the not overriden middleware.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23513

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We were not overriding middleware by higher priority layers; this updates the test (using new test suite in https://github.com/nuxt/nuxt/pull/23520) to confirm correct behaviour.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/app.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { promises as fsp, mkdirSync, writeFileSync } from 'node:fs'
 import { dirname, join, resolve } from 'pathe'
 import { defu } from 'defu'
 import { compileTemplate, findPath, logger, normalizePlugin, normalizeTemplate, resolveAlias, resolveFiles, resolvePath, templateUtils, tryResolveModule } from '@nuxt/kit'
-import type { Nuxt, NuxtApp, NuxtPlugin, NuxtTemplate, ResolvedNuxtTemplate } from 'nuxt/schema'
+import type { Nuxt, NuxtApp, NuxtMiddleware, NuxtPlugin, NuxtTemplate, ResolvedNuxtTemplate } from 'nuxt/schema'
```
Comment (danielroe) [inline packages/nuxt/src/core/app.ts:5]:
```suggestion
import type { Nuxt, NuxtApp, NuxtPlugin, NuxtTemplate, ResolvedNuxtTemplate } from 'nuxt/schema'
```
