### PR TITLE
fix(nuxt): warn if `inheritAttrs: false` is set when using `useId`

### LINKED ISSUE #25605: useId bug when inheritAttrs: false
### Environment

- Operating System: Darwin
- Node Version:     v20.7.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0

### Reproduction

https://stackblitz.com/~/edit/nuxt-starter-1b6v9b

### Describe the bug

when we add `inheritAttrs: false` in the component, `data-n-ids` not added to element, that caused hydration error

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/25605

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a warning when `inheritAttrs: false` is set in a component where we are using `useId`. This is not compatible with our current implementation.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/composables/id.ts [hunk 1]
```diff
@@ -26,6 +26,9 @@ export function useId (key?: string): string {
   const instanceIndex = key + ':' + instance._nuxtIdIndex[key]++
 
   if (import.meta.server) {
+    if (!import.meta.dev && instance.vnode.type && typeof instance.vnode.type === 'object' && 'inheritAttrs' in instance.vnode.type && instance.vnode.type.inheritAttrs === false) {
```
Comment (huang-julien) [inline packages/nuxt/src/app/composables/id.ts:29]: we don't warn in dev ?

Comment (manniL) [reply packages/nuxt/src/app/composables/id.ts:29]: I think we should consider warning only in dev, no? 🤔

Comment (danielroe) [reply packages/nuxt/src/app/composables/id.ts:29]: yes! 🤦

Comment (danielroe) [reply packages/nuxt/src/app/composables/id.ts:29]:
```suggestion
    if (import.meta.dev && instance.vnode.type && typeof instance.vnode.type === 'object' && 'inheritAttrs' in instance.vnode.type && instance.vnode.type.inheritAttrs === false) {
```

**Review by TheAlexLichter — APPROVED** [review]
