### PR TITLE
fix(utils): include routes with children for generation

### LINKED ISSUE #4562: `nuxt generate` doesn't generate HTML file for pages with child routes
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/Justineo/nuxt-generate-bug](https://github.com/Justineo/nuxt-generate-bug)

### Steps to reproduce

1. Creating a project with `create-nuxt-app`
2. Create following pages:

  ```
  pages
  ├─ ...
  ├─ test
  │  └─ foo.vue
  └─ test.vue
  ```

3. Run `nuxt generate`

### What is expected ?

In `dist` directory, there will be independent entry HTML file for both `/test` and `/test/foo`:

```
pages
├─ ...
├─ test
│  └─ foo.html
└─ test.html
```

### What is actually happening?

Entry for route path `/test` is missing:

```
pages
├─ ...
└─ test
   └─ foo.html
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8315">#c8315</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by farnabaz**
`flatRoutes` function was skip all parent routes that have children. Parent routes was not generates in static generation, to  Take a look at #4562 to find more about the issue.
close #4562 & #4982

## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/utils/src/route.js [hunk 1]
```diff
@@ -9,22 +9,19 @@ export const flatRoutes = function flatRoutes (router, fileName = '', routes = [
...
     }
-    if (r.children) {
-      if (fileName === '' && r.path === '/') {
-        routes.push('/')
-      }
-
-      return flatRoutes(r.children, fileName + r.path + '/', routes)
-    }
-    fileName = fileName.replace(/\/+/g, '/')
+    fileName = (fileName + r.path + '/').replace(/\/+/g, '/')
```
Comment (pi0) [inline packages/utils/src/route.js:12]: Neat: I think now makes sense naming variable to `const route =`

**Comment by farnabaz** [comment]
@pi0 I think one of previous test was wrong, Look at these lines. This route should create three pages (exact behavior as `vue-router`)

https://github.com/nuxt/nuxt.js/pull/7761/files#diff-f20ead15adb68c21668ec1154f3ba2a2L44-R56

File: packages/utils/src/route.js [hunk 2]
```diff
@@ -4,24 +4,37 @@ import consola from 'consola'
...
+}
+
 export const flatRoutes = function flatRoutes (router, fileName = '', routes = []) {
   router.forEach((r) => {
     if ([':', '*'].some(c => r.path.includes(c))) {
       return
     }
-    fileName = (fileName + r.path + '/').replace(/\/+/g, '/')
+    if (r.children) {
+      return flatRoutes(getRouteChildrens(r), fileName + r.path + '/', routes)
```
Comment (manniL) [inline packages/utils/src/route.js]: nit: using template string here instead of string concatention
```suggestion
      return flatRoutes(getRouteChildrens(r), `${fileName}${r.path}/`, routes)
```

File: packages/utils/src/route.js [hunk 3]
```diff
@@ -4,24 +4,37 @@ import consola from 'consola'
 
 import { r } from './resolve'
 
+const getRouteChildrens = function (route) {
+  if (route.children.some(child => child.path === '')) {
```
Comment (manniL) [inline packages/utils/src/route.js:8]: nit: extracting the condition as variable and name it, e.g. 
`const routeHasChildWithEmptyPath = route.children.some(child => child.path === '')`

Probably something less verbose though

**Review by pi0 — APPROVED** [review]
LGTM. @clarkdo @atinux Would you please also confirm new behavior? (/foo is being added)

**Review by clarkdo — APPROVED** [review]

**Review by atinux — APPROVED** [review]
Nice work!
