### PR TITLE
fix(vue-app): remove trailing slash in vue-router non-strict mode

### LINKED ISSUE #5593: Modal post doesn't open inside index route but it does in different routes
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://codesandbox.io/s/2v4vyr850n](https://codesandbox.io/s/2v4vyr850n)

### Steps to reproduce

You have to go to these routes (or click the links in the index route):

`/timewall` - works
`/testing` - works
`/` - not working

After that, you need to click on the post card and it will open the modal. This won't happen inside the index route and will show you the error.

### What is expected ?

Open the post modal inside `/timewall` and `/`

### What is actually happening?

Trying to open the modal in index route, will throw this error:

`_vm.$refs.postModal is undefined`

### Additional comments?

I configured my nuxt.config.js file to add to the previous routes a children so it can access the `post/_slug.vue` template inside the routes. 

![2019-04-24 00_47_10-web-app [F__Desarrollos_Doki_web-app] - ..._nuxt.config.js [web-app] - PhpStorm.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/966fdbf0-6654-11e9-bc99-8390039d252a.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9096">#c9096</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix #5593 

According to https://github.com/vuejs/vue-router/blob/dev/src/create-route-map.js#L167 , `vue-router` will remove the trailing slash in non strict mode.

Imagine we have routes like and there is `NuxtChild` and `NuxtLink to='/test/post/1'` in `pages/test.vue`:

In non-strict mode, after we click link, the `route.matched[0]` is always `{ path: '/test', ... }`

```js
{
  path: "/test",
  name: "test",
  children: [{
    path: "post/:slug"
  }]
}
``` 

When we access `http://localhost:3000/test`, `routerViewKey` is always `/test` before and after clicking link.

But if we access `http://localhost:3000/test/`, the `routerViewKey` is `/test/` from [`this.route.path`](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt.js#L67). After clicking link, the `routerViewKey` is `/test` from [`this.$route.matched[0].path`](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/components/nuxt.js#L41), so `test.vue` will be destroyed and recreated which is incorrect.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/components/nuxt.js [hunk 1]
```diff
@@ -41,7 +41,8 @@ export default {
         return this.nuxtChildKey || compile(this.$route.matched[0].path)(this.$route.params)
       }
 
-      const Component = this.$route.matched[0] && this.$route.matched[0].components.default
+      const matchedRoute = this.$route.matched[0]
```
Comment (manniL) [inline packages/vue-app/template/components/nuxt.js]: Nit:

```suggestion
      const [matchedRoute] = this.$route.matched
```

**Review by pi0 — APPROVED** [review]

**Review by galvez — APPROVED** [review]
LGTM
