### PR TITLE
fix(nuxt): scan folder indices for middleware

### LINKED ISSUE #14358: Scan plugins from top level `/plugins` folder only
Similar to nuxt/framework#6025, this makes directory scanning simpler and more consistent between dirs. Plugins nested in dirs can be manually added with `plugins: []` in `nuxt.config` or a reexport to top level `plugins/` directory.

### LINKED ISSUE #25331: Scan `<subdir>/index` files for composables, plugins, middleware, etc.
### Describe the feature

This PR will align scanning behavior for `plugins` with existing behavior for e.g. composables or middleware by only scanning top-level folders by default.

https://github.com/nuxt/nuxt/blob/648ef069931336b8ee0c0e48fef3ee700ebc3dbe/packages/kit/src/plugin.ts#L23-L27

Related: https://github.com/nuxt/nuxt/pull/18418/files

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/25331
closes https://github.com/nuxt/nuxt/issues/14358
related: https://github.com/nuxt/nuxt/issues/12414

### 📚 Description

This moves ahead to undo the previous move we made to remove scanning of `middleware/*/index` files, in the interests of consistency.

It might be nice also to update behaviour for `components/` and `utils/` so things are fully consistent across the board (what do you think @antfu?).

### CODE REVIEW

File: packages/nuxt/src/core/app.ts [hunk 1]
```diff
@@ -179,7 +179,12 @@ export async function resolveApp (nuxt: Nuxt, app: NuxtApp) {
   app.middleware = []
   for (const config of reversedConfigs) {
     const middlewareDir = (config.rootDir === nuxt.options.rootDir ? nuxt.options : config).dir?.middleware || 'middleware'
-    const middlewareFiles = await resolveFiles(config.srcDir, `${middlewareDir}/*{${nuxt.options.extensions.join(',')}}`)
+    const middlewareFiles = await resolveFiles(config.srcDir, [
+      `${middlewareDir}/*{${nuxt.options.extensions.join(',')}}`,
+      ...nuxt.options.future.compatibilityVersion === 4
```
Comment (manniL) [inline packages/nuxt/src/core/app.ts:184]: Do we need a fine-grained flag for it too?

**Comment by antfu** [comment]
I would be happy to see that move, yes! Thanks

File: packages/nuxt/src/core/app.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/app.ts:184]: I don't think so, as I've provided a hook. The fine grained flags will be removed with v4 release but the hook will continue to work.

**Review by TheAlexLichter — APPROVED** [review]
