### PR TITLE
fix(nuxt): work around payload extraction issue

### LINKED ISSUE #22068: [nuxt] Cannot load payload  /_payload.json
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.0
- Builder:          vite
- User Config:      pages, debug, dev, modules, pwa, app, vue, ignore
- Runtime Modules:  @nuxt/devtools@0.2.5
- Build Modules:    -
------------------------------

### Reproduction

its a pretty big project, It always worked fine and all I did before this happened was running npm install

### Describe the bug

When using my nuxt site using a different domain navigating to other pages stops working

when I build my site and upload it to azure it comes available on multiple domains

1. the azure domain (Site works fine here)
2. Our domain with a special subdomain (usually its help.domain.app)

On our subdomain the website navigation stops working and spits out the following error:
image

### Additional context

_No response_

### Logs

```shell-script
build logs
https://hastebin.com/share/oyamipasuv.bash
```

### PR DESCRIPTION
**Pull request by TheAlexLichter**
### 🔗 Linked issue

Resolves #22068 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Due to changes from https://github.com/nuxt/nuxt/pull/21860, [`process.env.NUXT_PAYLOAD_EXTRACTION`](https://github.com/nuxt/nuxt/blob/fed5868184c6ec7256c114cb804253b8deacdf64/packages/nuxt/src/core/nitro.ts#L194) is set "too early" for mentioned changes to come into effect. To resolve it, I've used Nuxt's nitro config to check for the `static` override. This should be removed in the future (3.8 or so).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/nuxt.ts [hunk 1]
```diff
@@ -369,15 +369,16 @@ async function initNuxt (nuxt: Nuxt) {
 
   addModuleTranspiles()
 
-  // Init nitro
-  await initNitro(nuxt)
-
   // TODO: remove when app manifest support is landed in https://github.com/nuxt/nuxt/pull/21641
   // Add prerender payload support
-  if (useNitro().options.static && nuxt.options.experimental.payloadExtraction === undefined) {
+  if (nuxt.options.nitro?.static && nuxt.options.experimental.payloadExtraction === undefined) {
```
Comment (danielroe) [inline packages/nuxt/src/core/nuxt.ts:374]: I think we need to find another way to resolve. Nitro static presets need static behaviour even though this won't be set in the Nuxt options.

Comment (manniL) [reply packages/nuxt/src/core/nuxt.ts:374]: Oh, I see. Then let's chat about that 👍🏻

**Review by danielroe — APPROVED** [review]
