### PR TITLE
fix(nuxt): resolve shared externals to absolute paths

### LINKED ISSUE #31222: WARN  force closing dev worker after 5 seconds...
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.15.4
- CLI Version:      3.22.4
- Nitro Version:    2.11.1
- Package Manager:  bun@1.2.4
- Builder:          -
- User Config:      ssr, routeRules, scripts, vite, modules, headlessui, devtools, css, build, tailwindcss, fonts, icon, i18n, imports, runtimeConfig, compatibilityDate
- Runtime Modules:  @nuxtjs/tailwindcss@6.13.1, nuxt-headlessui@1.2.0, @nuxtjs/i18n@8.5.1, @nuxt/fonts@0.7.2, @vueuse/nuxt@11.0.3, @pinia/nuxt@0.5.4, nuxt-svgo@4.0.4, @nuxt/icon@1.4.10, @nuxt/scripts@0.9.5
- Build Modules:    -
------------------------------

### Describe the bug

At my wits end, can't even run my app locally anymore. Using bun run dev, getting this: 
```
$ nuxt dev
Nuxt 3.15.4 with Nitro 2.11.1                                                                                                                                                                         nuxi  3:22:51 PM
                                                                                                                                                                                                            3:22:51 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using default Tailwind CSS file                                                                                                                                                         nuxt:tailwindcss 3:22:53 PM
  ➜ DevTools: press Shift + Alt + D in the browser (v1.7.0)                                                                                                                                                 3:22:55 PM

ℹ Nuxt Icon server bundle mode is set to local                                                                                                                                                             3:22:56 PM   
✔ Vite client built in 80ms                                                                                                                                                                                3:22:57 PM   
✔ Vite client built in 80ms                                                                                                                                                                                3:22:57 PM   
✔ Vite server built in 1613ms                                                                                                                                                                              3:22:58 PM   
✔ Vite server built in 1613ms                                                                                                                                                                              3:22:58 PM   
✔ Nuxt Nitro server built in 1017 ms                                                                                                                                                                 nitro 3:23:00 PM   
✔ Nuxt Nitro server built in 1017 ms                                                                                                                                                                 nitro 3:23:00 PM   
ℹ Vite client warmed up in 2ms                                                                                                                                                                             3:23:00 PM   

 WARN  force closing dev worker after 5 seconds...           
```

Browser tab for some reason says Error: cannot access 'Hasher' before initialization. I only see the nuxt splash page (not the usual 500 error page or anything)

When building/deploying, I get Cannot access 'nativeFuncLength' before initialization.

I don't know where to begin! I rolled back to a commit that worked last week and getting the same error. Same on my coworkers machine. 

Please help! I can't reproduce this and can't really provide my app because its a work thing and huge anyway so no idea where things went wrong. But as I said, things were fine last week (after fixing an issue with ohash/h3 and using override to use version 1.15.0)


### Additional context

Additional context to my previous issue from last week, if related, can be found at this link to the nuxt discord help thread: https://discord.com/channels/473401852243869706/1343546685938208799

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/31222

### 📚 Description

previous implementation in https://github.com/nuxt/nuxt/pull/22812 seems was no longer working. so this PR moves marking as external to our deep imports plugin

it marks as external but with absolute path so that when nitro resolves, the deduplication will only occur with the same version of the library.

it does adds a bit to the `server.mjs` (so not fully deduplicating as before) but likely a cost worth paying

### CODE REVIEW

File: packages/nuxt/src/core/plugins/resolve-deep-imports.ts [hunk 1]
```diff
@@ -29,12 +32,27 @@ export function resolveDeepImportsPlugin (nuxt: Nuxt): Plugin {
         resolvedConditions.add('require')
       }
       conditions = [...resolvedConditions]
+
+      const { runtimeDependencies = [] } = await tryImportModule<typeof import('nitro/runtime/meta')>('nitro/runtime/meta', {
+        url: nuxt.options.modulesDir.map(d => directoryToURL(d)),
```
Comment (pi0) [inline packages/nuxt/src/core/plugins/resolve-deep-imports.ts:37]: (nitro is explicit dep, it avoid hoisting issues with nitro pkg itself)

```suggestion
        url: import.meta.url,
```

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/core/plugins/resolve-deep-imports.ts [hunk 2]
```diff
@@ -34,7 +34,7 @@ export function resolveDeepImportsPlugin (nuxt: Nuxt): Plugin {
       conditions = [...resolvedConditions]
 
       const { runtimeDependencies = [] } = await tryImportModule<typeof import('nitro/runtime/meta')>('nitro/runtime/meta', {
-        url: nuxt.options.modulesDir.map(d => directoryToURL(d)),
+        url: new URL(import.meta.url),
```
Comment (pi0) [inline packages/nuxt/src/core/plugins/resolve-deep-imports.ts:37]: We have fastpath in exsolve BTW: https://github.com/unjs/exsolve/blob/main/src/resolve.ts#L340
