### PR TITLE
fix(webpack): transpile ufo

### LINKED ISSUE #8838: Error 'SCRIPT1053' occurs on IE11 (nuxt: v2.15.0)
### Versions

- nuxt: v2.15.0
- node: v14.15.4
- IE11 (Windows 10 Pro 20H2)

### Reproduction

This is a minimal example works with no error on IE11.
https://github.com/voidproc/example-nuxt-ie

However, an error 'SCRIPT1053: Const must be initialized' occurs when remove `transpile: ['ufo']` setting in `nuxt.config.js`.

### PR DESCRIPTION
**Pull request by kn3ny**
Add `ufo` module, instead of `@nuxt/ufo`, to the default target of transpile.

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

There is a commit https://github.com/nuxt/nuxt.js/commit/7529d65d75a1f943817cd5683e21335d48891b6b that migrates from `@nuxt/ufo` to `ufo`. However, it seems migration of the configuration of transpiling was not included.
Since `ufo` will not be transpiled by default, user's nuxt.js app will be broken on old browsers such as IE.

Resolves: #8838, #8839

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/webpack/src/config/base.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ export default class WebpackBaseConfig {
     return [
       /\.vue\.js/i, // include SFCs in node_modules
       /consola\/src/,
-      /@nuxt[/\\]ufo/, // exports modern syntax for browser field
+      /ufo/, // exports modern syntax for browser field
```
Comment (kn3ny) [inline packages/webpack/src/config/base.js:76]: Should I need to change `/^ufo$/`?

Comment (pi0) [reply packages/webpack/src/config/base.js:76]: ufo should be fine. All dependant packages except tailwind seem migrated already

**Review by pi0 — APPROVED** [review]
Thanks!

File: packages/webpack/src/config/base.js (hunk 1 above)
Comment (kn3ny) [reply packages/webpack/src/config/base.js:76]: I see. Thank you!
