### PR TITLE
fix(nuxt): respect layer order for other layer plugins

### LINKED ISSUE #23123: [Bug] Plugin Registration Order is not deterministic when using layers
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.1
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-g42wkd?file=nuxt.config.ts

### Describe the bug

The order of plugin execution is not correct when using layers. Plugins that are defined in lower layers execute after plugins defined in higher layers. This causes incorrect behavior when a plugin override is necessary. In the provided repo a use case of overriding the same entity from a higher level is not possible due to this issue.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23123

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This builds on work done by @userquin in https://github.com/nuxt/nuxt/pull/22889 to ensure that other plugins specified directly in nuxt config by layers are loaded in sequence matching layer order.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
Haven't tested but looks good 💯

File: packages/nuxt/src/core/app.ts [hunk 1]
```diff
@@ -141,6 +139,14 @@ async function resolveApp (nuxt: Nuxt, app: NuxtApp) {
     ].map(plugin => normalizePlugin(plugin as NuxtPlugin)))
   }
 
+  // Add back plugins not specified in layers or user config
+  for (const p of nuxt.options.plugins) {
+    const plugin = normalizePlugin(p)
+    if (!app.plugins.some(p => p.src === plugin.src)) {
+      app.plugins.unshift(plugin)
```
Comment (dargmuesli) [inline packages/nuxt/src/core/app.ts:146]: Maybe this should be `push` instead of `unshift`? (https://github.com/nuxt/nuxt/issues/23163)
