### PR TITLE
fix(nuxt): compatible route object for custom external routes

### LINKED ISSUE #19259: "[Vue Router warn]: No match found for location with path" on ANY NuxtLink with an external url
### Describe the feature

right now in Nuxt 3.2.2, any usage of NuxtLink to an external url gives a warning "[Vue Router warn]: No match found for location with path <path>".  

Even if you look at the example provided in the documentation and you look at the developer console, you'll see the warnings once the page loads up
https://nuxt.com/docs/examples/routing/nuxt-link#nuxtlink

This is unintuitive, because obviously external links will not be available for the underlying vue-router and it won't know about them.  The project I am working on is a conversion of a legacy site, and so because of that we have to link to external pages ALOT within the Nuxt part of the application to jump back and forth with the legacy site.  That means every SPA page has tons of warnings in the console.  

The documentation shows examples of using NuxtLink for both internal and external links, and it even has an "external" property for edge cases.  It would be really great if we could somehow disable those warnings when using external links or manually setting the external property on the NuxtLink component.

Right now the alternative for me is to render two completely different components, one that is a NuxtLink, and one that is a simple anchor tag.  This works, but isn't as neat as just using NuxtLink as it is currently documented.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/19259

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We were calling `router.resolve()` on known external routes. We can either completely omit this route or we can parse it as we are doing in the universal router plugin. (I've chosen the latter as it's a non-breaking change if someone is already using the universal router + custom external links, but other thoughts welcome.)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/components/nuxt-link.ts [hunk 1]
```diff
@@ -249,10 +249,25 @@ export function defineNuxtLink (options: NuxtLinkOptions) {
...
+          const url = href && parseURL(href)
           return slots.default({
             href,
             navigate,
-            route: router.resolve(href!),
+            route: url
+              ? {
+                  path: url.pathname,
+                  fullPath: url.pathname,
+                  query: parseQuery(url.search),
```
Comment (pi0) [inline packages/nuxt/src/app/components/nuxt-link.ts:260]: Small perf: this could be a getter

File: packages/nuxt/src/app/components/nuxt-link.ts [hunk 2]
```diff
@@ -249,10 +249,25 @@ export function defineNuxtLink (options: NuxtLinkOptions) {
...
           }
+          const url = href && parseURL(href)
           return slots.default({
             href,
             navigate,
-            route: router.resolve(href!),
+            route: url
+              ? {
+                  path: url.pathname,
+                  fullPath: url.pathname,
```
[the remark this answers is not in the document]
Comment (danielroe) [reply packages/nuxt/src/app/components/nuxt-link.ts:259]: that would be a nice perf. do you think we should make `route` itself a getter that calls `parseURL`?

[the remark this answers is not in the document]
Comment (pi0) [reply packages/nuxt/src/app/components/nuxt-link.ts:259]: Also better!

File: packages/nuxt/src/app/components/nuxt-link.ts [hunk 3]
```diff
@@ -249,16 +249,39 @@ export function defineNuxtLink (options: NuxtLinkOptions) {
...
+
+          Object.defineProperty(props, 'route', {
+            get () {
+              if (!href) { return undefined }
+
+              const url = parseURL(href)
+              return {
+                path: url.pathname,
+                fullPath: url.pathname,
+                query: parseQuery(url.search),
```
Comment (pi0) [inline packages/nuxt/src/app/components/nuxt-link.ts:271]: Even if `.route` accessor is lazy, sub propers (especially this one could be). It might not have significant performance overhead but can also have when there are dozens of components rendering concurrently so probably micro-optimization worth :)

Comment (danielroe) [reply packages/nuxt/src/app/components/nuxt-link.ts:271]: The conditions required for this to be hit are that we are 1) using pages module, 2) using a custom link, 3) using an external link, 4) accessing `route` in this slot. I don't see there being dozens of components matching those conditions rendering concurrently; I think in most cases an external link will simply handle the case of the `href` rather than the route object at all.

My thought is that adding the code to handle the slight perf opt of accessing route.query lazily will add more kb to the bundle than is really worth it. But you think this is a much more likely scenario?

Comment (pi0) [reply packages/nuxt/src/app/components/nuxt-link.ts:271]: I agree. But this special kind of component can be used by a CMS / Project and repeated.  Code diff is alow low btw `get query: () => parseQuery`. This kind of optimization is not odd (`error.stack` for instance is also lazy even tough it is not always accessed by users)... So feel free to judge either make change or ignore my comment :p
