### PR TITLE
fix(vite): unset `optimizeDeps.include` for server environment

### LINKED ISSUE #33538: [nightly] vite-env-api: `The entry point "ufo" cannot be marked as external`
### Environment

- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     4.2.0-29350737.ca3347b3
- CLI Version:      3.29.4-20251009-171814-0915ec9
- Nitro Version:    2.12.7
- Package Manager:  pnpm@10.18.3
- Builder:          -
- User Config:      devtools, modules, experimental, i18n
- Runtime Modules:  @nuxtjs/i18n@10.1.1
- Build Modules:    -

### Reproduction

https://github.com/OrbisK/nuxt-vite-env-api-reproduction

### Describe the bug

`pnpm dev` fails with:

```
✔ Vite dev server built in 57ms                                                                                                                                                                                        2:42:34 PM
✘ [ERROR] The entry point "ufo" cannot be marked as external


 ERROR  [unhandledRejection] Error during dependency optimization:                                                                                                                                                      2:42:35 PM

✘ [ERROR] The entry point "ufo" cannot be marked as external



    at failureErrorWithLog (node_modules/.pnpm/esbuild@0.25.11/node_modules/esbuild/lib/main.js:1467:15)
    at node_modules/.pnpm/esbuild@0.25.11/node_modules/esbuild/lib/main.js:926:25
    at node_modules/.pnpm/esbuild@0.25.11/node_modules/esbuild/lib/main.js:1345:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

✔ Nuxt Nitro server built in 1644ms   
```

### Additional context

_No response_

### Logs

```shell-script
✔ Vite dev server built in 57ms                                                                                                                                                                                        2:42:34 PM
✘ [ERROR] The entry point "ufo" cannot be marked as external


 ERROR  [unhandledRejection] Error during dependency optimization:                                                                                                                                                      2:42:35 PM

✘ [ERROR] The entry point "ufo" cannot be marked as external



    at failureErrorWithLog (node_modules/.pnpm/esbuild@0.25.11/node_modules/esbuild/lib/main.js:1467:15)
    at node_modules/.pnpm/esbuild@0.25.11/node_modules/esbuild/lib/main.js:926:25
    at node_modules/.pnpm/esbuild@0.25.11/node_modules/esbuild/lib/main.js:1345:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

✔ Nuxt Nitro server built in 1644ms
```

### PR DESCRIPTION
**Pull request by Flo0806**
### 🔗 Linked issue

Fixes: #33538

### Summary
  Fixes dependency optimization errors in Vite by excluding Nuxt virtual modules from `optimizeDeps`.

 ### Summary
  Fixes Vite dependency optimization errors by properly configuring `optimizeDeps` for the client environment.

  ### Problem
  When using Vite's environment API, users encountered errors like:
  ✘ [ERROR] The entry point "ufo" cannot be marked as external
  Error during dependency optimization

  **Root Cause:**
  In Vite, `optimizeDeps` configuration is **not inherited** by environments ([see Vite 
  docs](https://vite.dev/guide/api-environment)). The `clientEnvironment()` function in `client.ts` defines the proper
  `optimizeDeps` configuration, but it wasn't being applied to the client environment in `configEnvironment()`.

  ### Solution

**1. `/packages/vite/src/plugins/environments.ts`:**
Explicitly set `optimizeDeps` from `clientEnvironment()` configuration:

```ts
  const clientEnv = clientEnvironment(nuxt, entry)
  config.optimizeDeps = clientEnv.optimizeDeps
```

**2. /packages/vite/src/shared/client.ts:**
Extended the optimizeDeps.exclude list to include all Nuxt virtual modules (#imports, #app, #build/*, etc.) that are
resolved by Nuxt's own module resolution and should not be optimized by Vite.

### Test Plan

- Run test suite - all tests pass
- Verify "entry point cannot be marked as external" error is resolved
- Verify no "#imports" or "#build/*" resolution errors

### References

- Vite Environment API: https://vite.dev/guide/api-environment
- Original issue reproduction: https://github.com/OrbisK/nuxt-vite-env-api-reproduction

### CODE REVIEW

File: packages/vite/src/shared/client.ts [hunk 1]
```diff
@@ -47,8 +50,17 @@ export const clientEnvironment = (nuxt: Nuxt, entry: string) => {
...
         '#app-manifest',
+        // these should all be valid ESM
+        '#imports',
+        '#app',
+        '#build',
+        '#build/*',
+        '#components',
+        '#head',
+        'virtual:nuxt:',
+        'virtual:nuxt:*',
```
Comment (danielroe) [inline packages/vite/src/shared/client.ts:63]: @Flo0806 was there a particular reason you added these?

Comment (Flo0806) [reply packages/vite/src/shared/client.ts:63]: Yes, without these many tests was failing, because the client part was searching for these imports - and they doesn't exists. (`pnpm test:runtime`)

**Review by danielroe — APPROVED** [review]
