### PR TITLE
fix(nuxt): re-execute callOnce during HMR

### LINKED ISSUE #33788: `callOnce` does not hot reload when the inner function is changed during development
### Environment

- Operating System: `Darwin`
- Nuxt Version:     `4.2.1`
- CLI Version:      `3.30.0`
- Nitro Version:    `2.12.9`
- Package Manager:  `bun@1.2.21`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Repo Link: https://stackblitz.com/edit/github-qz7tek96?file=app%2Fapp.vue

During dev mode in stackblitz:

1. `callOnce` sucessfully works, state (`count.value`) changes from 0 -> 1
2. Change line 11 as follows:

```diff
- count.value += 1;
+ count.value += 2;
```

3. `callOnce` does _not_ run again. The expected value is where `count.value !== 1`.

### Describe the bug

When editing the function of `callOnce` during development mode, on save it should hot reload and run the new (changed) function, or do a page refresh. It does not, which is unexpected behaviour. 

### Additional context

I wasn't sure if this should be an issue, but I got the go ahead at https://github.com/nuxt/nuxt/discussions/33785
Thanks @cernymatej 😊  

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix https://github.com/nuxt/nuxt/issues/33788

### 📚 Description

This PR re-executes `callOnce` during HMR.

### CODE REVIEW

File: packages/nuxt/src/app/composables/once.ts [hunk 1]
```diff
@@ -40,7 +42,11 @@ export async function callOnce (...args: any): Promise<void> {
 
   // If key already ran
   if (nuxtApp.payload.once.has(_key)) {
-    return
+    if (import.meta.dev && _isHmrUpdating) {
+      // Allow re-execution during HMR
+    } else {
+      return
+    }
```
Comment (danielroe) [inline packages/nuxt/src/app/composables/once.ts]:
```suggestion
    // Allow re-execution during HMR
    if (!import.meta.dev || !_isHmrUpdating) {
      return
    }
```

**Comment by cernymatej** [comment]
Wouldn't this re-execute on **any** javascript HMR update, though?
If so, I'm not sure that's desired as it could cause various problems depending on what people use the function for.

**Comment by huang-julien** [comment]
> Wouldn't this re-execute on any javascript HMR update, though?
If so, I'm not sure that's desired as it could cause various problems depending on what people use the function for.

If Component A with `callOnce` is updated, `callOnce` will re-execute. If there's a component B in the dependency tree with another callOnce, it will re-execute too. 
But if B is not a dependency of A, `callOnce` friom B will not re-execute

**Review by danielroe — APPROVED** [review]
