### PR TITLE
fix(nuxt): default scanned layer components to priority `0`

### LINKED ISSUE #972: Nuxt 3.7.0 Warning: Two component files resolving to the same name
Just upgraded my Docus project to [Nuxt 3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0). On startup and build I now see a lot of "Two component files resolving to the same name" warnings. Despite that, everything is working as expected.

```
❯ npm run dev

> docus-starter@0.1.0 dev
> nuxi dev

Nuxt 3.7.0 with Nitro 2.6.2                                                                                                                                                                                                        10:35:22 AM
                                                                                                                                                                                                                                   10:35:22 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

✔ Nuxt DevTools is enabled v0.8.1 (experimental)                                                                                                                                                                                   10:35:25 AM

 WARN  [nuxt] Two component files resolving to the same name Logo:                                                                                                                                                                 10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt-themes/docus/components/app/Logo.vue
 - <redacted>/developer-documentation/components/Logo.vue


 WARN  [nuxt] Two component files resolving to the same name Ellipsis:                                                                                                                                                             10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt-themes/elements/components/globals/Ellipsis.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/docus/components/app/Ellipsis.vue


 WARN  [nuxt] Two component files resolving to the same name SourceLink:                                                                                                                                                           10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt-themes/elements/components/globals/SourceLink.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/docus/components/docs/SourceLink.vue


 WARN  [nuxt] Two component files resolving to the same name DocumentDrivenNotFound:                                                                                                                                               10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/docus/components/app/DocumentDrivenNotFound.vue


 WARN  [nuxt] Two component files resolving to the same name ProseA:                                                                                                                                                               10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseA.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseA.vue


 WARN  [nuxt] Two component files resolving to the same name ProseBlockquote:                                                                                                                                                      10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseBlockquote.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseBlockquote.vue


 WARN  [nuxt] Two component files resolving to the same name ProseCode:                                                                                                                                                            10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseCode.vue


 WARN  [nuxt] Two component files resolving to the same name ProseCodeInline:                                                                                                                                                      10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseCodeInline.vue


 WARN  [nuxt] Two component files resolving to the same name ProseEm:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseEm.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseEm.vue


 WARN  [nuxt] Two component files resolving to the same name ProseH1:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH1.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseH1.vue


 WARN  [nuxt] Two component files resolving to the same name ProseH2:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH2.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseH2.vue


 WARN  [nuxt] Two component files resolving to the same name ProseH3:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH3.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseH3.vue


 WARN  [nuxt] Two component files resolving to the same name ProseH4:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH4.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseH4.vue


 WARN  [nuxt] Two component files resolving to the same name ProseH5:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH5.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseH5.vue


 WARN  [nuxt] Two component files resolving to the same name ProseH6:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseH6.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseH6.vue


 WARN  [nuxt] Two component files resolving to the same name ProseHr:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseHr.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseHr.vue


 WARN  [nuxt] Two component files resolving to the same name ProseImg:                                                                                                                                                             10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseImg.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseImg.vue


 WARN  [nuxt] Two component files resolving to the same name ProseLi:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseLi.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseLi.vue


 WARN  [nuxt] Two component files resolving to the same name ProseOl:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseOl.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseOl.vue


 WARN  [nuxt] Two component files resolving to the same name ProseP:                                                                                                                                                               10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseP.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseP.vue


 WARN  [nuxt] Two component files resolving to the same name ProseStrong:                                                                                                                                                          10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseStrong.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseStrong.vue


 WARN  [nuxt] Two component files resolving to the same name ProseTable:                                                                                                                                                           10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTable.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseTable.vue


 WARN  [nuxt] Two component files resolving to the same name ProseTbody:                                                                                                                                                           10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTbody.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseTbody.vue


 WARN  [nuxt] Two component files resolving to the same name ProseTd:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTd.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseTd.vue


 WARN  [nuxt] Two component files resolving to the same name ProseTh:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTh.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseTh.vue


 WARN  [nuxt] Two component files resolving to the same name ProseThead:                                                                                                                                                           10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseThead.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseThead.vue


 WARN  [nuxt] Two component files resolving to the same name ProseTr:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseTr.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseTr.vue


 WARN  [nuxt] Two component files resolving to the same name ProseUl:                                                                                                                                                              10:35:26 AM

 - <redacted>/developer-documentation/node_modules/@nuxt/content/dist/runtime/components/Prose/ProseUl.vue
 - <redacted>/developer-documentation/node_modules/@nuxt-themes/typography/components/global/ProseUl.vue

ℹ Vite client warmed up in 4762ms                                                                                                                                                                                                  10:35:32 AM
✔ Nitro built in 3022 ms                                                                                                                                                                                                     nitro 10:35:33 AM
```

### LINKED ISSUE #23028: console warning when overriding layer component
A regression in 3.7.0, and partially resolved (for module component directories) in https://github.com/nuxt/nuxt/pull/22882.

```
WARN  [nuxt] Two component files resolving to the same name [MODULE_NAME]
```

We need to give layer component directories a default priority as well.

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23028
resolves https://github.com/nuxt-themes/docus/issues/972

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Follow-up on https://github.com/nuxt/nuxt/pull/22882, this gives layer components a priority of `0` by default so they can overridden by components in final nuxt project.

This doesn't change behaviour, just suppresses the warning log in this case.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/module.ts [hunk 1]
```diff
@@ -72,7 +73,7 @@ export default defineNuxtModule<ComponentsOptions>({
     nuxt.hook('app:resolve', async () => {
       // components/ dirs from all layers
       const allDirs = nuxt.options._layers
-        .map(layer => normalizeDirs(layer.config.components, layer.config.srcDir))
+        .map(layer => normalizeDirs(layer.config.components, layer.config.srcDir, { priority: layer.config.srcDir === nuxt.options.srcDir ? 1 : 0 }))
```
Comment (pi0) [inline packages/nuxt/src/components/module.ts:76]: As another idea, we could give main project 0 and layer -1, -2, -3 etc (it also doesn't requires reverse i guess)

**Review by pi0 — APPROVED** [review]
