### PR TITLE
fix(vue-renderer): fix meta injection when ssr renderer generates a spa page

### LINKED ISSUE #567: Title not updated on page redirect from SSR
It seems that between 2.3.3 and 2.3.4 a bug was introduced that prevents the page title to be updated on a redirect from an SSR page. Might this be caused by #563? :-/

---
Reproduce
1. Clone this repo: https://gitlab.com/njam/repro-vuemeta-redirect-title ([relevant commit](https://gitlab.com/njam/repro-vuemeta-redirect-title/-/commit/6c99904e417795f3effe586a783096e1a7c0351c))
```
git clone https://gitlab.com/njam/repro-vuemeta-redirect-title.git
cd repro-vuemeta-redirect-title
```
2. Build and serve the project:
```
yarn install
yarn run generate
npx serve ./dist
```
3. Open the page: http://localhost:5000 
4. Result:
  Expected: Browser redirects to `/foo`, title is "foo!"
  Actual: Browser redirects to `/foo`, title is "localhost:5000/"

### PR DESCRIPTION
**Pull request by pimlie**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Resolves: https://github.com/nuxt/vue-meta/issues/567

## Description

On nuxt generate in universal mode normally all pages are `serverRendered: true`, but redirects will be generated as a spa. This PR makes sure that vue-meta is aware of that as well and doesnt add its own ssr attributes.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-renderer/src/renderers/ssr.js [hunk 1]
```diff
@@ -111,12 +111,17 @@ export default class SSRRenderer extends BaseRenderer {
...
     let HEAD = ''
+    let metaInjectorOptions
 
     // Inject head meta
     // (this is unset when features.meta is false in server template)
     const meta = renderContext.meta && renderContext.meta.inject()
     if (meta) {
-      HEAD += meta.title.text() + meta.meta.text()
+      metaInjectorOptions = {
+        appId: renderContext.nuxt.serverRendered ? renderContext.meta.getOptions().ssrAppId : '1'
```
Comment (pi0) [inline packages/vue-renderer/src/renderers/ssr.js:121]: It seems like a loopback option passing. Can't we have something like `meta.inject(serverRendered)` in L118?

**Review by pi0 — APPROVED** [review]
