### PR TITLE
fix: allow relative public paths

### LINKED ISSUE #8863: Custom publicPath not working with electron
**Error message**: v2.15.0 ChunkLoadError: Loading chunk 2 failed. (works with v2.14)

### Versions
- nuxt: v2.15.0
- electron: v11.2.3

It works with nuxt-v2.14.12.

### Reproduction
I made a minimum code to reproduce.
https://github.com/tmtk75/nuxt-2-15-reproduce

### Steps to reproduce
You can reproduce with https://github.com/tmtk75/nuxt-2-15-reproduce.
```
yarn && yarn clean && yarn build && yarn start
```

### What is Expected?
It works even with v2.15 as v2.14.
Otherwise, there is another way or a workaround with v2.15.

### What is actually happening?
I can see `ChunkLoadError: Loading chunk 2 failed.` on DevTools when application is launching.

screenshot

### PR DESCRIPTION
**Pull request by danielroe**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
closes #8863

## Checklist:
- [x] I have added tests to cover my changes
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/utils/src/lang.js [hunk 1]
```diff
@@ -10,10 +10,16 @@ export const isNonEmptyString = obj => Boolean(obj && isString(obj))
 
 export const isPureObject = obj => !Array.isArray(obj) && typeof obj === 'object'
 
+// Replace once ufo exports isRelative
 export const isUrl = function isUrl (url) {
   return ['http', '//'].some(str => url.startsWith(str))
 }
 
+// Replace once ufo exports isRelative
+export function isRelative (url) {
```
Comment (pi0) [inline packages/utils/src/lang.js:19]: We can support this in ufo apart from relative resolution support :)

File: packages/utils/src/lang.js [hunk 2]
```diff
@@ -10,10 +10,16 @@ export const isNonEmptyString = obj => Boolean(obj && isString(obj))
 
 export const isPureObject = obj => !Array.isArray(obj) && typeof obj === 'object'
 
+// Replace once ufo exports isRelative
```
Comment (pi0) [inline packages/utils/src/lang.js:13]: This can be now hasProtocol(.., true(

File: packages/config/src/options.js [hunk 3]
```diff
@@ -215,6 +215,7 @@ export function getNuxtConfig (_options) {
 
   options.build.publicPath = options.build.publicPath.replace(/([^/])$/, '$1/')
   options.build._publicPath = options.build._publicPath.replace(/([^/])$/, '$1/')
+  options.build._publicPath = options.build._publicPath.replace(/^\.\//, '/')
```
Comment (pi0) [inline packages/config/src/options.js:218]: Can be chained with L217

File: packages/utils/src/lang.js (hunk 1 above)
Comment (danielroe) [reply packages/utils/src/lang.js:19]: Linking: https://github.com/nuxt-contrib/ufo/pull/17

Comment (pi0) [reply packages/utils/src/lang.js:19]: + ufo@0.6.9

File: packages/config/src/options.js [hunk 4]
```diff
@@ -452,10 +452,12 @@ export function getNuxtConfig (_options) {
...
   // App config (internal for nuxt2 at this stage)
   const useCDN = isUrl(options.build.publicPath) && !options.dev
+  const isRelativePublicPath = isRelative(options.build.publicPath)
+
   options.app = defu(options.app, {
     basePath: options.router.base,
-    assetsPath: useCDN ? '/' : joinURL(options.router.base, options.build.publicPath),
-    cdnURL: useCDN ? options.build.publicPath : null
+    assetsPath: useCDN || isRelativePublicPath ? '/' : joinURL(options.router.base, options.build.publicPath),
+    cdnURL: useCDN || isRelativePublicPath ? options.build.publicPath : null
```
Comment (pi0) [inline packages/config/src/options.js:460]: This is logically wrong. relative url is not cdn...

Comment (danielroe) [reply packages/config/src/options.js:460]: good point. to implement this though with `assetsPath` we would have to change some logic to avoid urlJoining the router base to relative path - happy with that?

Comment (danielroe) [reply packages/config/src/options.js:460]: ah - no, I'm wrong - I forgot https://github.com/nuxt-contrib/ufo/pull/15 hadn't yet been merged...

Comment (pi0) [reply packages/config/src/options.js]: support for falsy base added in ufo@0.6.10

File: test/dev/basic.relative.test.js [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    const config = await loadFixture('basic', {
+      dev: false,
+      build: {
+        publicPath: './_nuxt/'
+      }
+    })
+    nuxt = new Nuxt(config)
+    await nuxt.ready()
+
+    const builder = new Builder(nuxt)
```
Comment (pi0) [inline test/dev/basic.relative.test.js:45]: Building fixtures over and over costs. Can we please use runtimeConfig to check intended behavior in production?

File: packages/config/src/options.js [hunk 6]
```diff
@@ -214,7 +214,7 @@ export function getNuxtConfig (_options) {
   }
 
   options.build.publicPath = options.build.publicPath.replace(/([^/])$/, '$1/')
-  options.build._publicPath = options.build._publicPath.replace(/([^/])$/, '$1/')
+  options.build._publicPath = options.build._publicPath.replace(/([^/])$/, '$1/').replace(/^\.\//, '/')
```
[the remark this answers is not in the document]
Comment (danielroe) [reply packages/config/src/options.js]: Should be better now. Could extract as a util if we feel it would improve readability.

**Review by pi0 — APPROVED** [review]
