### PR TITLE
fix(nuxt): unset context after app is created

### LINKED ISSUE #14719: automatically call nuxt hooks with implicit nuxt context
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-t5twtq-b3tflp?file=plugin%2Fserver.server.ts,nuxt.config.ts

500
nuxt instance unavailable

### Describe the bug

useNuxtApp doesn't work in lifecycle hooks on server side

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #19623: cross-request state pollution when `useAsyncData` is used in a plugin
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.29.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
-----------------------------

### Reproduction

https://github.com/huang-julien/nuxt/tree/test/xrps-server-component 
This repo contains the content of https://github.com/nuxt/nuxt/pull/19605
Run the fixtures in dev and go to `/islands`
Refresh 5-6 time, you should see that `PureComponent` get replaced by the result of `AsyncServerComponent`

You can also do it at `/` but you'd need to leave your finger on F5 for 2-3sec.

Check the console. There's 2 value, they should always be the same. The first one is an array length, the second one a Set size.

### Describe the bug

When there's a very  high rate of request with sync component server side (just leave you're finger on F5), sometimes the app instance retrieved from unctx with `useNuxtApp` does not belong to the current instance of vue App.

It seems that this does not apply to pages rendering but only when requesting for server components.

### Additional context

Found when working on https://github.com/nuxt/nuxt/pull/19605. It is way easier to reproduce it with async components

discussed with @danielroe 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/19623
resolves https://github.com/nuxt/nuxt/issues/14719

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We can unset the nuxt app context after initialising it and calling each hook. It should be safe, and appears to resolve the linked reproduction.

This calls `app:created` and `app:error` (the only two server Nuxt hooks) with implicit Nuxt context, resolving https://github.com/nuxt/nuxt/issues/14719, though the normal caveats apply (the context will be lost within a hook after the first await).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/entry.ts [hunk 1]
```diff
@@ -30,11 +31,19 @@ if (process.server) {
 
     const nuxt = createNuxtApp({ vueApp, ssrContext })
 
+    async function contextCaller (hooks: HookCallback[], args: any[]) {
+      for (const hook of hooks) {
+        nuxtAppCtx.set(nuxt)
+        await hook(...args)
```
Comment (pi0) [inline packages/nuxt/src/app/entry.ts:37]: I think we might need to use `ctx.call` (otherwise same concurrent ctx sharing problem can happen during promise resolution)

Comment (danielroe) [reply packages/nuxt/src/app/entry.ts]: okay, using `.call`.

File: packages/nuxt/src/app/entry.ts [hunk 2]
```diff
@@ -30,11 +31,17 @@ if (process.server) {
...
+    async function contextCaller (hooks: HookCallback[], args: any[]) {
+      for (const hook of hooks) {
+        await nuxtAppCtx.call(nuxt, () => hook(...args))
+      }
+    }
+
     try {
       await applyPlugins(nuxt, plugins)
-      await nuxt.hooks.callHook('app:created', vueApp)
+      await nuxt.hooks.callHookWith(contextCaller, 'app:created', vueApp)
```
Comment (pi0) [inline packages/nuxt/src/app/entry.ts:42]: Something else i'm wondering is that we probably only need this for server-side only. It can be a breaking change for client-side as there, we have context always available assuming there is one nuxt instance. 

Also we could directly patch `nuxt.callHook` with contextCaller wdyt?

Comment (danielroe) [reply packages/nuxt/src/app/entry.ts:42]: Yes, this change only affects the server side.

As for patching, that's a nice idea. Will update.

File: packages/nuxt/src/app/nuxt.ts [hunk 3]
```diff
@@ -187,6 +187,17 @@ export function createNuxtApp (options: CreateOptions) {
...
   nuxtApp.hook = nuxtApp.hooks.hook
+
+  if (process.server) {
+    async function contextCaller (hooks: HookCallback[], args: any[]) {
+      for (const hook of hooks) {
+        await nuxtAppCtx.call(nuxtApp, () => hook(...args))
+      }
+    }
+    // Patch callHook to preserve NuxtApp context on server
+    nuxtApp.hooks.callHook = (name: any, ...args: any[]) => nuxtApp.hooks.callHookWith(contextCaller, name, ...args)
```
Comment (pi0) [inline packages/nuxt/src/app/nuxt.ts:198]: For followup, we could support `setCaller` for hookable library https://github.com/unjs/hookable/issues/74

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/app/nuxt.ts (hunk 3 above)
Comment (pi0) [reply packages/nuxt/src/app/nuxt.ts:198]:
```suggestion
    // TODO: Refactor after https://github.com/unjs/hookable/issues/74
    nuxtApp.hooks.callHook = (name: any, ...args: any[]) => nuxtApp.hooks.callHookWith(contextCaller, name, ...args)
```

**Comment by idflood** [comment]
@danielroe the changes with the new `if (process.server)` condition here "broke" my current [data persisting solution](https://github.com/nuxt/nuxt/issues/18615#issuecomment-1413693370) given in #18615 .

I don't know if there is something to be done here, or if there is now a better way to persist data. For now I will revert to 3.3.1 but I'm curious to know if you have any suggestion to implement this kind of global shared data for nuxt generate.

**Comment by danielroe** [comment]
@idflood `app:created` should still be called. The issue you're experiencing is a regression which should be resolved in https://github.com/nuxt/nuxt/pull/19969 or possibly sooner in https://github.com/unjs/hookable/pull/79.

**Comment by idflood** [comment]
@danielroe Thanks a lot, you are awesome 👍 I confirm #19969 fixes this issue : )

**Comment by danielroe** [comment]
@idflood This should now be resolved with the latest version of `hookable` via https://github.com/unjs/hookable/pull/79. You should be able to get it by explicitly installing the latest version or by refreshing your lockfile.

Let me know if not.
