### PR TITLE
fix(nuxt): transform client fallbacks directly on SFCs

### LINKED ISSUE #20833: NuxtClientFallback hydration broken in webpack build
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.1.1
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

- run `npx cross-env TEST_BUILDER=webpack pnpm nuxi build .\test\fixtures\basic\` on nuxt repo
- run it there will be a hydration issue. VNode will not be mounted correctly

### Describe the bug

A silent bug (no warning or error in the console). When using wbpack as a builder, `NuxtClientFallback` has a strange behavior, mounting its DOM node without discarding the old nodes

### Additional context

found with https://github.com/nuxt/nuxt/pull/20336

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue
fix #20833 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Hi :wave: this PR fix an issue on `NuxtClientFallback` with webpack only. 
The fallback dom node are not removed client-side. However i have no clue on why does `{ type: ['template'] }` cause this issue

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/client-fallback-auto-id.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export const clientFallbackAutoIdPlugin = createUnplugin((options: LoaderOptions
       if (include.some(pattern => id.match(pattern))) {
         return true
       }
-      return isVue(id, { type: ['template'] })
+      return isVue(id)
```
Comment (danielroe) [inline packages/nuxt/src/components/client-fallback-auto-id.ts:28]: it seems likely we need to update the `isVue` helper util to correctly identify template Vue imports within webpack, so we can preserve the performance improvement of restricting this transform to just vue templates.

Comment (danielroe) [reply packages/nuxt/src/components/client-fallback-auto-id.ts:28]: actually, I think your solution is right here, as we're directly replacing text in the SFC...

**Review by danielroe — APPROVED** [review]

File: packages/nuxt/src/components/client-fallback-auto-id.ts (hunk 1 above)
Comment (huang-julien) [reply packages/nuxt/src/components/client-fallback-auto-id.ts:28]: i just begin to understand how it work, 
image
here's a `console.log(id, isVue(id), isVue(id, { type: ['template'] })` 🙂
