### PR TITLE
fix(schema): make serverDir only relative to root

### LINKED ISSUE #28695: serverDir not being registered
### Environment

- Operating System: Linux
- Node Version:     v20.16.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.7.1
- Builder:          -
- User Config:      compatibilityDate, ssr, devtools, srcDir, serverDir, devServer, vue, build, imports, components, hooks, sourcemap
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Github Repo: https://github.com/nunonux/nuxt-serverdir-issue
StackBlitz: https://stackblitz.com/edit/github-adnwzy?file=nuxt.config.ts

### Describe the bug

When I set the _**serverDir**_ property in nuxt.config.ts with the value _**'/src/server'**_, nuxt don't r**egister the routes** in the api folder. 
So, if I send an request for a route in the api folder, I get an 404 request error.

### Additional context

Normally I structure my nuxt app as:
src/
  app/
  server/
It has been working great until the nuxt version 1.12.4 and 1.13.0, that's were it breaks my current app. 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/28695

### 📚 Description

This PR make server dir relative paths only relative to rootdir as stated in the doc

### CODE REVIEW

File: packages/schema/src/config/common.ts [hunk 1]
```diff
@@ -156,9 +156,7 @@ export default defineUntypedSchema({
    */
   serverDir: {
     $resolve: async (val: string | undefined, get): Promise<string> => {
-      const isV4 = ((await get('future') as Record<string, unknown>).compatibilityVersion === 4)
-
-      return resolve(isV4 ? await get('rootDir') as string : await get('srcDir') as string, val ?? 'server')
+      return resolve(await get('rootDir') as string, val ?? 'server')
```
Comment (danielroe) [inline packages/schema/src/config/common.ts:159]: A little tweak required.

if it's not v4 compat, then by default this should be `<srcDir>/server`. In v4 compat, it should be `<rootDir>/server`. If the user provides it then in either case it should be resolved relative to `<rootDir>`.

**Comment by HigherOrderLogic** [comment]
Just a nitpick but the issue is #28695, not #26965.

**Review by danielroe — APPROVED** [review]
