### PR TITLE
fix(nuxt): migrate to AST-aware tree-shaking + route injection

### LINKED ISSUE #33070: nuxt:tree-shake-composables:transform creates syntax errors
### Environment

❯ - Operating System: `Darwin`
- Node Version:     `v22.16.0`
- Nuxt Version:     `4.0.3`
- CLI Version:      `3.28.0`
- Nitro Version:    `2.12.4`
- Package Manager:  `npm@10.9.2`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-pkrqqz9m?file=app%2Fapp.vue

Install dependencies and run build

```bash
npm install
npm run build
```

See error during server build

### Describe the bug

Build log:

```sh
> npm run build 

> build
> nuxt build

Nuxt 4.0.3 with Nitro 2.12.4                                                                                                                 nuxi 10:08:04 AM
ℹ Building for Nitro preset: node-server                                                                                                    nuxi 10:08:04 AM
ℹ Building client...                                                                                                                             10:08:05 AM
ℹ vite v7.1.3 building for production...                                                                                                         10:08:05 AM
ℹ ✓ 127 modules transformed.                                                                                                                     10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/manifest.json                   1.09 kB │ gzip:  0.29 kB                                         10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/error-500.DjyirMQI.css    1.91 kB │ gzip:  0.73 kB                                         10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/error-404.DlVPZ4GE.css    2.43 kB │ gzip:  0.86 kB                                         10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/entry.nBs2o3t4.css        6.95 kB │ gzip:  1.66 kB                                         10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/WMnQmeoN.js               3.47 kB │ gzip:  1.55 kB                                         10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/CKoPJdJo.js               9.29 kB │ gzip:  3.74 kB                                         10:08:05 AM
ℹ ../node_modules/.cache/nuxt/.nuxt/dist/client/_nuxt/BKiKrINi.js             145.92 kB │ gzip: 54.32 kB                                         10:08:05 AM
ℹ ✓ built in 754ms                                                                                                                               10:08:05 AM
✔ Client built in 763ms                                                                                                                          10:08:05 AM
ℹ Building server...                                                                                                                             10:08:05 AM
ℹ vite v7.1.3 building SSR bundle for production...                                                                                              10:08:05 AM
ℹ ✓ 30 modules transformed.                                                                                                                      10:08:06 AM

 ERROR  ✗ Build failed in 124ms                                                                                                                   10:08:06 AM


 ERROR  Nuxt Build Error: app/app.vue (3:0): Expression expected (Note that you need plugins to import files that are not JavaScript)        nuxi 10:08:06 AM
file: /Users/mak13180/site/esri/nuxt-process-env-error/app/app.vue:3:0

1: <script setup>
2:   console.log({
3:     onUpdated(_) {},
   ^
4:   });
5: </script>


    at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:401:41)
    at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:14433:28)
    at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:16313:10)
    at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:15553:12)
    at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:17308:24)
    at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:21321:13)

  [cause]: Expression expected

      at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:401:41)
      at ParseError.initialise (node_modules/rollup/dist/es/shared/node-entry.js:14433:28)
      at convertNode (node_modules/rollup/dist/es/shared/node-entry.js:16313:10)
      at convertProgram (node_modules/rollup/dist/es/shared/node-entry.js:15553:12)
      at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:17308:24)
      at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:21321:13)
```

### Additional context

If source code includes a method `onUpdated` inside an object/class, the nuxt's optimization plugin inserts syntax error:

```sh
  console.log({
    onUpdated(_) {},
  });
```

becomes:

```sh
  console.log({
    false && /*@__PURE__*/ onUpdated(_) {},
  });
```

That is done by this plugin: https://github.com/nuxt/nuxt/blob/1111111f1ef0403d122da6a0c4ea35ef574e9b19/packages/nuxt/src/core/plugins/tree-shake.ts#L13

This breaks consumption of https://www.npmjs.com/package/@esri/calcite-components as it includes dependency on @arcgis/lumina which includes a method called `onUpdated`

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/33070

### 📚 Description

this PR drops a couple of regexp-based plugins in favour of oxc-parser handling, resolving a couple of bugs along the way

### CODE REVIEW

File: packages/nuxt/src/core/plugins/tree-shake.ts [hunk 1]
```diff
@@ -28,21 +24,74 @@ export const TreeShakeComposablesPlugin = (options: TreeShakeComposablesPluginOp
...
+                allImportedComposableNames.add(localName)
+
+                // Only track the path if it's from an allowed source
+                if (importPath === '#imports' || options.composables[importPath]?.includes(importedName)) {
+                  importedComposables.set(localName, importPath)
+                }
+              }
+            }
+            return
+          }
```
Comment (cernymatej) [inline packages/nuxt/src/core/plugins/tree-shake.ts]: if you use the ScopeTracker, you can then get the declaration of the identifier and check if it's an import
```ts
const scopeTrackerNode = scopeTracker.getDeclaration(functionName)

if (
  scopeTrackerNode?.type === 'Import'
  && scopeTrackerNode.importNode.source.value === /* ... */
)
```

this way, it will support shadowing outer-scope composables

```ts
// edge case example
import { onMounted } from '#imports'

onMounted(() => console.log('treeshake this'))

function foo() { 
  onMounted()
  // we will need a pre-pass to collect all identifiers for each scope, though...
  function onMounted() {
    console.log('do not treeshake this')
  }
}
```

**Review by cernymatej — APPROVED** [review]

**Comment by danielroe** [comment]
@huang-julien available on pkg.pr.new: https://github.com/nuxt/nuxt/pull/33128#issuecomment-3249244412
