### PR TITLE
fix(server): avoid caching `.js` assets in development to fix HMR for safari

### LINKED ISSUE #3828: safari: infinite loop when hot reloading
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2) (or latest 2.0.0 pre code)

### Steps to reproduce

1. Launch dev server via `yarn dev` (`HOST=0.0.0.0 nuxt`)
2. Load http://localhost:3000/
3. Edit code, any code. Watch the nuxt dev server recompile everything.
4. Reload
5. HMR fails, triggering rapid reloading of the entire page, forever, until Safari kills the tab for excessive CPU usage.
6. The only way to test new code is to close the tab and open a new tab to localhost (and re-open dev console).

### What is expected ?

Hot reload to work without forcing me to close the tab and open a new tab every time I change a line of code.

### What is actually happening?

Browser crushing infinite reload.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7666">#c7666</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by danielroe**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
This PR turns off caching for webpack-processed JS files in dev mode.

<details><summary><strong>Fixes reload loop on safari (closes #3828)</strong>.</summary>
<br>
Previously, `runtime.js` was being cached in-memory by Safari and triggering infinite HMR updates in the following situation:
* server started
* change made to file (triggering HMR)
* server restarted
* safari hard reload -> starts infinite loop (because `runtime.js` from first server is loaded from memory)

</details>

**Note**: if you have previously experienced an infinite reload loop, you will need to clear your Safari cache once using `Develop...Empty Caches` and then reload.

## Checklist:
- [x] All new and existing tests are passing.

### CODE REVIEW

**Review by clarkdo — DISMISSED** [review]

File: packages/server/src/server.js [hunk 1]
```diff
@@ -114,6 +114,11 @@ export default class Server {
         if (!this.devMiddleware) {
           return next()
         }
+        // Safari over-caches JS (breaking HMR) and the seemingly only way to turn
+        // this off in dev mode is to set Vary: * header
+        if (req.url.startsWith(this.publicPath) && req.url.endsWith('.js')) {
+          res.setHeader('Vary', '*')
```
Comment (clarkdo) [inline packages/server/src/server.js:120]: Would cache-control: no-store be better?

Comment (danielroe) [reply packages/server/src/server.js:120]: You would think so, but it's a known issue with Safari's cache mechanism (= a bug, imo). See https://stackoverflow.com/a/54337073/9614848

Comment (pi0) [reply packages/server/src/server.js:120]: @danielroe Can you please also confirm it only happens for js? (ie changing an imported asset like image accepts hmr without cache issue)

Comment (danielroe) [reply packages/server/src/server.js:120]: @pi0 I've confirmed there is no issue with HMR image assets.

The issue isn't to do with all .js, just the runtime chunk. I believe the issue could be resolved by simply adding `Vary` header to `/_nuxt/runtime.js`, as that file is what determines the HMR update URLs. But I've made it more general in this PR in case of `runtimeChunk: 'multiple'`, for example.

**Review by pi0 — APPROVED** [review]
