### PR TITLE
fix(nuxt): short circuit middleware when validate returns false

### LINKED ISSUE #29250: Route Page validate not working on SSR
### Environment

Nuxt project info:                                                                                                                                                                                                              11:36:52 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.13.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/wandering-field-rjwg87
open `/posts/nan-id`  with ssr 

expected: Page not exist. The middleware is not called 

### Describe the bug

In SSR mode, validate does not work properly. And after it return false, the middleware still called. In spa mode, nothing will happen if you try to go to an invalid page.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/29250

### 📚 Description

this updates middleware behaviour to short circuit when `validate` returns false

I'd like to confirm this isn't a breaking change but wasn't able to replicate 'falling through' to other routes if validate returned `false`

### CODE REVIEW

**Review by huang-julien — APPROVED** [review]

File: packages/nuxt/src/pages/runtime/validate.ts [hunk 1]
```diff
@@ -1,41 +1,29 @@
...
-      // We stop the navigation immediately before it resolves
-      // if there is no other route matching it.
-      return false
-    }
-  })
+
+  // We pretend to have navigated to the invalid route so
+  // that the user can return to the previous page with
+  // the back button.
+  if (typeof window !== 'undefined') {
```
Comment (Mini-ghost) [inline packages/nuxt/src/pages/runtime/validate.ts:24]: Would there be any difference between using `import.meta.client` here versus `typeof window !== 'undefined'`?

Comment (danielroe) [reply packages/nuxt/src/pages/runtime/validate.ts:24]: not sure where that line originally came from, but `import.meta.client` should be just as safe 👍  (they are both tree-shakeable)
