### PR TITLE
fix(nuxt): add types for globally injected `$config` object

### LINKED ISSUE #20069: `$config` type error
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-2l517b

```
$ npm i
$ npm run typecheck
```

### Describe the bug

The code below gives an error.

```vue
<template>
  <div>
    <h1>index</h1>
    <p>{{ $config.public.flag }}</p><!-- type error -->
  </div>
</template>
```

```vue
<script lang="ts">
export default defineNuxtComponent({
  created() {
    console.log(this.$config.public.flag); // type error
  },
});
</script>
```

I paste the log when type checking at the bottom.

This is a problem that occurs from v3.3.3.
It did not occur with v3.2.3. (https://stackblitz.com/edit/github-2l517b-cwvb5p)

### Additional context

_No response_

### Logs

```shell-script
❯ npm run typecheck
$ nuxt typecheck
Nuxi 3.3.3                                                             16:52:14
pages/index.vue:4:11 - error TS2339: Property '$config' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R) => ...'.

4     <p>{{ $config.public.flag }}</p>
            ~~~~~~~

pages/option.vue:4:22 - error TS2339: Property '$config' does not exist on type 'CreateComponentPublicInstance<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, {}, {}, false, {}, OptionTypesType<{}, {}, {}, {}, {}, {}>, ... 5 more ..., {}>'.

4     console.log(this.$config.public.flag);
                       ~~~~~~~

pages/option.vue:12:11 - error TS2339: Property '$config' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R) => ...'.

12     <p>{{ $config.public.flag }}</p>
             ~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     1  pages/index.vue:4
     2  pages/option.vue:4

 ERROR  Command failed with exit code 2: vue-tsc --noEmit              16:52:17

  at makeError (file://node_modules/nuxi/dist/shared/nuxi.63bda57d.mjs:640:11)
  at handlePromise (file://node_modules/nuxi/dist/shared/nuxi.63bda57d.mjs:1129:26)
  at async Object.invoke (file://node_modules/nuxi/dist/chunks/typecheck.mjs:69:7)
  at async _main (file://node_modules/nuxi/dist/cli.mjs:64:20)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/20069

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds types for the injected `$config` by including them in the generated schema types.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by antfu — APPROVED** [review]
I don't have the context of why it's removed (or missing?) but the PR itself LGTM

**Comment by danielroe** [comment]
The issue is that before v3.3 users didn't notice the missing types as the key signature for `useNuxtApp` was `any` rather than `unknown`.

File: packages/nuxt/src/core/templates.ts [hunk 1]
```diff
@@ -154,7 +154,18 @@ export const schemaTemplate: NuxtTemplate<TemplateContext> = {
...
           indentation: 2
         }),
-      '}'
+      '}',
+      `declare module 'vue' {
+        interface ComponentCustomProperties {
+          $config: RuntimeConfig
+        }
+      }`,
+      // TODO: remove when webstorm has support for augumenting 'vue' directly
```
Comment (scscgit) [inline packages/nuxt/src/core/templates.ts:163]: <del>augumenting</del> augmenting

Comment (danielroe) [reply packages/nuxt/src/core/templates.ts:163]: nice spot! want to make pr or shall I?
