### PR TITLE
fix(schema): update for vue option change in `vite-plugin-vue`

### LINKED ISSUE #28295: propsDestructure no longer working
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, vue
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-g3udp4?file=nuxt.config.ts

### Describe the bug

Since [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue)@5.1.0 the `propsDestructure` option should be set inside a `features` flag (see [changelog](https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue@5.1.0/packages/plugin-vue/CHANGELOG.md#510-2024-07-23)) and therefore doesn't work anymore in Nuxt by setting `vue.propsDestructure: true`. I'll make a PR.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by yassilah**
### 🔗 Linked issue

resolves #28295.
### 📚 Description

Fixes a bug with enabling `propsDestructure` with [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue)@^5.1.0.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

File: packages/schema/src/config/vite.ts [hunk 1]
```diff
@@ -56,13 +56,15 @@ export default defineUntypedSchema({
...
-        propsDestructure: {
-          $resolve: async (val, get) => val ?? Boolean((await get('vue') as Record<string, any>).propsDestructure),
-        },
         hoistStatic: {
           $resolve: async (val, get) => val ?? (await get('vue') as Record<string, any>).compilerOptions?.hoistStatic,
         },
       },
+      features: {
+        propsDestructure: {
+          $resolve: async (val, get) => val ?? Boolean((await get('vue') as Record<string, any>).propsDestructure),
```
Comment (danielroe) [inline packages/schema/src/config/vite.ts:65]: we should probably also check if `vue.script.propsDestructure` is set, for backwards-compatibility

**Review by danielroe — APPROVED** [review]
