### PR TITLE
fix(nuxt): allow camelCase for lazy hydration attributes

### LINKED ISSUE #32295: `Extraneous non-props attributes (hydrateOn*) were passed to component but could not be automatically inherited because component renders fragment or text or teleport root nodes.`
### Environment

- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     3.17.5
- CLI Version:      3.25.1
- Nitro Version:    2.11.12
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-m2k3wh7t?file=app.vue

### Describe the bug

When passing any [strategy](https://nuxt.com/docs/guide/directory-structure/components#hydration-strategies) of [lazy hydration](https://vuejs.org/guide/components/async.html#lazy-hydration) on lazy component:
```html
<LazyAsync hydrateOnVisible />
```
that has more than one root node:
```html
<template>
  <p>1</p>
  <p>2</p>
</template>
```
Console of devtools will log:
> Extraneous non-props attributes (hydrateOnVisible) were passed to component but could not be automatically inherited because component renders fragment or text or teleport root nodes.`

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #32295 

### 📚 Description

This PR allows users to use PascalCase attribute for lazy hydration

### CODE REVIEW

File: packages/nuxt/src/components/plugins/lazy-hydration-transform.ts [hunk 1]
```diff
@@ -23,7 +23,9 @@ const hydrationStrategyMap = {
   hydrateWhen: 'If',
   hydrateNever: 'Never',
 }
-const LAZY_HYDRATION_PROPS_RE = /\bhydrate-?on-?idle|hydrate-?on-?visible|hydrate-?on-?interaction|hydrate-?on-?media-?query|hydrate-?after|hydrate-?when|hydrate-?never\b/
+
+const LAZY_HYDRATION_PROPS_RE = /\b(?:hydrate-on-idle|HydrateOnIdle|hydrate-on-visible|HydrateOnVisible|hydrate-on-interaction|HydrateOnInteraction|hydrate-on-media-query|HydrateOnMediaQuery|hydrate-after|HydrateAfter|hydrate-when|HydrateWhen|hydrate-never|HydrateNever)\b/
```
Comment (danielroe) [inline packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: we don't want this to be PascalCase, but camelCase, right?

Comment (huang-julien) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: ooops

**Review by danielroe — APPROVED** [review]
