### PR TITLE
fix(nuxt): add warning for lazy-hydration missing prefix

### LINKED ISSUE #32736: Warn when using hydration directive without `<Lazy` prefix.
### Describe the feature

Right now, there is no warning when people use hydration strategies but forgetting to add the `<Lazy` prefix. This should give a warning during dev. 

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [x] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [x] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by OskarLebuda**
### 🔗 Linked issue

resolves #32736

### 📚 Description
Add a missing warning for components that use the `lazy-hydration` props but aren't prefixed with `<Lazy`. This helps catch cases where developers intend to lazy-load a component but forget the naming convention, potentially leading to unexpected behavior.

Example:
```vue
<template>
  <SomeComp hydrate-never/>
</template>
```

Warning:
obraz

### CODE REVIEW

File: packages/nuxt/src/components/plugins/lazy-hydration-transform.ts [hunk 1]
```diff
@@ -75,6 +75,10 @@ export const LazyHydrationTransformPlugin = (options: LoaderOptions) => createUn
               return
             }
             if (!/^(?:Lazy|lazy-)/.test(node.name)) {
+              if (node.name !== 'template') {
+                logger.warn(`Component <${node.name}> has lazy-hydration props but is not declared as a lazy component.\n` +
```
Comment (TheAlexLichter) [inline packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: Do we have any chance to point at the file (and ideally LOC) here? That'd be even better DX

Comment (OskarLebuda) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: I'll try to check that!

Comment (OskarLebuda) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: @TheAlexLichter switched it to run only in `dev` and `test` mode :) I also added `test` explicitly so it doesn’t get skipped during test runs.

Comment (OskarLebuda) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: @TheAlexLichter by “point the file” - do you mean the file where the issue actually occurs? Like, where the component is being **used**, not where it’s defined?

Comment (TheAlexLichter) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: Yes, ideally where it is used so I can fix it with a click in my console 👍🏻

Comment (OskarLebuda) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: Added 👍🏻

Comment (OskarLebuda) [reply packages/nuxt/src/components/plugins/lazy-hydration-transform.ts]: @TheAlexLichter is that what you want?

**Review by danielroe — APPROVED** [review]
