### PR TITLE
fix(nuxt): show error page after fatal `abortNavigation`

### LINKED ISSUE #15053: error page not shown after abortNavigation
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-i5nygk?file=error.vue

### Describe the bug

When throwing an error or aborting navigation from middleware nuxt does not render the error.vue page but instead shows the default nuxt error page. If this is not the intended usage of abortNavigation please provide an alternative.

using showError on a page using middlewares would trigger the same issue.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by aleksdotbar**
### 🔗 Linked issue
resolves #15053

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Show error page if `fatal: true` option was passed to `abortNavigation`

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by xanderbarkhatov** [comment]
Not sure if it's okay doing it here, but felt cleaner than in **_/plugins/router.ts_** as we only want to do it for **fatal** errors.

File: packages/nuxt/src/app/composables/router.ts [hunk 1]
```diff
@@ -155,10 +155,15 @@ export const abortNavigation = (err?: string | Partial<NuxtError>) => {
   if (process.dev && !isProcessingMiddleware()) {
     throw new Error('abortNavigation() is only usable inside a route middleware handler.')
   }
-  if (err) {
-    throw createError(err)
+
+  if (!err) { return false }
+
+  if (typeof err === 'object' && err.fatal) {
```
Comment (danielroe) [inline packages/nuxt/src/app/composables/router.ts:161]: Maybe:

```suggestion
  if (isNuxtError(err) && err.fatal) {
```

**Review by danielroe — APPROVED** [review]
