### PR TITLE
fix(vue-app): warn if promises and functions are in fetch state

### LINKED ISSUE #8338: Functions declared in data are cleared when fetch is present
### Versions

- nuxt: 2.12.2

### Reproduction

[https://codesandbox.io/s/distracted-sky-tdi6b](https://codesandbox.io/s/distracted-sky-tdi6b)

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

Declare a function as variable inside `data` in a page

### What is Expected?
Access to that variable and use it

### What is actually happening?
The variable is empty if I use fetch hook of nuxt. The problem occurs only in ssr mode, if go to the page with the navigator all is working as expected.

### PR DESCRIPTION
**Pull request by danielroe**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
Resolves #8338

## Checklist:
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-app/template/utils.js [hunk 1]
```diff
@@ -25,6 +25,16 @@ export function interopDefault (promise) {
 export function hasFetch(vm) {
   return vm.$options && typeof vm.$options.fetch === 'function' && !vm.$options.fetch.length
 }
+export function purifyData(data) {
```
Comment (pi0) [inline packages/vue-app/template/utils.js:28]: Since this adds a runtime overhead, maybe we can warn users in development mode to not use non POJO in state/data?

Comment (danielroe) [reply packages/vue-app/template/utils.js:28]: I think a lot of people don't understand the POJO warning - and indeed the side effects (that the entire component state is stringified, for example!)

Are you thinking of warning in dev mode and not checking in prod?

Another option: use a Proxy for `this` for fetch to detect changed properties so not everything will be stringified?

Comment (pi0) [reply packages/vue-app/template/utils.js:28]: > I think a lot of people don't understand the POJO warning - and indeed the side effects (that the entire component data is stringified, for example!)

Indeed fully agree. We need better DX to guide users about this.

> Are you thinking of warning in dev mode and not checking in prod?

Yeah. Like a `process.env` guard similar to other vue packages (vuex for example only checks `stat` to be a function in dev env)  this can avoid adding overhead to production

> Another option: use a Proxy for this for fetch to detect changed properties so not everything will be stringified?

Nuxt 3 PR welcome :D

**Review by pi0 — APPROVED** [review]
