### PR TITLE
fix: return 404 if extendRoutes without Component

### LINKED ISSUE #3351: extend Router without Component
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://codesandbox.io/s/003z85lpxn](https://codesandbox.io/s/003z85lpxn)

### Steps to reproduce

```javascript
module.exports = {
  router: {
    extendRoutes (routes, resolve) {
      routes.push({
        name: 'logout',
        path: '/logout',
        beforeEnter: (to, from, next) => {
           // anything
        },
      })
    }
  }
}
```

### What is expected ?

Result: Cannot read property 'options' of undefined

image

### What is actually happening?

Error

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7097">#c7097</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
resolve #3351

### CODE REVIEW

File: lib/app/utils.js [hunk 1]
```diff
@@ -69,9 +69,14 @@ export function getMatchedComponentsInstances(route, matches = false) {
 
 export function flatMapComponents(route, fn) {
   return Array.prototype.concat.apply([], route.matched.map(function (m, index) {
-    return Object.keys(m.components).map(function (key) {
-      return fn(m.components[key], m.instances[key], m, key, index)
-    })
+    return Object.keys(m.components).reduce(function (promises, key) {
```
Comment (galvez) [inline lib/app/utils.js]: @clarkdo pardon my ignorance, but why do you use a full blown function in `reduce()` instead of `() => {}`? Is it because of previous compatibility with earlier Node versions?

Comment (Atinux) [reply lib/app/utils.js]: I guess since it's in `lib/app/utils.js` (and shipped to the browser), it's to avoid transpilation?

Comment (galvez) [reply lib/app/utils.js]: @Atinux ha! Thought so! Thanks!
