### PR TITLE
fix(nuxt): add script block if there's none before island transformation

### LINKED ISSUE #25147: Using `nuxt-client` throws `Fail to resolve component: NuxtTeleportSsrClient`
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      experimental
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-issues-25147?file=app.vue,components%2FTheFooter.server.vue,pages%2Findex.vue,nuxt.config.ts

### Describe the bug

Using `<NuxtLink nuxt-client to="/">Index</NuxtLink>` in a server component will throw `[Vue warn]: Failed to resolve component: NuxtTeleportSsrClient`.

### Additional context

cc @huang-julien

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

fix #25147

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Hi :wave: 
This PR fix #25147 because in the example, there's no `<script>` block so the SFC will be missing imports when transformed by `islandTransform` plugin

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/islandsTransform.ts [hunk 1]
```diff
@@ -57,9 +58,14 @@ export const islandsTransform = createUnplugin((options: ServerOnlyComponentTran
       const startingIndex = template.index || 0
       const s = new MagicString(code)
 
-      s.replace(SCRIPT_RE, (full) => {
-        return full + '\nimport { vforToArray as __vforToArray } from \'#app/components/utils\'' + '\nimport NuxtTeleportSsrClient from \'#app/components/nuxt-teleport-ssr-client\''
-      })
+      if(!code.match(SCRIPT_RE)) {
```
Comment (danielroe) [inline packages/nuxt/src/components/islandsTransform.ts:61]:
```suggestion
      if (!code.match(SCRIPT_RE)) {
```

**Review by danielroe — APPROVED** [review]
