### PR TITLE
fix(nuxt): exclude resolved vite virtual modules prefix

### LINKED ISSUE #22833: exclude also default resolved Vite virtual modules
### Environment

```shell
Nuxt project info:                                                                                                                                                        13:07:25

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

Open the following SB repo using `virtual:pwa-info`: 
https://stackblitz.com/edit/nuxt-starter-dnvrut?file=app.vue,package.json,nuxt.config.ts

Once Nuxt starts, there is a warning about resolving `virtual:pwa-info` (should be `\0virtual:pwa-info`):
imagen

You can also reproduce it in the nuxt repo using the playground , just add this to the playground `nuxt.config.ts` file:
```ts
const virtual = 'virtual:xxx'
const resolvedVirtual = `\0${virtual}`

export default defineNuxtConfig({
  vite: {
    plugins: [{
      name: 'xxx',
      enforce: 'post',
      resolveId (id) {
        if (id === virtual) {
          console.log('xxx:resolveId', id, resolvedVirtual)
          return resolvedVirtual
        }
      },
      load (id) {
        if (id === resolvedVirtual) {
          console.log('xxx:load', id, resolvedVirtual)
          return 'export const xxx = "xxx";'
        }
      }
    }]
  }
})
```

Add this component on playground folder:
```ts
import { defineComponent } from 'vue'
import { xxx } from 'virtual:xxx'

export default defineComponent({
  setup () {
    if (xxx) {
      console.log(xxx)
    }

    return () => null
  }
})
```

And add the component to the `app.vue`:
```vue
<script setup lang="ts">
import VirtualComponent from './VirtualComponent'
</script>

<template>
  <VirtualComponent />
  <!-- Edit this file to play around with Nuxt but never commit changes! -->
  <div>
    Nuxt 3 Playground
  </div>
</template>

<style scoped>

</style>
```

You will see the warning once Nuxt starts:
```shell
[nuxt] Could not resolve id virtual:xxx D:\work\projects\userquin\GitHub\userquin\nuxt-org\nuxt\playground\index.html
```

### Describe the bug

Resolved Vite virtual modules should be also excluded, `\0virtual:` should also be excluded: https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention.

There are a few modules only checking for `virtual:` prefix, we should also review the usage:

imagen

I'm preparing a PR.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by userquin**
### 🔗 Linked issue

closes #22833

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

check linked issue

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/transform.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export function createTransformPlugin (nuxt: Nuxt, getComponents: getComponentsT
     name: 'nuxt:components:imports',
     transformInclude (id) {
       id = normalize(id)
-      return id.startsWith('virtual:') || id.startsWith(nuxt.options.buildDir) || !isIgnored(id)
+      return id.startsWith('virtual:') || id.startsWith('\0virtual:') || id.startsWith(nuxt.options.buildDir) || !isIgnored(id)
```
Comment (userquin) [inline packages/nuxt/src/components/transform.ts:50]: I'm checking if we can revert this

Comment (userquin) [reply packages/nuxt/src/components/transform.ts:50]: it is fine

**Review by danielroe — APPROVED** [review]
