### PR TITLE
fix(webpack): fallback for empty chunk name

### LINKED ISSUE #7665: since nuxt@2.13.3 some modern files are missing?
Since nuxt 2.13.3 it seems our app is totally broken in modern mode.
e.g. https://cdn-test.hokify.com/pwa/company/_assets/commons/.2714f92.modern.js <-- see the commons/ followed by a dot immediately.

Browser console log:
image

Nuxt 2.13.2 is NOT affected by this bug as far as I can tell, as the only change from yesterday to today is the nuxt version.
Maybe it's related to #7639 ?

In another app I use a custom "filename" option for the assets, It seems this one is not affecetd by this bug, but still verifying it.
```js
filenames: {
			app: ({ isModern, isDev }) =>
				`${!isModern ? 'legacy-' : ''}${!isDev ? '[contenthash]' : '[name]'}-app.js`,
			chunk: ({ isModern, isDev }) =>
				`${!isModern ? 'legacy-' : ''}${!isDev ? '[contenthash]-' : ''}[name].js`
		}
```

### Versions

- nuxt: nuxt@2.13.3
- node: v12.18.0

### Reproduction

Couldn't find time yet, will deliver a reproducable example later if needed.

### PR DESCRIPTION
**Pull request by simllll**
fixes #7665

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
if all chunks have no name, it results to an empty compactName. Due to #7639 this results into file paths like /common/.xxx.js. As files with a dot at the beginnign are not served, this is a problem ;-)  

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/webpack/src/config/client.js [hunk 1]
```diff
@@ -86,6 +82,12 @@ export default class WebpackClientConfig extends WebpackBaseConfig {
           .map(name => name.replace(/[/\\]/g, '.').replace(/_/g, '').replace('pages.', ''))
           .join('~')
 
+        // Fixes https://github.com/nuxt/nuxt.js/issues/7665
+        // TODO: We need a reproduction for this case (test/fixtures/shared-chunk)
```
Comment (pi0) [inline packages/webpack/src/config/client.js:86]: @simllll @aldarund I've added a TODO item as couldn't reproduce the issue. Would be awesome if we can find a reproduction for fixtures. And sorry for issues that happened due to this name change...

**Review by pi0 — DISMISSED** [review]

File: packages/webpack/src/config/client.js [hunk 2]
```diff
@@ -74,10 +74,6 @@ export default class WebpackClientConfig extends WebpackBaseConfig {
 
     if (!this.dev && cacheGroups.default && cacheGroups.default.name === undefined) {
       cacheGroups.default.name = (_module, chunks) => {
-        // Use default name for single chunks
-        if (chunks.length === 1) {
-          return chunks[0].name || ''
-        }
```
Comment (simllll) [inline packages/webpack/src/config/client.js:80]: This might change behavior, because it will now be returned as commons/name instead of just the name without the folder prefix for chunks with size 1. Is this intended?

Comment (pi0) [reply packages/webpack/src/config/client.js:80]: 476af4304a6a6624d71b14d27183e5a7a9f59ef2

**Comment by simllll** [comment]
Lgtm

**Comment by pi0** [comment]
Thanks @simllll. Would you please confirm it working using `nuxt-edge` before doing release? (should be published in few minutes)

**Comment by simllll** [comment]
@pi0 just tested it, I can confirm the issue is fixed in `nuxt-edge`. looks good, thanks!

File: packages/webpack/src/config/client.js (hunk 1 above)
Comment (husayt) [reply packages/webpack/src/config/client.js:89]: Nuxt 2.13.13 was broken trying to load chunks like `.xxx.js`. This has fixed it. Thanks @simllll and @pi0
