### PR TITLE
fix: hmr in modern mode

### LINKED ISSUE #4620: Hot Module Replacement not working in modern mode (Error 404)
### Version

[v2.3.0](https://github.com/nuxt.js/releases/tag/v2.3.0)

### Reproduction link

[https://codesandbox.io/s/ly824lz46l](https://codesandbox.io/s/ly824lz46l)

### Steps to reproduce

1. Add  `modern: "client"` to `nuxt.config.js`.
2. Start nuxt in dev mode.
3. Edit a file (e.g. `pages/index.vue` - the browser won't update automatically. Additionally, you will be able to see at least one request to `https://ly824lz46l.sse.codesandbox.io/__webpack_hmr/modern` failing with status code `404`
4. Remove   `modern: "client"` from `nuxt.config.js`.
5. Hot module replacement works again.

### What is expected ?

HMR working with `modern: "client"`

### What is actually happening?

Request to `.../__webpack_hmr/modern` failing with code `404`

### Additional comments?

I used the default nuxt template from code sandbox and added `modern: "client"` to `nuxt.config.js`.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8350">#c8350</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by clarkdo**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Fix #4620

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/vue-renderer/src/renderer.js [hunk 1]
```diff
@@ -150,6 +150,7 @@ export default class VueRenderer {
         if (isMFS) {
           // Cleanup MFS as soon as possible to save memory
           _fs.unlinkSync(fullPath)
+          delete this._assetsMapping
```
Comment (pi0) [inline packages/vue-renderer/src/renderer.js]: Do we need asset mapping inside renderer for HMR?

File: packages/server/src/middleware/modern.js [hunk 2]
```diff
@@ -34,19 +34,28 @@ const detectModernBuild = ({ options, resources }) => {
   }
 }
 
-const detectModernBrowser = (req, options) => {
+const detectModernBrowser = (req) => {
+  const { socket = {}, headers } = req
```
Comment (pi0) [inline packages/server/src/middleware/modern.js]: Destructuring can be in function params :)

File: packages/vue-renderer/src/renderer.js (hunk 1 above)
Comment (clarkdo) [reply packages/vue-renderer/src/renderer.js]: Yes, because client modern mode doesnt have modern renderer

File: packages/server/src/middleware/modern.js (hunk 2 above)
Comment (clarkdo) [reply packages/server/src/middleware/modern.js]: OK, I’ll change it shortly

File: packages/vue-renderer/src/renderer.js (hunk 1 above)
Comment (pi0) [reply packages/vue-renderer/src/renderer.js]: @clarkdo Would you please point to where we require it? We may find a way to keep deleting assetsMapping here.

Comment (clarkdo) [reply packages/vue-renderer/src/renderer.js]: getPreloadFiles, sorry I’m on phone

Comment (clarkdo) [reply packages/vue-renderer/src/renderer.js]: Any probelm here?

Comment (clarkdo) [reply packages/vue-renderer/src/renderer.js]: It needs to be deleted since every rebuilding will lead to hash changed, so the mapping needs to be generated again 🤥

Comment (clarkdo) [reply packages/vue-renderer/src/renderer.js]: It needs to be deleted since every rebuilding will lead to hash changed, so the mapping needs to be generated again 🤥

**Review by pi0 — DISMISSED** [review]

**Review by atinux — APPROVED** [review]
