### PR TITLE
fix(nuxt): correct RouteNamedMap generation for duplicate pages

### LINKED ISSUE #29350: Incorrect RouteNamedMap type generation caused by duplicate page files when using experimental:typedPages
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

* https://stackblitz.com/edit/github-nekbjl?file=.nuxt%2Ftypes%2Ftyped-router.d.ts&view=editor
See `.nuxt/types/typed-router.d.ts` after the build is complete.

### Describe the bug

When creating duplicate route pages, the generated RouteNamedMap type has an incorrect key. Specifically, when I created `pages/foo.vue` and `pages/foo/index.vue`, the RouteNamedMap type located at `.nuxt/types/typed-router.d.ts` has keys named `foo` and `/foo`. I believe these two keys should be aggregated into `foo`.
Image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by harunari0928**
### 🔗 Linked issue

resolves #29350

### 📚 Description

Fix the RouteNamedMap generation. When I created `pages/foo.vue` and `pages/foo/index.vue`, the RouteNamedMap type located at `.nuxt/types/typed-router.d.ts` has keys named `foo` and `/foo`.This fix aggregates these two keys into `foo`

### CODE REVIEW

File: packages/nuxt/src/pages/module.ts [hunk 1]
```diff
@@ -170,7 +170,21 @@ export default defineNuxtModule({
...
+              if (page.meta) {
+                parent.addToMeta(page.meta)
+              }
+              if (page.alias) {
+                parent.addAlias(page.alias)
+              }
+              parent.name = page.name
+              return
+            }
+            addedPagePaths.add(`${parent.path}${page.path}`)
```
Comment (danielroe) [inline packages/nuxt/src/pages/module.ts:186]: should we use `joinURL` or `${parent.path}/${page.path}`?

**Comment by danielroe** [comment]
would you add a test to the basic-types fixture? 🙏

File: packages/nuxt/src/pages/module.ts (hunk 1 above)
Comment (harunari0928) [reply packages/nuxt/src/pages/module.ts]: @danielroe 
I think it's preferable to use joinURL to avoid potential issues with path formatting. I've made the fix accordingly.

**Comment by harunari0928** [comment]
> would you add a test to the basic-types fixture? 🙏

I added some pages to the basic-types fixture package to simulate the issue. Does this look okay to you?

**Review by danielroe — APPROVED** [review]
