### PR TITLE
fix(nuxt): respect `baseURL` when ignoring prerendered manifest

### LINKED ISSUE #30367: `nuxt generate` fails when using `app.baseURL` different than `/` since v3.15
### Environment

ALL envs.

- Operating System: `Darwin`
- Node Version:     `v23.4.0`
- Nuxt Version:     `3.15.0`
- CLI Version:      `3.17.2`
- Nitro Version:    `2.10.4`
- Package Manager:  `yarn@1.22.22`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- `npx nuxi@latest init test-project`
- `cd test-project`
- `NUXT_APP_BASE_URL="/something" yarn run generate`

Reproduction url: https://stackblitz.com/edit/github-htzmuwfb?file=nuxt.config.ts

### Describe the bug

Since `nuxt v3.15`, `nuxt generate` fails when the configuration defines an `app.baseURL` different than the default `/` using the config file or `NUXT_APP_BASE_URL` as an environment variable.

This happens even in a fresh project.

It can be bypassed by disabling the `appManifest` (by setting `experimental.appManifest` to `false`)

### Additional context

Image

### Logs

```shell-script
> nuxt generate

Nuxt 3.15.0 with Nitro 2.10.4                                                                                           3:46:00 PM
ℹ Using Nitro server preset: static                                                                                    3:46:01 PM
ℹ Compiled plugins.client.mjs in 511.86ms                                                                              3:46:06 PM
ℹ Compiled types/plugins.d.ts in 523.6ms                                                                               3:46:06 PM
ℹ Building client...                                                                                                   3:46:08 PM
ℹ vite v6.0.5 building for production...                                                                               3:46:08 PM
ℹ ✓ 135 modules transformed.                                                                                           3:46:11 PM
ℹ .nuxt/dist/client/manifest.json                   1.06 kB │ gzip:  0.29 kB                                           3:46:11 PM
ℹ .nuxt/dist/client/_nuxt/error-500.dGVH929u.css    1.88 kB │ gzip:  0.72 kB                                           3:46:11 PM
ℹ .nuxt/dist/client/_nuxt/error-404.C3V-3Mc4.css    3.56 kB │ gzip:  1.11 kB                                           3:46:11 PM
ℹ .nuxt/dist/client/_nuxt/entry.ofCu9KLV.css       12.41 kB │ gzip:  2.57 kB                                           3:46:11 PM
ℹ .nuxt/dist/client/_nuxt/DSVsJNNr.js               3.39 kB │ gzip:  1.53 kB                                           3:46:11 PM
ℹ .nuxt/dist/client/_nuxt/Cyk1OFr2.js               9.41 kB │ gzip:  3.77 kB                                           3:46:11 PM
ℹ .nuxt/dist/client/_nuxt/B8f4TB0u.js             219.51 kB │ gzip: 62.59 kB                                           3:46:11 PM
ℹ ✓ built in 2.94s                                                                                                     3:46:11 PM
✔ Client built in 2952ms                                                                                               3:46:11 PM
ℹ Building server...                                                                                                   3:46:11 PM
ℹ vite v6.0.5 building SSR bundle for production...                                                                    3:46:11 PM
ℹ ✓ 49 modules transformed.                                                                                            3:46:12 PM
ℹ .nuxt/dist/server/_nuxt/entry-styles.C7mjwxNe.mjs             0.08 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-404-styles.PedwCpCK.mjs         0.08 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-500-styles.K0bbvuT_.mjs         0.08 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/welcome-styles.CCGfeDbY.mjs           0.15 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-404-styles.B5yeQDbX.mjs         0.15 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-500-styles.HhVXVi60.mjs         0.15 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/styles.mjs                                  1.11 kB                                                3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-Bj5KKHbJ.js    2.10 kB │ map:   0.12 kB                               3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-COU7bu3q.js    3.77 kB │ map:   0.12 kB                               3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-500-D4R_5GhE.js                 4.54 kB │ map:   5.36 kB                               3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-Di7eYM5N.js       12.67 kB │ map:   0.11 kB                               3:46:13 PM
ℹ .nuxt/dist/server/_nuxt/error-404-DME_KJAK.js                15.64 kB │ map:  29.05 kB                               3:46:13 PM
ℹ .nuxt/dist/server/server.mjs                                124.55 kB │ map: 182.05 kB                               3:46:13 PM
ℹ ✓ built in 1.40s                                                                                                     3:46:13 PM
✔ Server built in 1451ms                                                                                               3:46:13 PM
ℹ Initializing prerenderer                                                                                       nitro 3:46:13 PM
ℹ Prerendering 3 initial routes with crawler                                                                     nitro 3:46:16 PM
  ├─ /200.html (323ms)                                                                                            nitro 3:46:17 PM
  ├─ /404.html (322ms)                                                                                            nitro 3:46:17 PM
  ├─ / (343ms)                                                                                                    nitro 3:46:17 PM
  ├─ /some-sub-path/_nuxt/builds/meta/44c8cfbf-f224-48e5-8e0b-58235722c140.json (3ms)                             nitro 3:46:17 PM
  │ ├── [404] Cannot find static asset /_nuxt/builds/meta/44c8cfbf-f224-48e5-8e0b-58235722c140.json
  │ └── Linked from /
  ├─ /some-sub-path/_payload.json?44c8cfbf-f224-48e5-8e0b-58235722c140 (3ms) (skipped)                            nitro 3:46:17 PM
  ├─ /_payload.json (4ms)                                                                                         nitro 3:46:17 PM
                                                                                                                  nitro 3:46:17 PM
Errors prerendering:
  ├─ /some-sub-path/_nuxt/builds/meta/44c8cfbf-f224-48e5-8e0b-58235722c140.json (3ms)                             nitro 3:46:17 PM
  │ ├── [404] Cannot find static asset /_nuxt/builds/meta/44c8cfbf-f224-48e5-8e0b-58235722c140.json
  │ └── Linked from /
                                                                                                                  nitro 3:46:17 PM

 ERROR  Exiting due to prerender errors.                                                                                3:46:17 PM

    at prerender (node_modules/nitropack/dist/core/index.mjs:2090:11) 



 ERROR  Exiting due to prerender errors.                                                                                3:46:17 PM
```

### PR DESCRIPTION
**Pull request by TheAlexLichter**
### 🔗 Linked issue

Resolves https://github.com/nuxt/nuxt/issues/30367

### 📚 Description

Adds the baseURL to the manifest preload path.

### CODE REVIEW

File: packages/nuxt/src/core/nitro.ts [hunk 1]
```diff
@@ -249,7 +249,8 @@ export async function initNitro (nuxt: Nuxt & { _nitro?: Nitro }) {
     const buildId = nuxt.options.runtimeConfig.app.buildId ||= nuxt.options.buildId
     const buildTimestamp = Date.now()
 
-    const manifestPrefix = joinURL(nuxt.options.app.buildAssetsDir, 'builds')
+    const baseURL = nuxt.options.runtimeConfig.app.baseURL ||= nuxt.options.app.baseURL
```
Comment (TheAlexLichter) [inline packages/nuxt/src/core/nitro.ts:252]: Not sure if we do need the reassign like we do in L249 for buildId 🤔

`const buildId = nuxt.options.runtimeConfig.app.buildId ||= nuxt.options.buildId`

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts:252]: we do not need to reassign

Comment (TheAlexLichter) [reply packages/nuxt/src/core/nitro.ts:252]: Okay, will remove it then

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts]: i think we don't need to check runtimeConfig here at all

**Comment by TheAlexLichter** [comment]
As a note: This fixes local generate but I wonder if this will conflict with static deployments to e.g. cloudflare or vercel, as we extend the URL with the baseURL manually there.
(Stumbled upon while checking https://github.com/nitrojs/nitro/issues/1484)

**Comment by danielroe** [comment]
having taken a look, I suspect the issue here is not the path of the build assets file at this point but what we're rendering here:

https://github.com/nuxt/nuxt/blob/54f5b9e8a4fef8da9b0e0139e89aea0d62b1d1c3/packages/nuxt/src/core/runtime/nitro/renderer.ts#L402-L408
