### PR TITLE
fix(cli): grammatical errors

### LINKED ISSUE #8217: Grammar error in Nuxt Generate Warning
### Versions
- nuxt: 2.14.7

### Steps to reproduce

Have no nuxt.config.js file, run `yarn generate`.  In this warning `your` should be `you`

image

### What is Expected?
`you have to set`

### What is actually happening?
`your have to set`

### PR DESCRIPTION
**Pull request by steveperkins**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolves #8217. Fixes two grammatical errors in an error message.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

### CODE REVIEW

File: packages/cli/src/commands/generate.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ export default {
 
     // Forcing static target anyway
     config.target = TARGETS.static
-    consola.warn(`For using \`nuxt generate\`, your have to set \`target: 'static'\` in your \`nuxt.config\`\n       👉 Learn more about it on https://go.nuxtjs.dev/static-target`)
+    consola.warn(`When using \`nuxt generate\`, you have to set \`target: 'static'\` in your \`nuxt.config\`\n       👉 Learn more about it on https://go.nuxtjs.dev/static-target`)
```
Comment (danielroe) [inline packages/cli/src/commands/generate.js:79]:
```suggestion
    consola.warn(`When using \`nuxt generate\`, you should set \`target: 'static'\` in your \`nuxt.config\`\n       👉 Learn more about it on https://go.nuxtjs.dev/static-target`)
```

**suggestion**: this is a warning before forcing - so you don't *have* to set target

**Review by pi0 — APPROVED** [review]
Thanks
