### PR TITLE
fix(vite): expand `fs.allow` dirs to include app files

### LINKED ISSUE #14295: Vite unable to load modules when components are outside project directory
### Environment

Stackblitz, using components config:
```
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `components`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

Local, using component:dirs hook:
```
- Operating System: `Darwin`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `hooks`, `modules`, `app`, `css`
- Runtime Modules:  `@storyblok/nuxt@4.0.1`
- Build Modules:    `-`
```

### Reproduction

Repro: https://stackblitz.com/edit/github-tncnqa

What I did (things to note):
1. moved the nuxt project into a `nuxt` directory
2. configured stackblitz to be able to work with this structure by adding a `.stackblitzrc` file
3. imported the markdown dependency as a test case
4. configured nuxt/vue to globally load components from the parent (`/components`) directory (using `components` config, but same problem happens if I used `components:dirs` hook)
5. added an `Inner.vue` and `Outer.vue` components - they basically convert and display some markdown to html

### Describe the bug

When adding components from outside the project directory, loading modules in those components messes up. 
For example, if the `makrdown` module was supposed to be imported, this error pops up during build:
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/github-tncnqa/nuxt/markdown' imported from /home/projects/github-tncnqa/nuxt/.nuxt/dist/server/server.mjs

### Additional context

I'm not sure if this relates to nuxt or is purely a vite problem, unfortunately I don't know enough to find the problem and I have no idea how to make a reproduction with vite only.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/14295

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds the directories from app dependencies (like component folders) directly into the vite allow list to avoid potential issues. It's of course totally possible for a user to do this themselves but it can add friction. wdyt @antfu?

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/vite/src/vite.ts [hunk 1]
```diff
@@ -27,6 +28,23 @@ export async function bundle (nuxt: Nuxt) {
...
     (nuxt.options.vite.devBundler === 'vite-node' && nuxt.options.dev)
   const entry = await resolvePath(resolve(nuxt.options.appDir, useAsyncEntry ? 'entry.async' : 'entry'))
+
+  let allowDirs = [
+    nuxt.options.appDir,
+    nuxt.options.workspaceDir,
+    ...nuxt.options._layers.map(l => l.config.rootDir),
+    ...nuxt.apps.default?.components.map(c => dirname(c.filePath)),
+    ...nuxt.apps.default?.plugins.map(p => dirname(p.src)),
+    ...nuxt.apps.default?.middleware.map(m => dirname(m.path)),
```
Comment (pi0) [inline packages/vite/src/vite.ts:38]: To avoid future refactor, shall we iterate over all possible `apps` keys?

File: packages/vite/src/vite.ts [hunk 2]
```diff
@@ -27,6 +28,23 @@ export async function bundle (nuxt: Nuxt) {
...
+    ...Object.values(nuxt.apps.default?.layouts || {}).map(l => dirname(l.file)),
+    dirname(nuxt.apps.default.rootComponent!),
+    dirname(nuxt.apps.default.errorComponent!)
+  ].filter(d => d && existsSync(d))
```
Comment (pi0) [inline packages/vite/src/vite.ts:42]: I guess this list makes some duplicates (unnecessary nested paths `/foo` covers `/foo/bar`) but i guess should be fine for performance /cc @antfu ? (or a sort might help at least)

Comment (danielroe) [reply packages/vite/src/vite.ts:42]: This PR does handle nested paths - see:

https://github.com/nuxt/nuxt/blob/49bfa2d37984473727ad573b50ffe079558c6457/packages/vite/src/vite.ts#L44-L46

Deduplicating is certainly worth it though.

File: packages/vite/src/vite.ts (hunk 1 above)
Comment (pi0) [reply packages/vite/src/vite.ts:38]: We might try multi-app via an experimental module as well. If core (or any modules might start depending on `nuxt.apps` can be ready for it, it could be a bonus  :)

Comment (danielroe) [reply packages/vite/src/vite.ts:38]: sure, makes sense - but I think it's worth noting (for the benefit of any modules) that we definitely do not support multi-app yet. we still need a team discussion first.

Comment (pi0) [reply packages/vite/src/vite.ts]: For sure :) It is only placeholder for the future.

**Review by pi0 — APPROVED** [review]
