### PR TITLE
fix(nuxt): don't use local fetch with an external `baseURL`

### LINKED ISSUE #23880: About the isLocalFetch variable of useFetch
### Describe the feature

https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/fetch.ts#L143-L148C6

Currently, `isLocalFetch` is true when the request starts with `/`, and if I redefine `globalThis.$fetch` and set `baseURL`, then it's wrong.

When I tried to fix this I found that `ofetch` couldn't get the `options.baseURL` for the current instance, so I open https://github.com/unjs/ofetch/issues/303#issuecomment-1774885204

cc @pi0 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt/nuxt/issues/23880

### ❓ Type of change
- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This updates the test for `isLocalFetch` to only match if there is no provided baseURL or the baseURL starts with `/`.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/composables/fetch.ts [hunk 1]
```diff
@@ -140,12 +140,9 @@ export function useFetch<
...
     controller = typeof AbortController !== 'undefined' ? new AbortController() : {} as AbortController
 
-    const isLocalFetch = typeof _request.value === 'string' && _request.value.startsWith('/')
-    let _$fetch = opts.$fetch || globalThis.$fetch
+    const isLocalFetch = typeof _request.value === 'string' && _request.value.startsWith('/') && (!unref(opts.baseURL) || unref(opts.baseURL)!.startsWith('/'))
     // Use fetch with request context and headers for server direct API calls
-    if (import.meta.server && !opts.$fetch && isLocalFetch) {
-      _$fetch = useRequestFetch()
-    }
+    const _$fetch = opts.$fetch || ((import.meta.server && isLocalFetch) ? useRequestFetch() : globalThis.$fetch)
```
Comment (pi0) [inline packages/nuxt/src/app/composables/fetch.ts:145]: Small perf: I'm not sure if this would be tree-shaken without modification so worth to double check if you can quickly check. Seems we need `isLocalFetch` computation only in server and without explicit `$fetch` option.

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/app/composables/fetch.ts [hunk 2]
```diff
@@ -140,12 +140,9 @@ export function useFetch<
     controller?.abort?.()
     controller = typeof AbortController !== 'undefined' ? new AbortController() : {} as AbortController
 
-    const isLocalFetch = typeof _request.value === 'string' && _request.value.startsWith('/')
-    let _$fetch = opts.$fetch || globalThis.$fetch
+    const isLocalFetch = typeof _request.value === 'string' && _request.value.startsWith('/') && (!unref(opts.baseURL) || unref(opts.baseURL)!.startsWith('/'))
```
Comment (KeJunMao) [inline packages/nuxt/src/app/composables/fetch.ts:143]:
```js
useFetch('/users', { $fetch: $fetch.create({ baseURL: 'https://example.com/api/' }) })
// isLocalFetch === true ?
```

File: packages/nuxt/src/app/composables/fetch.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/app/composables/fetch.ts:145]: yes, it's still tree-shaken.

File: packages/nuxt/src/app/composables/fetch.ts (hunk 2 above)
Comment (danielroe) [reply packages/nuxt/src/app/composables/fetch.ts:143]: yes, but it isn't used... will push a perf refactor to avoid computing it at all if not needed...
